#ifndef _MAP_OBJECTS_H_
#define _MAP_OBJECTS_H_

#include "common.h"

#define FIELD_HEIGHT 24
#define FIELD_WIDTH 20

#define MAX_FIELD_OBJECTS 218

/* ground object tool interaction flags */
#define GROUND_OBJECT_CUTTABLE 1
#define GROUND_OBJECT_TILLABLE 2
#define GROUND_OBJECT_CHOPPABLE 4
#define GROUND_OBJECT_HAMMERABLE 8
#define GROUND_OBJECT_WATERABLE 0x10
#define GROUND_OBJECT_PLANTABLE 0x20

/* field tiles */
#define BASE_TILE 1
#define TILLED 2	
#define TILLED_WATERED 3
#define SMALL_ROCK 4
#define WEED 5
#define LOG 6
#define BROKEN_LOG 7
#define TURNIP_PLANTED_STAGE_1 8
#define TURNIP_PLANTED_STAGE_1_WATERED 9
#define TURNIP_PLANTED_STAGE_2 10
#define TURNIP_PLANTED_STAGE_2_WATERED 11
#define TURNIP_SPROUT_STAGE_1 12
#define TURNIP_SPROUT_STAGE_1_WATERED 13
#define TURNIP_SPRPUT_STAGE_2 14
#define TURNIP_SPROUT_STAGE_2_WATERED 15
#define TURNIP_RIPE 16
#define TURNIP_RIPE_WATERED 17
#define TURNIP_DEAD 18
#define POTATO_PLANTED_STAGE_1 19
#define POTATO_PLANTED_STAGE_1_WATERED 20
#define POTATO_PLANTED_STAGE_2 21
#define POTATO_PLANTED_STAGE_2_WATERED 22
#define POTATO_PLANTED_STAGE_3 23
#define POTATO_PLANTED_STAGE_3_WATERED 24
#define POTATO_SPROUT_STAGE_1 25
#define POTATO_SPROUT_STAGE_1_WATERED 26
#define POTATO_SPROUT_STAGE_2 27
#define POTATO_SPROUT_STAGE_2_WATERED 28
#define POTATO_SPROUT_STAGE_3 29
#define POTATO_SPROUT_STAGE_3_WATERED 30
#define POTATO_RIPE 31
#define POTATO_RIPE_WATERED 32
#define POTATO_DEAD 33
#define EGGPLANT_PLANTED_STAGE_1 34
#define EGGPLANT_PLANTED_STAGE_1_WATERED 35
#define EGGPLANT_PLANTED_STAGE_2 36
#define EGGPLANT_PLANTED_STAGE_2_WATERED 37
#define EGGPLANT_SPROUT_STAGE_1 38
#define EGGPLANT_SPROUT_STAGE_1_WATERED 39
#define EGGPLANT_SPROUT_STAGE_2 40
#define EGGPLANT_SPROUT_STAGE_2_WATERED 41
#define EGGPLANT_STALK_STAGE_1 42
#define EGGPLANT_STALK_STAGE_1_WATERED 43
#define EGGPLANT_STALK_STAGE_2 44
#define EGGPLANT_STALK_STAGE_2_WATERED 45
#define EGGPLANT_STALK_STAGE_3 46
#define EGGPLANT_STALK_STAGE_3_WATERED 47
#define EGGPLANT_RIPE 48
#define EGGPLANT_RIPE_WATERED 49
#define EGGPLANT_DEAD 50
#define CABBAGE_PLANTED_STAGE_1 51
#define CABBAGE_PLANTED_STAGE_1_WATERED 52
#define CABBAGE_PLANTED_STAGE_2 53
#define CABBAGE_PLANTED_STAGE_2_WATERED 54
#define CABBAGE_PLANTED_STAGE_3 55
#define CABBAGE_PLANTED_STAGE_3_WATERED 56
#define CABBAGE_SPROUT_STAGE_1 57
#define CABBAGE_SPROUT_STAGE_1_WATERED 58
#define CABBAGE_SPROUT_STAGE_2 59
#define CABBAGE_SPROUT_STAGE_2_WATERED 60
#define CABBAGE_STALK_STAGE_1 61
#define CABBAGE_STALK_STAGE_1_WATERED 62
#define CABBAGE_STALK_STAGE_2 63
#define CABBAGE_STALK_STAGE_2_WATERED 64
#define CABBAGE_RIPE 65
#define CABBAGE_RIPE_WATERED 66
#define CABBAGE_DEAD 67
#define STRAWBERRY_PLANTED_STAGE_1 68
#define STRAWBERRY_PLANTED_STAGE_1_WATERED 69
#define STRAWBERRY_PLANTED_STAGE_2 70
#define STRAWBERRY_PLANTED_STAGE_2_WATERED 71
#define STRAWBERRY_SPROUT_STAGE_1 72
#define STRAWBERRY_SPROUT_STAGE_1_WATERED 73
#define STRAWBERRY_SPROUT_STAGE_2 74
#define STRAWBERRY_SPROUT_STAGE_2_WATERED 75
#define STRAWBERRY_STALK_STAGE_1 76
#define STRAWBERRY_STALK_STAGE_1_WATERED 77
#define STRAWBERRY_STALK_STAGE_2 78
#define STRAWBERRY_STALK_STAGE_2_WATERED 79
#define STRAWBERRY_RIPE 80
#define STRAWBERRY_RIPE_WATERED 81
#define STRAWBERRY_DEAD 82
#define TOMATO_PLANTED_STAGE_1 83
#define TOMATO_PLANTED_STAGE_1_WATERED 84
#define TOMATO_PLANTED_STAGE_2 85
#define TOMATO_PLANTED_STAGE_2_WATERED 86
#define TOMATO_SPROUT_STAGE_1 87
#define TOMATO_SPROUT_STAGE_1_WATERED 88
#define TOMATO_SPROUT_STAGE_2 89
#define TOMATO_SPROUT_STAGE_2_WATERED 90
#define TOMATO_STALK_STAGE_1 91
#define TOMATO_STALK_STAGE_1_WATERED 92
#define TOMATO_STALK_STAGE_2 93
#define TOMATO_STALK_STAGE_2_WATERED 94
#define TOMATO_PLANT_STAGE_1 95
#define TOMATO_PLANT_STAGE_1_WATERED 96
#define TOMATO_PLANT_STAGE_2 97
#define TOMATO_PLANT_STAGE_2_WATERED 98
#define TOMATO_PLANT_STAGE_3 99
#define TOMATO_PLANT_STAGE_3_WATERED 100
#define TOMATO_RIPE 101
#define TOMATO_RIPE_WATERED 102
#define TOMATO_DEAD 103
#define CORN_PLANTED_STAGE_1 104
#define CORN_PLANTED_STAGE_1_WATERED 105
#define CORN_PLANTED_STAGE_2 106
#define CORN_PLANTED_STAGE_2_WATERED 107
#define CORN_PLANTED_STAGE_3 108
#define CORN_PLANTED_STAGE_3_WATERED 109
#define CORN_SPROUT_STAGE_1 110
#define CORN_SPROUT_STAGE_1_WATERED 111
#define CORN_SPROUT_STAGE_2 112
#define CORN_SPROUT_STAGE_2_WATERED 113
#define CORN_SPROUT_STAGE_3 114
#define CORN_SPROUT_STAGE_3_WATERED 115
#define CORN_STALK_STAGE_1 116
#define CORN_STALK_STAGE_1_WATERED 117
#define CORN_STALK_STAGE_2 118
#define CORN_STALK_STAGE_2_WATERED 119
#define CORN_STALK_STAGE_3 120
#define CORN_STALK_STAGE_3_WATERED 121
#define CORN_PLANT_STAGE_1 122
#define CORN_PLANT_STAGE_1_WATERED 123
#define CORN_PLANT_STAGE_2 124
#define CORN_PLANT_STAGE_2_WATERED 125
#define CORN_PLANT_STAGE_3 126
#define CORN_PLANT_STAGE_3_WATERED 127
#define CORN_PLANT_STAGE_4 128
#define CORN_PLANT_STAGE_4_WATERED 129
#define CORN_RIPE 130
#define CORN_RIPE_WATERED 131
#define CORN_DEAD 132
#define GRASS_PLANTED_STAGE_1 133
#define GRASS_PLANTED_STAGE_2 134
#define GRASS_PLANTED_STAGE_3 135
#define GRASS_SPROUT_STAGE_1 136
#define GRASS_SPROUT_STAGE_2 137
#define GRASS_SPROUT_STAGE_3 138
#define GRASS_GROWING_STAGE_1 139
#define GRASS_GROWING_STAGE_2 140
#define GRASS_GROWING_STAGE_3 141
#define GRASS_RIPE 142
#define GRASS_CUT 143
#define MOONDROP_PLANTED_STAGE_1 144
#define MOONDROP_PLANTED_STAGE_1_WATERED 145
#define MOONDROP_PLANTED_STAGE_2 146
#define MOONDROP_PLANTED_STAGE_2_WATERED 147
#define MOONDROP_SPROUT_STAGE_1 148
#define MOONDROP_SPROUT_STAGE_1_WATERED 149
#define MOONDROP_SPROUT_STAGE_2 150
#define MOONDROP_SPROUT_STAGE_2_WATERED 151
#define MOONDROP_PLANT_STAGE_1 152
#define MOONDROP_PLANT_STAGE_1_WATERED 153
#define MOONDROP_PLANT_STAGE_2 154
#define MOONDROP_PLANT_STAGE_2_WATERED 155
#define MOONDROP_RIPE 156
#define MOONDROP_RIPE_WATERED 157
#define MOONDROP_DEAD 158
#define PINK_CAT_MINT_PLANTED_STAGE_1 159
#define PINK_CAT_MINT_PLANTED_STAGE_1_WATERED 160
#define PINK_CAT_MINT_PLANTED_STAGE_2 161
#define PINK_CAT_MINT_PLANTED_STAGE_2_WATERED 162
#define PINK_CAT_MINT_PLANTED_STAGE_3 163
#define PINK_CAT_MINT_PLANTED_STAGE_3_WATERED 164
#define PINK_CAT_MINT_SPROUT_STAGE_1 165
#define PINK_CAT_MINT_SPROUT_STAGE_1_WATERED 166
#define PINK_CAT_MINT_SPROUT_STAGE_2 167
#define PINK_CAT_MINT_SPROUT_STAGE_2_WATERED 168
#define PINK_CAT_MINT_SPROUT_STAGE_3 169
#define PINK_CAT_MINT_SPROUT_STAGE_3_WATERED 170
#define PINK_CAT_MINT_PLANT_STAGE_1 171
#define PINK_CAT_MINT_PLANT_STAGE_1_WATERED 172
#define PINK_CAT_MINT_PLANT_STAGE_2 173
#define PINK_CAT_MINT_PLANT_STAGE_2_WATERED 174
#define PINK_CAT_MINT_RIPE 175
#define PINK_CAT_MINT_RIPE_WATERED 176 
#define PINK_CAT_MINT_DEAD 177
#define BLUE_MIST_FLOWER_PLANTED_STAGE_1 178
#define BLUE_MIST_FLOWER_PLANTED_STAGE_1_WATERED 179
#define BLUE_MIST_FLOWER_PLANTED_STAGE_2 180
#define BLUE_MIST_FLOWER_PLANTED_STAGE_2_WATERED 181
#define BLUE_MIST_FLOWER_PLANTED_STAGE_3 182
#define BLUE_MIST_FLOWER_PLANTED_STAGE_4_WATERED 183
#define BLUE_MIST_FLOWER_SPROUT_STAGE_1 184
#define BLUE_MIST_FLOWER_SPROUT_STAGE_1_WATERED 185
#define BLUE_MIST_FLOWER_SPROUT_STAGE_2 186
#define BLUE_MIST_FLOWER_SPROUT_STAGE_2_WATERED 187
#define BLUE_MIST_FLOWER_SPROUT_STAGE_3 188
#define BLUE_MIST_FLOWER_SPROUT_STAGE_3_WATERED 189
#define BLUE_MIST_FLOWER_PLANT_STAGE_1 190
#define BLUE_MIST_FLOWER_PLANT_STAGE_1_WATERED 191
#define BLUE_MIST_FLOWER_PLANT_STAGE_2 192
#define BLUE_MIST_FLOWER_PLANT_STAGE_2_WATERED 193
#define BLUE_MIST_FLOWER_RIPE 194
#define BLUE_MIST_FLOWER_RIPE_WATERED 195
#define BOULDER 196
// 0xC5-0xC7 invisible spaces to trigger collision 
#define STUMP 200
// 0xC9-0xCB = invisible spaces to trigger collision
#define MEDICINAL_HERB_FIELD 204
#define EDIBLE_HERB_FIELD 205
#define VERYBERRY_FRUIT_FIELD 206
#define TROPICAL_FRUIT_FIELD 207
#define WALNUT_FIELD 208
#define WILD_GRAPES_FIELD 209
#define MUSHROOM_FIELD 210
#define POISONOUS_MUSHROOM_FIELD 211
#define BERRY_OF_FULLMOON_FIELD 212
#define MOONDROP_PLANT_FIELD 213
#define INVALID_GROUND_OBJECT 215

typedef struct {
    u8 mapAdditionIndex;
    u8 spriteIndex;
    u8 heldItemIndex;
    u8 toolInteractionFlags;
    u8 playerInteractionFlags;
} GroundObjectInfo;

extern u8 topOfMountain1FieldTiles[FIELD_HEIGHT][FIELD_WIDTH];
extern u8 moonMountainFieldTiles[FIELD_HEIGHT][FIELD_WIDTH];
extern u8 pondFieldTiles[FIELD_HEIGHT][FIELD_WIDTH];
extern u8 caveFieldTiles[FIELD_HEIGHT][FIELD_WIDTH];
extern u8 mineFieldTiles[FIELD_HEIGHT][FIELD_WIDTH];
extern u8 greenhouseFieldTiles[FIELD_HEIGHT][FIELD_WIDTH];
extern u8 mountain1FieldTiles[FIELD_HEIGHT][FIELD_WIDTH];
extern u8 mountain2FieldTiles[FIELD_HEIGHT][FIELD_WIDTH];
extern u8 ranchFieldTiles[FIELD_HEIGHT][FIELD_WIDTH];
extern u8 farmFieldTiles[FIELD_HEIGHT][FIELD_WIDTH];

extern void setMapGroundObjects(u8);   
extern bool checkAnimalCanEatGrass(void);               
extern void setDefaultGroundObjectsForLevel(); 
extern u8 getGroundObjectMapAdditionIndex(u8);              
extern u8 getHeldItemIndexFromGroundObject(u8);                 
extern u8 getGroundObjectToolInteractionFlags(u8);
extern u8 getGroundObjectPlayerInteractionsFlags(u8 index);     
extern u8 setFieldTile(u8, u8, u8, u8); 
extern void addGroundObjectToMap(u8, u8, u8, u8);
extern void addGroundObjectToMapFromPlayerPosition(u8, f32, u8);    
extern u8 getGroundObjectIndexFromPlayerPosition(f32, u8);  
extern u8 getGroundObjectIndexFromCoordinates(f32, f32); 
extern void updateFieldObjectsOvernight();                
extern void updateCropsIfRain();                                   
extern void randomlyAddWeedsToFarmField();     
extern void randomlyBreakLogPieces(u8);             
extern void clearForagableObjects(u8 mapIndex);
extern void randomlyCutGrass(u8);       
extern void randomlyDestroyCrops(u8);   
extern void randomlyResetGreenhouseTiles(u8);         
extern u16 getFarmGrassTilesSum();     
extern u16 getFarmMoondropFlowerCount();       
extern u16 getGreenhouseMoondropFlowerCount(void);
extern u16 getFarmPinkCatMintFlowersCount(void);     
extern u16 getGreenhousePinkCatMintFlowersCount(void);  
extern void removePinkCatMintFlowerFromFarm(void);

extern u8 blueMistFlowerPlot;

#endif