#include "game/fieldTiles.h"

// base farm
u8 D_80113580[FIELD_HEIGHT][FIELD_WIDTH] = {
    {SMALL_ROCK, SMALL_ROCK, BASE_TILE, SMALL_ROCK, BASE_TILE, BASE_TILE, SMALL_ROCK, BASE_TILE, SMALL_ROCK, WEED, WEED, BASE_TILE, BASE_TILE, SMALL_ROCK, SMALL_ROCK, SMALL_ROCK, SMALL_ROCK, SMALL_ROCK, SMALL_ROCK, SMALL_ROCK},
    {BASE_TILE, SMALL_ROCK, SMALL_ROCK, WEED, WEED, BASE_TILE, BASE_TILE, SMALL_ROCK, SMALL_ROCK, BASE_TILE, BOULDER, 0xC5, BASE_TILE, BASE_TILE, SMALL_ROCK, SMALL_ROCK, SMALL_ROCK, SMALL_ROCK, SMALL_ROCK, SMALL_ROCK},
    {BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, SMALL_ROCK, BASE_TILE, WEED, BASE_TILE, SMALL_ROCK, 0xC6, 0xC7, SMALL_ROCK, SMALL_ROCK, SMALL_ROCK, SMALL_ROCK, SMALL_ROCK, BOULDER, 0xC5, SMALL_ROCK},
    {BASE_TILE, WEED, WEED, BASE_TILE, SMALL_ROCK, SMALL_ROCK, WEED, WEED, SMALL_ROCK, SMALL_ROCK, SMALL_ROCK, BASE_TILE, BASE_TILE, SMALL_ROCK, SMALL_ROCK, SMALL_ROCK, SMALL_ROCK, 0xC6, 0xC7, SMALL_ROCK},
    {WEED, WEED, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, SMALL_ROCK, SMALL_ROCK, SMALL_ROCK, WEED, WEED, SMALL_ROCK, SMALL_ROCK, SMALL_ROCK, BASE_TILE, BASE_TILE, SMALL_ROCK, BASE_TILE},
    {SMALL_ROCK, WEED, BOULDER, 0xC5, BASE_TILE, SMALL_ROCK, BASE_TILE, BASE_TILE, SMALL_ROCK, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, WEED, WEED, BASE_TILE, BASE_TILE},
    {BASE_TILE, BASE_TILE, 0xC6, 0xC7, WEED, BASE_TILE, BASE_TILE, SMALL_ROCK, BASE_TILE, SMALL_ROCK, WEED, STUMP, 0xC9, WEED, WEED, WEED, WEED, WEED, BOULDER, 0xC5},
    {BASE_TILE, SMALL_ROCK, BASE_TILE, BASE_TILE, WEED, SMALL_ROCK, BASE_TILE, SMALL_ROCK, BASE_TILE, WEED, BASE_TILE, 0xCA, 0xCB, BASE_TILE, WEED, BASE_TILE, WEED, BASE_TILE, 0xC6, 0xC7},
    {WEED, SMALL_ROCK, SMALL_ROCK, BASE_TILE, WEED, BASE_TILE, BOULDER, 0xC5, SMALL_ROCK, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, SMALL_ROCK, BASE_TILE, STUMP, 0xC9, BASE_TILE, BASE_TILE, BASE_TILE},
    {SMALL_ROCK, SMALL_ROCK, SMALL_ROCK, BASE_TILE, BASE_TILE, BASE_TILE, 0xC6, 0xC7, BOULDER, 0xC5, BASE_TILE, BASE_TILE, SMALL_ROCK, SMALL_ROCK, BASE_TILE, 0xCA, 0xCB, SMALL_ROCK, BASE_TILE, WEED},
    {BASE_TILE, BASE_TILE, STUMP, 0xC9, BASE_TILE, BASE_TILE, SMALL_ROCK, SMALL_ROCK, 0xC6, 0xC7, BASE_TILE, SMALL_ROCK, SMALL_ROCK, SMALL_ROCK, SMALL_ROCK, SMALL_ROCK, BASE_TILE, WEED, SMALL_ROCK, WEED},
    {BASE_TILE, SMALL_ROCK, 0xCA, 0xCB, SMALL_ROCK, SMALL_ROCK, BASE_TILE, SMALL_ROCK, WEED, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, WEED, WEED, SMALL_ROCK, WEED, SMALL_ROCK, SMALL_ROCK},
    {SMALL_ROCK, SMALL_ROCK, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, SMALL_ROCK, BASE_TILE, SMALL_ROCK, BASE_TILE, STUMP, 0xC9, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, SMALL_ROCK, WEED},
    {SMALL_ROCK, SMALL_ROCK, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, WEED, BASE_TILE, BASE_TILE, SMALL_ROCK, BASE_TILE, 0xCA, 0xCB, WEED, BASE_TILE, STUMP, 0xC9, SMALL_ROCK, WEED},
    {SMALL_ROCK, BASE_TILE, SMALL_ROCK, WEED, WEED, WEED, WEED, BASE_TILE, STUMP, 0xC9, WEED, WEED, BASE_TILE, BASE_TILE, BASE_TILE, WEED, 0xCA, 0xCB, BASE_TILE, SMALL_ROCK},
    {BASE_TILE, WEED, SMALL_ROCK, BASE_TILE, BASE_TILE, BASE_TILE, WEED, BASE_TILE, 0xCA, 0xCB, BASE_TILE, WEED, BASE_TILE, BASE_TILE, WEED, SMALL_ROCK, BASE_TILE, STUMP, 0xC9, BASE_TILE},
    {BASE_TILE, WEED, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, SMALL_ROCK, WEED, SMALL_ROCK, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, 0xCA, 0xCB, SMALL_ROCK},
    {BASE_TILE, BASE_TILE, BASE_TILE, WEED, STUMP, 0xC9, BASE_TILE, SMALL_ROCK, SMALL_ROCK, SMALL_ROCK, BASE_TILE, BASE_TILE, SMALL_ROCK, SMALL_ROCK, BASE_TILE, STUMP, 0xC9, BASE_TILE, SMALL_ROCK, SMALL_ROCK},
    {BOULDER, 0xC5, BASE_TILE, BASE_TILE, 0xCA, 0xCB, BASE_TILE, SMALL_ROCK, WEED, WEED, STUMP, 0xC9, WEED, WEED, BASE_TILE, 0xCA, 0xCB, BASE_TILE, BASE_TILE, BASE_TILE},
    {0xC6, 0xC7, BASE_TILE, SMALL_ROCK, BASE_TILE, BASE_TILE, SMALL_ROCK, BASE_TILE, WEED, WEED, 0xCA, 0xCB, BASE_TILE, WEED, BASE_TILE, BASE_TILE, BASE_TILE, BOULDER, 0xC5, SMALL_ROCK},
    {WEED, WEED, SMALL_ROCK, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, WEED, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, SMALL_ROCK, BASE_TILE, SMALL_ROCK, 0xC6, 0xC7, SMALL_ROCK},
    {WEED, WEED, SMALL_ROCK, BASE_TILE, WEED, WEED, BASE_TILE, WEED, SMALL_ROCK, BASE_TILE, SMALL_ROCK, SMALL_ROCK, SMALL_ROCK, BASE_TILE, SMALL_ROCK, SMALL_ROCK, SMALL_ROCK, SMALL_ROCK, WEED, SMALL_ROCK},
    {BASE_TILE, SMALL_ROCK, BASE_TILE, SMALL_ROCK, WEED, WEED, SMALL_ROCK, SMALL_ROCK, BASE_TILE, WEED, BASE_TILE, SMALL_ROCK, SMALL_ROCK, SMALL_ROCK, BASE_TILE, SMALL_ROCK, SMALL_ROCK, WEED, WEED, SMALL_ROCK},
    {BASE_TILE, WEED, WEED, BASE_TILE, SMALL_ROCK, BASE_TILE, SMALL_ROCK, SMALL_ROCK, WEED, WEED, BASE_TILE, BASE_TILE, SMALL_ROCK, BASE_TILE, BASE_TILE, WEED, SMALL_ROCK, BASE_TILE, WEED, BASE_TILE}
};

// greenhouse reset
u8 D_80113760[FIELD_HEIGHT][FIELD_WIDTH] = {
    {BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, 0, 0, 0, 0},
    {BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, 0, 0, 0, 0},
    {BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, 0, 0, 0, 0},
    {BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, 0, 0, 0, 0},
    {BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, 0, 0, 0, 0},
    {BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, 0, 0, 0, 0},
    {BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, 0, 0, 0, 0},
    {BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, 0, 0, 0, 0},
    {BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, 0, 0, 0, 0},
    {BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, 0, 0, 0, 0},
    {BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, 0, 0, 0, 0},
    {BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, 0, 0, 0, 0},
    {BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, 0, 0, 0, 0},
    {BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, 0, 0, 0, 0},
    {BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, 0, 0, 0, 0},
    {BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, BASE_TILE, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
};

// ranch flowers
u8 D_80113940[FIELD_HEIGHT][FIELD_WIDTH] = {
    {MOONDROP_PLANT_FIELD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {MOONDROP_PLANT_FIELD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {MOONDROP_PLANT_FIELD, MOONDROP_PLANT_FIELD, MOONDROP_PLANT_FIELD, MOONDROP_PLANT_FIELD, MOONDROP_PLANT_FIELD, MOONDROP_PLANT_FIELD, MOONDROP_PLANT_FIELD, MOONDROP_PLANT_FIELD, MOONDROP_PLANT_FIELD, MOONDROP_PLANT_FIELD, MOONDROP_PLANT_FIELD, MOONDROP_PLANT_FIELD, MOONDROP_PLANT_FIELD, MOONDROP_PLANT_FIELD, MOONDROP_PLANT_FIELD, 0, 0, 0, 0, 0},
    {MOONDROP_PLANT_FIELD, MOONDROP_PLANT_FIELD, MOONDROP_PLANT_FIELD, MOONDROP_PLANT_FIELD, MOONDROP_PLANT_FIELD, MOONDROP_PLANT_FIELD, MOONDROP_PLANT_FIELD, MOONDROP_PLANT_FIELD, MOONDROP_PLANT_FIELD, MOONDROP_PLANT_FIELD, MOONDROP_PLANT_FIELD, MOONDROP_PLANT_FIELD, MOONDROP_PLANT_FIELD, MOONDROP_PLANT_FIELD, MOONDROP_PLANT_FIELD, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
};