#include "common.h"

#include "game/shop.h"

#include "ld_symbols.h"

#include "system/controller.h"
#include "system/entity.h"
#include "system/map.h"
#include "system/mapController.h"
#include "system/message.h"
#include "system/numberSprites.h"
#include "system/globalSprites.h"
#include "system/sprite.h"

#include "game/animals.h"
#include "game/cutscenes.h"
#include "game/game.h"
#include "game/gameAudio.h"
#include "game/gameStatus.h"
#include "game/items.h"
#include "game/level.h"
#include "game/overlayScreens.h"
#include "game/player.h"
#include "game/time.h"
#include "game/transition.h"

#include "mainLoop.h"

#include "assetIndices/cutscenes.h" 
#include "assetIndices/maps.h"
#include "assetIndices/sfxs.h"
#include "assetIndices/sprites.h"

#include "buffers/buffers.h"

#include "data/animation/entityAnimationScripts/entityAnimationScripts.h"

// bss
ShopContext shopContext;
u16 shopGiftTextIndex;

// shared bss
u8 flowerShopPoints;
u8 bakeryCardPoints;

// data

/* All arrays below are indexed by the TOTAL_SHOP_ITEMS-sized shop-item-index
 * space defined in shop.h. Rows of 4 align with the physical shop groupings:
 *
 *   row 0  (0-3)    flower shop: turnip/potato/cabbage/grass seeds
 *   row 1  (4-7)    flower shop: tomato/corn/eggplant/strawberry seeds
 *   row 2  (8-11)   flower shop: moon-drop, (gap 9), blue-mist; bakery cake
 *   row 3  (12-15)  bakery pie; inn/diner slots 13-15
 *   row 4  (16-19)  inn/diner slots 16-18; Rick store milker
 *   row 5  (20-23)  Rick store: brush/clippers/blue feather/rug
 *   row 6  (24-27)  Rick store cabinet/pot; ranch chicken feed/miracle potion
 *   row 7  (28-31)  ranch cow medicine/fodder; animal shop chicken/sheep
 *   row 8  (32-35)  ranch store animals; potion shop A/B
 *   row 9  (36-39)  potion shop C; souvenir shop ocarina/vase-early/vase
 *   row 10 (40-43)  inn menu: wine, liquor, beer, milk
 *   row 11 (44-47)  inn menu water; festival vendor slots
 *   row 12 (48-51)  festival vendor slots
 *   row 13 (52-55)  festival vendor slot; flower-fest seeds; flower-fest / fireworks empty-bottle grants
 */

u16 itemDescriptionTextIndices[TOTAL_SHOP_ITEMS] = {
    21,  // FLOWER_SHOP_TURNIP_SEEDS_ITEM
    22,  // FLOWER_SHOP_POTATO_SEEDS_ITEM
    23,  // FLOWER_SHOP_CABBAGE_SEEDS_ITEM
    28,  // FLOWER_SHOP_GRASS_SEEDS_ITEM
    24,  // FLOWER_SHOP_TOMATO_SEEDS_ITEM
    25,  // FLOWER_SHOP_CORN_SEEDS_ITEM
    26,  // FLOWER_SHOP_EGGPLANT_SEEDS_ITEM
    27,  // FLOWER_SHOP_STRAWBERRY_SEEDS_ITEM
    29,  // FLOWER_SHOP_MOON_DROP_SEEDS_ITEM
    30,  // (unused)
    31,  // FLOWER_SHOP_BLUE_MIST_SEEDS_ITEM
    0,   // BAKERY_CAKE_ITEM
    0,   // BAKERY_PIE_ITEM
    0,   // BAKERY_COOKIES
    0,   // BAKERY_CAKE
    0,   // BAKERY_PIE
    0,   // BAKERY_TEA
    0,   // BAKERY_WATER
    0,   // (gap)
    42,  // RICK_STORE_MILKER_ITEM
    43,  // RICK_STORE_BRUSH_ITEM
    44,  // RICK_STORE_CLIPPERS_ITEM
    45,  // RICK_STORE_BLUE_FEATHER_ITEM
    49,  // RICK_STORE_RUG_ITEM
    50,  // RICK_STORE_CABINET_ITEM
    51,  // RICK_STORE_ICE_CREAM_MAKER_ITEM
    69,  // RANCH_STORE_CHICKEN_FEED_ITEM
    70,  // RANCH_STORE_MIRACLE_POTION_ITEM
    71,  // RANCH_STORE_COW_MEDICINE_ITEM
    72,  // RANCH_STORE_FODDER_ITEM
    0,   // RANCH_STORE_CHICKEN_ITEM
    0,   // RANCH_STORE_SHEEP_ITEM
    0,   // RANCH_STORE_COW_ITEM
    0,   // RANCH_STORE_SHOP_CANCEL
    101, // POTION_SHOP_CURE_ALL_ITEM
    102, // POTION_SHOP_VITAMIN_ITEM
    103, // POTION_SHOP_STRONG_VITAMINS_ITEM
    114, // SOUVENIR_SHOP_OCARINA_ITEM
    115, // SOUVENIR_SHOP_VASE_EARLY_ITEM
    116, // SOUVENIR_SHOP_BLUE_VASE_ITEM
    0,   // TAVERN_WINE_ITEM
    0,   // TAVERN_LIQUOR_ITEM
    0,   // TAVERN_BEER_ITEM
    0,   // TAVERN_MILK_ITEM
    0,   // TAVERN_WATERN_ITEM
    0,   // HORSE_RACE_TEA
    0,   // HORSE_RACE_MILK
    0,   // DOG_RACE_TEA
    0,   // DOR_RACE_MILK
    0,   // RACE_COOKIES
    0,   // FESTIVAL_COTTON_CANDY
    0,   // FESTIVAL_FRIED_OCTOPUS
    0,   // FESTIVAL_ROASTED_CORN
    39,  // FLOWER_FESTIVAL_PINK_CAT_MINT_SEEDS_ITEM
    37,  // FLOWER_FESTIVAL_EMPTY_BOTTLE_ITEM
    37   // FIREWORKS_FESTIVAL_EMPTY_BOTTLE_ITEM
};

u16 purchaseConfirmationTextIndices[TOTAL_SHOP_ITEMS] = {
    32,  // FLOWER_SHOP_TURNIP_SEEDS_ITEM
    32,  // FLOWER_SHOP_POTATO_SEEDS_ITEM
    32,  // FLOWER_SHOP_CABBAGE_SEEDS_ITEM
    32,  // FLOWER_SHOP_GRASS_SEEDS_ITEM
    32,  // FLOWER_SHOP_TOMATO_SEEDS_ITEM
    32,  // FLOWER_SHOP_CORN_SEEDS_ITEM
    32,  // FLOWER_SHOP_EGGPLANT_SEEDS_ITEM
    32,  // FLOWER_SHOP_STRAWBERRY_SEEDS_ITEM
    32,  // FLOWER_SHOP_MOON_DROP_SEEDS_ITEM
    32,  // (unused)
    32,  // FLOWER_SHOP_BLUE_MIST_SEEDS_ITEM
    0,   // BAKERY_CAKE_ITEM
    0,   // BAKERY_PIE_ITEM
    0,   // BAKERY_COOKIES
    0,   // BAKERY_CAKE
    0,   // BAKERY_PIE
    0,   // BAKERY_TEA
    0,   // BAKERY_WATER
    0,   // (gap)
    339, // RICK_STORE_MILKER_ITEM
    339, // RICK_STORE_BRUSH_ITEM
    339, // RICK_STORE_CLIPPERS_ITEM
    339, // RICK_STORE_BLUE_FEATHER_ITEM
    339, // RICK_STORE_RUG_ITEM
    339, // RICK_STORE_CABINET_ITEM
    339, // RICK_STORE_ICE_CREAM_MAKER_ITEM
    338, // RANCH_STORE_CHICKEN_FEED_ITEM
    338, // RANCH_STORE_MIRACLE_POTION_ITEM
    338, // RANCH_STORE_COW_MEDICINE_ITEM
    338, // RANCH_STORE_FODDER_ITEM
    338, // RANCH_STORE_CHICKEN_ITEM
    338, // RANCH_STORE_SHEEP_ITEM
    338, // RANCH_STORE_COW_ITEM
    338, // RANCH_STORE_SHOP_CANCEL
    343, // POTION_SHOP_CURE_ALL_ITEM
    343, // POTION_SHOP_VITAMIN_ITEM
    343, // POTION_SHOP_STRONG_VITAMINS_ITEM
    341, // SOUVENIR_SHOP_OCARINA_ITEM
    341, // SOUVENIR_SHOP_VASE_EARLY_ITEM
    341, // SOUVENIR_SHOP_BLUE_VASE_ITEM
    0,   // TAVERN_WINE_ITEM
    0,   // TAVERN_LIQUOR_ITEM
    0,   // TAVERN_BEER_ITEM
    0,   // TAVERN_MILK_ITEM
    0,   // TAVERN_WATERN_ITEM
    0,   // HORSE_RACE_TEA
    0,   // HORSE_RACE_MILK
    0,   // DOG_RACE_TEA
    0,   // DOR_RACE_MILK
    0,   // RACE_COOKIES
    0,   // FESTIVAL_COTTON_CANDY
    0,   // FESTIVAL_FRIED_OCTOPUS
    0,   // FESTIVAL_ROASTED_CORN
    40,  // FLOWER_FESTIVAL_PINK_CAT_MINT_SEEDS_ITEM
    78,  // FLOWER_FESTIVAL_EMPTY_BOTTLE_ITEM
    78   // FIREWORKS_FESTIVAL_EMPTY_BOTTLE_ITEM
};

u16 declinePurchaseTextIndices[TOTAL_SHOP_ITEMS] = {
    34,  // FLOWER_SHOP_TURNIP_SEEDS_ITEM
    34,  // FLOWER_SHOP_POTATO_SEEDS_ITEM
    34,  // FLOWER_SHOP_CABBAGE_SEEDS_ITEM
    34,  // FLOWER_SHOP_GRASS_SEEDS_ITEM
    34,  // FLOWER_SHOP_TOMATO_SEEDS_ITEM
    34,  // FLOWER_SHOP_CORN_SEEDS_ITEM
    34,  // FLOWER_SHOP_EGGPLANT_SEEDS_ITEM
    34,  // FLOWER_SHOP_STRAWBERRY_SEEDS_ITEM
    34,  // FLOWER_SHOP_MOON_DROP_SEEDS_ITEM
    34,  // (unused)
    34,  // FLOWER_SHOP_BLUE_MIST_SEEDS_ITEM
    63,  // BAKERY_CAKE_ITEM
    63,  // BAKERY_PIE_ITEM
    63,  // BAKERY_COOKIES
    63,  // BAKERY_CAKE
    63,  // BAKERY_PIE
    63,  // BAKERY_TEA
    63,  // BAKERY_WATER
    63,  // (gap)
    47,  // RICK_STORE_MILKER_ITEM
    47,  // RICK_STORE_BRUSH_ITEM
    47,  // RICK_STORE_CLIPPERS_ITEM
    47,  // RICK_STORE_BLUE_FEATHER_ITEM
    47,  // RICK_STORE_RUG_ITEM
    47,  // RICK_STORE_CABINET_ITEM
    47,  // RICK_STORE_ICE_CREAM_MAKER_ITEM
    74,  // RANCH_STORE_CHICKEN_FEED_ITEM
    74,  // RANCH_STORE_MIRACLE_POTION_ITEM
    74,  // RANCH_STORE_COW_MEDICINE_ITEM
    74,  // RANCH_STORE_FODDER_ITEM
    84,  // RANCH_STORE_CHICKEN_ITEM
    84,  // RANCH_STORE_SHEEP_ITEM
    84,  // RANCH_STORE_COW_ITEM
    84,  // RANCH_STORE_SHOP_CANCEL
    105, // POTION_SHOP_CURE_ALL_ITEM
    105, // POTION_SHOP_VITAMIN_ITEM
    105, // POTION_SHOP_STRONG_VITAMINS_ITEM
    118, // SOUVENIR_SHOP_OCARINA_ITEM
    118, // SOUVENIR_SHOP_VASE_EARLY_ITEM
    118, // SOUVENIR_SHOP_BLUE_VASE_ITEM
    0,   // TAVERN_WINE_ITEM
    0,   // TAVERN_LIQUOR_ITEM
    0,   // TAVERN_BEER_ITEM
    0,   // TAVERN_MILK_ITEM
    0,   // TAVERN_WATERN_ITEM
    0,   // HORSE_RACE_TEA
    0,   // HORSE_RACE_MILK
    0,   // DOG_RACE_TEA
    0,   // DOR_RACE_MILK
    0,   // RACE_COOKIES
    0,   // FESTIVAL_COTTON_CANDY
    0,   // FESTIVAL_FRIED_OCTOPUS
    0,   // FESTIVAL_ROASTED_CORN
    42,  // FLOWER_FESTIVAL_PINK_CAT_MINT_SEEDS_ITEM
    44,  // FLOWER_FESTIVAL_EMPTY_BOTTLE_ITEM
    44   // FIREWORKS_FESTIVAL_EMPTY_BOTTLE_ITEM
};

u16 postPurchaseTextIndices[TOTAL_SHOP_ITEMS] = {
    33,  // FLOWER_SHOP_TURNIP_SEEDS_ITEM
    33,  // FLOWER_SHOP_POTATO_SEEDS_ITEM
    33,  // FLOWER_SHOP_CABBAGE_SEEDS_ITEM
    33,  // FLOWER_SHOP_GRASS_SEEDS_ITEM
    33,  // FLOWER_SHOP_TOMATO_SEEDS_ITEM
    33,  // FLOWER_SHOP_CORN_SEEDS_ITEM
    33,  // FLOWER_SHOP_EGGPLANT_SEEDS_ITEM
    33,  // FLOWER_SHOP_STRAWBERRY_SEEDS_ITEM
    33,  // FLOWER_SHOP_MOON_DROP_SEEDS_ITEM
    33,  // (unused)
    33,  // FLOWER_SHOP_BLUE_MIST_SEEDS_ITEM
    62,  // BAKERY_CAKE_ITEM
    62,  // BAKERY_PIE_ITEM
    62,  // BAKERY_COOKIES
    58,  // BAKERY_CAKE
    58,  // BAKERY_PIE
    58,  // BAKERY_TEA
    58,  // BAKERY_WATER
    58,  // (gap)
    46,  // RICK_STORE_MILKER_ITEM
    46,  // RICK_STORE_BRUSH_ITEM
    46,  // RICK_STORE_CLIPPERS_ITEM
    46,  // RICK_STORE_BLUE_FEATHER_ITEM
    53,  // RICK_STORE_RUG_ITEM
    53,  // RICK_STORE_CABINET_ITEM
    53,  // RICK_STORE_ICE_CREAM_MAKER_ITEM
    73,  // RANCH_STORE_CHICKEN_FEED_ITEM
    73,  // RANCH_STORE_MIRACLE_POTION_ITEM
    73,  // RANCH_STORE_COW_MEDICINE_ITEM
    73,  // RANCH_STORE_FODDER_ITEM
    80,  // RANCH_STORE_CHICKEN_ITEM
    80,  // RANCH_STORE_SHEEP_ITEM
    80,  // RANCH_STORE_COW_ITEM
    80,  // RANCH_STORE_SHOP_CANCEL
    104, // POTION_SHOP_CURE_ALL_ITEM
    104, // POTION_SHOP_VITAMIN_ITEM
    104, // POTION_SHOP_STRONG_VITAMINS_ITEM
    117, // SOUVENIR_SHOP_OCARINA_ITEM
    115, // SOUVENIR_SHOP_VASE_EARLY_ITEM
    117, // SOUVENIR_SHOP_BLUE_VASE_ITEM
    123, // TAVERN_WINE_ITEM
    123, // TAVERN_LIQUOR_ITEM
    123, // TAVERN_BEER_ITEM
    124, // TAVERN_MILK_ITEM
    124, // TAVERN_WATERN_ITEM
    19,  // HORSE_RACE_TEA
    19,  // HORSE_RACE_MILK
    19,  // DOG_RACE_TEA
    19,  // DOR_RACE_MILK
    19,  // RACE_COOKIES
    30,  // FESTIVAL_COTTON_CANDY
    30,  // FESTIVAL_FRIED_OCTOPUS
    30,  // FESTIVAL_ROASTED_CORN
    46,  // FLOWER_FESTIVAL_PINK_CAT_MINT_SEEDS_ITEM
    47,  // FLOWER_FESTIVAL_EMPTY_BOTTLE_ITEM
    47   // FIREWORKS_FESTIVAL_EMPTY_BOTTLE_ITEM
};

u16 notEnoughMoneyTextIndices[TOTAL_SHOP_ITEMS] = {
    35,  // FLOWER_SHOP_TURNIP_SEEDS_ITEM
    35,  // FLOWER_SHOP_POTATO_SEEDS_ITEM
    35,  // FLOWER_SHOP_CABBAGE_SEEDS_ITEM
    35,  // FLOWER_SHOP_GRASS_SEEDS_ITEM
    35,  // FLOWER_SHOP_TOMATO_SEEDS_ITEM
    35,  // FLOWER_SHOP_CORN_SEEDS_ITEM
    35,  // FLOWER_SHOP_EGGPLANT_SEEDS_ITEM
    35,  // FLOWER_SHOP_STRAWBERRY_SEEDS_ITEM
    35,  // FLOWER_SHOP_MOON_DROP_SEEDS_ITEM
    35,  // (unused)
    35,  // FLOWER_SHOP_BLUE_MIST_SEEDS_ITEM
    64,  // BAKERY_CAKE_ITEM
    64,  // BAKERY_PIE_ITEM
    64,  // BAKERY_COOKIES
    64,  // BAKERY_CAKE
    64,  // BAKERY_PIE
    64,  // BAKERY_TEA
    64,  // BAKERY_WATER
    64,  // (gap)
    48,  // RICK_STORE_MILKER_ITEM
    48,  // RICK_STORE_BRUSH_ITEM
    48,  // RICK_STORE_CLIPPERS_ITEM
    48,  // RICK_STORE_BLUE_FEATHER_ITEM
    48,  // RICK_STORE_RUG_ITEM
    48,  // RICK_STORE_CABINET_ITEM
    48,  // RICK_STORE_ICE_CREAM_MAKER_ITEM
    75,  // RANCH_STORE_CHICKEN_FEED_ITEM
    75,  // RANCH_STORE_MIRACLE_POTION_ITEM
    75,  // RANCH_STORE_COW_MEDICINE_ITEM
    75,  // RANCH_STORE_FODDER_ITEM
    75,  // RANCH_STORE_CHICKEN_ITEM
    75,  // RANCH_STORE_SHEEP_ITEM
    75,  // RANCH_STORE_COW_ITEM
    75,  // RANCH_STORE_SHOP_CANCEL
    106, // POTION_SHOP_CURE_ALL_ITEM
    106, // POTION_SHOP_VITAMIN_ITEM
    106, // POTION_SHOP_STRONG_VITAMINS_ITEM
    119, // SOUVENIR_SHOP_OCARINA_ITEM
    119, // SOUVENIR_SHOP_VASE_EARLY_ITEM
    119, // SOUVENIR_SHOP_BLUE_VASE_ITEM
    57,  // TAVERN_WINE_ITEM
    57,  // TAVERN_LIQUOR_ITEM
    57,  // TAVERN_BEER_ITEM
    57,  // TAVERN_MILK_ITEM
    57,  // TAVERN_WATERN_ITEM
    21,  // HORSE_RACE_TEA
    21,  // HORSE_RACE_MILK
    21,  // DOG_RACE_TEA
    21,  // DOR_RACE_MILK
    21,  // RACE_COOKIES
    32,  // FESTIVAL_COTTON_CANDY
    32,  // FESTIVAL_FRIED_OCTOPUS
    32,  // FESTIVAL_ROASTED_CORN
    43,  // FLOWER_FESTIVAL_PINK_CAT_MINT_SEEDS_ITEM
    41,  // FLOWER_FESTIVAL_EMPTY_BOTTLE_ITEM
    41   // FIREWORKS_FESTIVAL_EMPTY_BOTTLE_ITEM
};

u16 exceedMaxQuantityTextIndices[TOTAL_SHOP_ITEMS] = {
    344, // FLOWER_SHOP_TURNIP_SEEDS_ITEM
    344, // FLOWER_SHOP_POTATO_SEEDS_ITEM
    344, // FLOWER_SHOP_CABBAGE_SEEDS_ITEM
    344, // FLOWER_SHOP_GRASS_SEEDS_ITEM
    344, // FLOWER_SHOP_TOMATO_SEEDS_ITEM
    344, // FLOWER_SHOP_CORN_SEEDS_ITEM
    344, // FLOWER_SHOP_EGGPLANT_SEEDS_ITEM
    344, // FLOWER_SHOP_STRAWBERRY_SEEDS_ITEM
    344, // FLOWER_SHOP_MOON_DROP_SEEDS_ITEM
    344, // (unused)
    344, // FLOWER_SHOP_BLUE_MIST_SEEDS_ITEM
    0,   // BAKERY_CAKE_ITEM
    0,   // BAKERY_PIE_ITEM
    0,   // BAKERY_COOKIES
    0,   // BAKERY_CAKE
    0,   // BAKERY_PIE
    0,   // BAKERY_TEA
    0,   // BAKERY_WATER
    0,   // (gap)
    0,   // RICK_STORE_MILKER_ITEM
    0,   // RICK_STORE_BRUSH_ITEM
    0,   // RICK_STORE_CLIPPERS_ITEM
    0,   // RICK_STORE_BLUE_FEATHER_ITEM
    0,   // RICK_STORE_RUG_ITEM
    0,   // RICK_STORE_CABINET_ITEM
    0,   // RICK_STORE_ICE_CREAM_MAKER_ITEM
    345, // RANCH_STORE_CHICKEN_FEED_ITEM
    345, // RANCH_STORE_MIRACLE_POTION_ITEM
    345, // RANCH_STORE_COW_MEDICINE_ITEM
    345, // RANCH_STORE_FODDER_ITEM
    86,  // RANCH_STORE_CHICKEN_ITEM
    86,  // RANCH_STORE_SHEEP_ITEM
    86,  // RANCH_STORE_COW_ITEM
    86,  // RANCH_STORE_SHOP_CANCEL
    0,   // POTION_SHOP_CURE_ALL_ITEM
    0,   // POTION_SHOP_VITAMIN_ITEM
    0,   // POTION_SHOP_STRONG_VITAMINS_ITEM
    0,   // SOUVENIR_SHOP_OCARINA_ITEM
    0,   // SOUVENIR_SHOP_VASE_EARLY_ITEM
    0,   // SOUVENIR_SHOP_BLUE_VASE_ITEM
    0,   // TAVERN_WINE_ITEM
    0,   // TAVERN_LIQUOR_ITEM
    0,   // TAVERN_BEER_ITEM
    0,   // TAVERN_MILK_ITEM
    0,   // TAVERN_WATERN_ITEM
    0,   // HORSE_RACE_TEA
    0,   // HORSE_RACE_MILK
    0,   // DOG_RACE_TEA
    0,   // DOR_RACE_MILK
    0,   // RACE_COOKIES
    0,   // FESTIVAL_COTTON_CANDY
    0,   // FESTIVAL_FRIED_OCTOPUS
    0,   // FESTIVAL_ROASTED_CORN
    45,  // FLOWER_FESTIVAL_PINK_CAT_MINT_SEEDS_ITEM
    0,   // FLOWER_FESTIVAL_EMPTY_BOTTLE_ITEM
    0    // FIREWORKS_FESTIVAL_EMPTY_BOTTLE_ITEM
};

// no space in rucksack
u16 sendToFarmTextIndices[TOTAL_SHOP_ITEMS] = {
    346, // FLOWER_SHOP_TURNIP_SEEDS_ITEM
    346, // FLOWER_SHOP_POTATO_SEEDS_ITEM
    346, // FLOWER_SHOP_CABBAGE_SEEDS_ITEM
    346, // FLOWER_SHOP_GRASS_SEEDS_ITEM
    346, // FLOWER_SHOP_TOMATO_SEEDS_ITEM
    346, // FLOWER_SHOP_CORN_SEEDS_ITEM
    346, // FLOWER_SHOP_EGGPLANT_SEEDS_ITEM
    346, // FLOWER_SHOP_STRAWBERRY_SEEDS_ITEM
    346, // FLOWER_SHOP_MOON_DROP_SEEDS_ITEM
    346, // (unused)
    346, // FLOWER_SHOP_BLUE_MIST_SEEDS_ITEM
    0,   // BAKERY_CAKE_ITEM
    0,   // BAKERY_PIE_ITEM
    0,   // BAKERY_COOKIES
    0,   // BAKERY_CAKE
    0,   // BAKERY_PIE
    0,   // BAKERY_TEA
    0,   // BAKERY_WATER
    0,   // (gap)
    347, // RICK_STORE_MILKER_ITEM
    347, // RICK_STORE_BRUSH_ITEM
    347, // RICK_STORE_CLIPPERS_ITEM
    347, // RICK_STORE_BLUE_FEATHER_ITEM
    347, // RICK_STORE_RUG_ITEM
    347, // RICK_STORE_CABINET_ITEM
    347, // RICK_STORE_ICE_CREAM_MAKER_ITEM
    348, // RANCH_STORE_CHICKEN_FEED_ITEM
    348, // RANCH_STORE_MIRACLE_POTION_ITEM
    348, // RANCH_STORE_COW_MEDICINE_ITEM
    348, // RANCH_STORE_FODDER_ITEM
    0,   // RANCH_STORE_CHICKEN_ITEM
    0,   // RANCH_STORE_SHEEP_ITEM
    0,   // RANCH_STORE_COW_ITEM
    0,   // RANCH_STORE_SHOP_CANCEL
    0,   // POTION_SHOP_CURE_ALL_ITEM
    0,   // POTION_SHOP_VITAMIN_ITEM
    0,   // POTION_SHOP_STRONG_VITAMINS_ITEM
    349, // SOUVENIR_SHOP_OCARINA_ITEM
    349, // SOUVENIR_SHOP_VASE_EARLY_ITEM
    349, // SOUVENIR_SHOP_BLUE_VASE_ITEM
    0,   // TAVERN_WINE_ITEM
    0,   // TAVERN_LIQUOR_ITEM
    0,   // TAVERN_BEER_ITEM
    0,   // TAVERN_MILK_ITEM
    0,   // TAVERN_WATERN_ITEM
    0,   // HORSE_RACE_TEA
    0,   // HORSE_RACE_MILK
    0,   // DOG_RACE_TEA
    0,   // DOR_RACE_MILK
    0,   // RACE_COOKIES
    0,   // FESTIVAL_COTTON_CANDY
    0,   // FESTIVAL_FRIED_OCTOPUS
    0,   // FESTIVAL_ROASTED_CORN
    46,  // FLOWER_FESTIVAL_PINK_CAT_MINT_SEEDS_ITEM
    47,  // FLOWER_FESTIVAL_EMPTY_BOTTLE_ITEM
    47   // FIREWORKS_FESTIVAL_EMPTY_BOTTLE_ITEM
};

u16 shopItemTextAddressesIndex[TOTAL_SHOP_ITEMS] = {
    6, // FLOWER_SHOP_TURNIP_SEEDS_ITEM
    6, // FLOWER_SHOP_POTATO_SEEDS_ITEM
    6, // FLOWER_SHOP_CABBAGE_SEEDS_ITEM
    6, // FLOWER_SHOP_GRASS_SEEDS_ITEM
    6, // FLOWER_SHOP_TOMATO_SEEDS_ITEM
    6, // FLOWER_SHOP_CORN_SEEDS_ITEM
    6, // FLOWER_SHOP_EGGPLANT_SEEDS_ITEM
    6, // FLOWER_SHOP_STRAWBERRY_SEEDS_ITEM
    6, // FLOWER_SHOP_MOON_DROP_SEEDS_ITEM
    6, // (unused)
    6, // FLOWER_SHOP_BLUE_MIST_SEEDS_ITEM
    6, // BAKERY_CAKE_ITEM
    6, // BAKERY_PIE_ITEM
    6, // BAKERY_COOKIES
    6, // BAKERY_CAKE
    6, // BAKERY_PIE
    6, // BAKERY_TEA
    6, // BAKERY_WATER
    6, // (gap)
    6, // RICK_STORE_MILKER_ITEM
    6, // RICK_STORE_BRUSH_ITEM
    6, // RICK_STORE_CLIPPERS_ITEM
    6, // RICK_STORE_BLUE_FEATHER_ITEM
    6, // RICK_STORE_RUG_ITEM
    6, // RICK_STORE_CABINET_ITEM
    6, // RICK_STORE_ICE_CREAM_MAKER_ITEM
    6, // RANCH_STORE_CHICKEN_FEED_ITEM
    6, // RANCH_STORE_MIRACLE_POTION_ITEM
    6, // RANCH_STORE_COW_MEDICINE_ITEM
    6, // RANCH_STORE_FODDER_ITEM
    6, // RANCH_STORE_CHICKEN_ITEM
    6, // RANCH_STORE_SHEEP_ITEM
    6, // RANCH_STORE_COW_ITEM
    6, // RANCH_STORE_SHOP_CANCEL
    6, // POTION_SHOP_CURE_ALL_ITEM
    6, // POTION_SHOP_VITAMIN_ITEM
    6, // POTION_SHOP_STRONG_VITAMINS_ITEM
    6, // SOUVENIR_SHOP_OCARINA_ITEM
    6, // SOUVENIR_SHOP_VASE_EARLY_ITEM
    6, // SOUVENIR_SHOP_BLUE_VASE_ITEM
    6, // TAVERN_WINE_ITEM
    6, // TAVERN_LIQUOR_ITEM
    6, // TAVERN_BEER_ITEM
    6, // TAVERN_MILK_ITEM
    6, // TAVERN_WATERN_ITEM
    4, // HORSE_RACE_TEA
    4, // HORSE_RACE_MILK
    4, // DOG_RACE_TEA
    4, // DOR_RACE_MILK
    4, // RACE_COOKIES
    4, // FESTIVAL_COTTON_CANDY
    4, // FESTIVAL_FRIED_OCTOPUS
    4, // FESTIVAL_ROASTED_CORN
    4, // FLOWER_FESTIVAL_PINK_CAT_MINT_SEEDS_ITEM
    4, // FLOWER_FESTIVAL_EMPTY_BOTTLE_ITEM
    4  // FIREWORKS_FESTIVAL_EMPTY_BOTTLE_ITEM
};

u16 prices[TOTAL_SHOP_ITEMS] = {
    200,   // FLOWER_SHOP_TURNIP_SEEDS_ITEM
    200,   // FLOWER_SHOP_POTATO_SEEDS_ITEM
    200,   // FLOWER_SHOP_CABBAGE_SEEDS_ITEM
    500,   // FLOWER_SHOP_GRASS_SEEDS_ITEM
    300,   // FLOWER_SHOP_TOMATO_SEEDS_ITEM
    300,   // FLOWER_SHOP_CORN_SEEDS_ITEM
    300,   // FLOWER_SHOP_EGGPLANT_SEEDS_ITEM
    500,   // FLOWER_SHOP_STRAWBERRY_SEEDS_ITEM
    300,   // FLOWER_SHOP_MOON_DROP_SEEDS_ITEM
    0,     // (unused)
    500,   // FLOWER_SHOP_BLUE_MIST_SEEDS_ITEM
    300,   // BAKERY_CAKE_ITEM
    350,   // BAKERY_PIE_ITEM
    300,   // BAKERY_COOKIES
    300,   // BAKERY_CAKE
    350,   // BAKERY_PIE
    200,   // BAKERY_TEA
    0,     // BAKERY_WATER
    0,     // (gap)
    1800,  // RICK_STORE_MILKER_ITEM
    600,   // RICK_STORE_BRUSH_ITEM
    1000,  // RICK_STORE_CLIPPERS_ITEM
    980,   // RICK_STORE_BLUE_FEATHER_ITEM
    3000,  // RICK_STORE_RUG_ITEM
    2000,  // RICK_STORE_CABINET_ITEM
    10000, // RICK_STORE_ICE_CREAM_MAKER_ITEM
    10,    // RANCH_STORE_CHICKEN_FEED_ITEM
    3000,  // RANCH_STORE_MIRACLE_POTION_ITEM
    1000,  // RANCH_STORE_COW_MEDICINE_ITEM
    30,    // RANCH_STORE_FODDER_ITEM
    1500,  // RANCH_STORE_CHICKEN_ITEM
    4000,  // RANCH_STORE_SHEEP_ITEM
    6000,  // RANCH_STORE_COW_ITEM
    0,     // RANCH_STORE_SHOP_CANCEL
    1500,  // POTION_SHOP_CURE_ALL_ITEM
    1000,  // POTION_SHOP_VITAMIN_ITEM
    2000,  // POTION_SHOP_STRONG_VITAMINS_ITEM
    1200,  // SOUVENIR_SHOP_OCARINA_ITEM
    0,     // SOUVENIR_SHOP_VASE_EARLY_ITEM
    2000,  // SOUVENIR_SHOP_BLUE_VASE_ITEM
    300,   // TAVERN_WINE_ITEM
    300,   // TAVERN_LIQUOR_ITEM
    350,   // TAVERN_BEER_ITEM
    150,   // TAVERN_MILK_ITEM
    0,     // TAVERN_WATERN_ITEM
    150,   // HORSE_RACE_TEA
    200,   // HORSE_RACE_MILK
    150,   // DOG_RACE_TEA
    200,   // DOR_RACE_MILK
    300,   // RACE_COOKIES
    120,   // FESTIVAL_COTTON_CANDY
    200,   // FESTIVAL_FRIED_OCTOPUS
    250,   // FESTIVAL_ROASTED_CORN
    300,   // FLOWER_FESTIVAL_PINK_CAT_MINT_SEEDS_ITEM
    200,   // FLOWER_FESTIVAL_EMPTY_BOTTLE_ITEM
    200    // FIREWORKS_FESTIVAL_EMPTY_BOTTLE_ITEM
};

u16 shopItemMaxQuantities[TOTAL_SHOP_ITEMS] = {
    20, // FLOWER_SHOP_TURNIP_SEEDS_ITEM
    20, // FLOWER_SHOP_POTATO_SEEDS_ITEM
    20, // FLOWER_SHOP_CABBAGE_SEEDS_ITEM
    20, // FLOWER_SHOP_GRASS_SEEDS_ITEM
    20, // FLOWER_SHOP_TOMATO_SEEDS_ITEM
    20, // FLOWER_SHOP_CORN_SEEDS_ITEM
    20, // FLOWER_SHOP_EGGPLANT_SEEDS_ITEM
    20, // FLOWER_SHOP_STRAWBERRY_SEEDS_ITEM
    20, // FLOWER_SHOP_MOON_DROP_SEEDS_ITEM
    20, // (unused)
    1,  // FLOWER_SHOP_BLUE_MIST_SEEDS_ITEM
    1,  // BAKERY_CAKE_ITEM
    1,  // BAKERY_PIE_ITEM
    1,  // BAKERY_COOKIES
    1,  // BAKERY_CAKE
    1,  // BAKERY_PIE
    1,  // BAKERY_TEA
    1,  // BAKERY_WATER
    1,  // (gap)
    1,  // RICK_STORE_MILKER_ITEM
    1,  // RICK_STORE_BRUSH_ITEM
    1,  // RICK_STORE_CLIPPERS_ITEM
    1,  // RICK_STORE_BLUE_FEATHER_ITEM
    1,  // RICK_STORE_RUG_ITEM
    1,  // RICK_STORE_CABINET_ITEM
    1,  // RICK_STORE_ICE_CREAM_MAKER_ITEM
    99, // RANCH_STORE_CHICKEN_FEED_ITEM
    1,  // RANCH_STORE_MIRACLE_POTION_ITEM
    1,  // RANCH_STORE_COW_MEDICINE_ITEM
    99, // RANCH_STORE_FODDER_ITEM
    1,  // RANCH_STORE_CHICKEN_ITEM
    1,  // RANCH_STORE_SHEEP_ITEM
    1,  // RANCH_STORE_COW_ITEM
    1,  // RANCH_STORE_SHOP_CANCEL
    1,  // POTION_SHOP_CURE_ALL_ITEM
    1,  // POTION_SHOP_VITAMIN_ITEM
    1,  // POTION_SHOP_STRONG_VITAMINS_ITEM
    1,  // SOUVENIR_SHOP_OCARINA_ITEM
    1,  // SOUVENIR_SHOP_VASE_EARLY_ITEM
    1,  // SOUVENIR_SHOP_BLUE_VASE_ITEM
    1,  // TAVERN_WINE_ITEM
    1,  // TAVERN_LIQUOR_ITEM
    1,  // TAVERN_BEER_ITEM
    1,  // TAVERN_MILK_ITEM
    1,  // TAVERN_WATERN_ITEM
    1,  // HORSE_RACE_TEA
    1,  // HORSE_RACE_MILK
    1,  // DOG_RACE_TEA
    1,  // DOR_RACE_MILK
    1,  // RACE_COOKIES
    1,  // FESTIVAL_COTTON_CANDY
    1,  // FESTIVAL_FRIED_OCTOPUS
    1,  // FESTIVAL_ROASTED_CORN
    20, // FLOWER_FESTIVAL_PINK_CAT_MINT_SEEDS_ITEM
    1,  // FLOWER_FESTIVAL_EMPTY_BOTTLE_ITEM
    1   // FIREWORKS_FESTIVAL_EMPTY_BOTTLE_ITEM
};

u16 shopItemAnimationIndices[TOTAL_SHOP_ITEMS] = {
    58,  // FLOWER_SHOP_TURNIP_SEEDS_ITEM
    59,  // FLOWER_SHOP_POTATO_SEEDS_ITEM
    60,  // FLOWER_SHOP_CABBAGE_SEEDS_ITEM
    65,  // FLOWER_SHOP_GRASS_SEEDS_ITEM
    61,  // FLOWER_SHOP_TOMATO_SEEDS_ITEM
    62,  // FLOWER_SHOP_CORN_SEEDS_ITEM
    63,  // FLOWER_SHOP_EGGPLANT_SEEDS_ITEM
    64,  // FLOWER_SHOP_STRAWBERRY_SEEDS_ITEM
    66,  // FLOWER_SHOP_MOON_DROP_SEEDS_ITEM
    67,  // (unused)
    68,  // FLOWER_SHOP_BLUE_MIST_SEEDS_ITEM
    0,   // BAKERY_CAKE_ITEM
    0,   // BAKERY_PIE_ITEM
    0,   // BAKERY_COOKIES
    0,   // BAKERY_CAKE
    0,   // BAKERY_PIE
    0,   // BAKERY_TEA
    0,   // BAKERY_WATER
    0,   // (gap)
    75,  // RICK_STORE_MILKER_ITEM
    74,  // RICK_STORE_BRUSH_ITEM
    73,  // RICK_STORE_CLIPPERS_ITEM
    10,  // RICK_STORE_BLUE_FEATHER_ITEM
    77,  // RICK_STORE_RUG_ITEM
    76,  // RICK_STORE_CABINET_ITEM
    76,  // RICK_STORE_ICE_CREAM_MAKER_ITEM
    69,  // RANCH_STORE_CHICKEN_FEED_ITEM
    71,  // RANCH_STORE_MIRACLE_POTION_ITEM
    72,  // RANCH_STORE_COW_MEDICINE_ITEM
    70,  // RANCH_STORE_FODDER_ITEM
    0,   // RANCH_STORE_CHICKEN_ITEM
    0,   // RANCH_STORE_SHEEP_ITEM
    0,   // RANCH_STORE_COW_ITEM
    0,   // RANCH_STORE_SHOP_CANCEL
    0,   // POTION_SHOP_CURE_ALL_ITEM
    0,   // POTION_SHOP_VITAMIN_ITEM
    0,   // POTION_SHOP_STRONG_VITAMINS_ITEM
    54,  // SOUVENIR_SHOP_OCARINA_ITEM
    79,  // SOUVENIR_SHOP_VASE_EARLY_ITEM
    78,  // SOUVENIR_SHOP_BLUE_VASE_ITEM
    0,   // TAVERN_WINE_ITEM
    0,   // TAVERN_LIQUOR_ITEM
    0,   // TAVERN_BEER_ITEM
    0,   // TAVERN_MILK_ITEM
    0,   // TAVERN_WATERN_ITEM
    0,   // HORSE_RACE_TEA
    0,   // HORSE_RACE_MILK
    0,   // DOG_RACE_TEA
    0,   // DOR_RACE_MILK
    0,   // RACE_COOKIES
    0,   // FESTIVAL_COTTON_CANDY
    0,   // FESTIVAL_FRIED_OCTOPUS
    0,   // FESTIVAL_ROASTED_CORN
    67,  // FLOWER_FESTIVAL_PINK_CAT_MINT_SEEDS_ITEM
    112, // FLOWER_FESTIVAL_EMPTY_BOTTLE_ITEM
    112  // FIREWORKS_FESTIVAL_EMPTY_BOTTLE_ITEM
};

Vec3f shopItemMapCoordinates[TOTAL_SHOP_ITEMS] = {
    { -16.0f, 32.0f, -144.0f },  // FLOWER_SHOP_TURNIP_SEEDS_ITEM
    { -48.0f, 32.0f, -144.0f },  // FLOWER_SHOP_POTATO_SEEDS_ITEM
    { -80.0f, 32.0f, -144.0f },  // FLOWER_SHOP_CABBAGE_SEEDS_ITEM
    { -112.0f, 32.0f, -16.0f },  // FLOWER_SHOP_GRASS_SEEDS_ITEM
    { -112.0f, 32.0f, -112.0f }, // FLOWER_SHOP_TOMATO_SEEDS_ITEM
    { -112.0f, 32.0f, -80.0f },  // FLOWER_SHOP_CORN_SEEDS_ITEM
    { -112.0f, 32.0f, -48.0f },  // FLOWER_SHOP_EGGPLANT_SEEDS_ITEM
    { -112.0f, 32.0f, 16.0f },   // FLOWER_SHOP_STRAWBERRY_SEEDS_ITEM
    { -112.0f, 32.0f, 16.0f },   // FLOWER_SHOP_MOON_DROP_SEEDS_ITEM
    { 0.0f, 0.0f, 0.0f },        // (unused)
    { -112.0f, 32.0f, 48.0f },   // FLOWER_SHOP_BLUE_MIST_SEEDS_ITEM
    { 0.0f, 0.0f, 0.0f },        // BAKERY_CAKE_ITEM
    { 0.0f, 0.0f, 0.0f },        // BAKERY_PIE_ITEM
    { 0.0f, 0.0f, 0.0f },        // BAKERY_COOKIES
    { 0.0f, 0.0f, 0.0f },        // BAKERY_CAKE
    { 0.0f, 0.0f, 0.0f },        // BAKERY_PIE
    { 0.0f, 0.0f, 0.0f },        // BAKERY_TEA
    { 0.0f, 0.0f, 0.0f },        // BAKERY_WATER
    { 0.0f, 0.0f, 0.0f },        // (gap)
    { -112.0f, 32.0f, 80.0f },   // RICK_STORE_MILKER_ITEM
    { -112.0f, 32.0f, 48.0f },   // RICK_STORE_BRUSH_ITEM
    { -112.0f, 32.0f, 16.0f },   // RICK_STORE_CLIPPERS_ITEM
    { -112.0f, 32.0f, 112.0f },  // RICK_STORE_BLUE_FEATHER_ITEM
    { -112.0f, 16.0f, -24.0f },  // RICK_STORE_RUG_ITEM
    { -48.0f, 32.0f, -52.0f },   // RICK_STORE_CABINET_ITEM
    { -48.0f, 32.0f, -52.0f },   // RICK_STORE_ICE_CREAM_MAKER_ITEM
    { 16.0f, 32.0f, -144.0f },   // RANCH_STORE_CHICKEN_FEED_ITEM
    { -48.0f, 32.0f, -144.0f },  // RANCH_STORE_MIRACLE_POTION_ITEM
    { -80.0f, 32.0f, -144.0f },  // RANCH_STORE_COW_MEDICINE_ITEM
    { -16.0f, 32.0f, -144.0f },  // RANCH_STORE_FODDER_ITEM
    { 0.0f, 0.0f, 0.0f },        // RANCH_STORE_CHICKEN_ITEM
    { 0.0f, 0.0f, 0.0f },        // RANCH_STORE_SHEEP_ITEM
    { 0.0f, 0.0f, 0.0f },        // RANCH_STORE_COW_ITEM
    { 0.0f, 0.0f, 0.0f },        // RANCH_STORE_SHOP_CANCEL
    { 0.0f, 0.0f, 0.0f },        // POTION_SHOP_CURE_ALL_ITEM
    { 0.0f, 0.0f, 0.0f },        // POTION_SHOP_VITAMIN_ITEM
    { 0.0f, 0.0f, 0.0f },        // POTION_SHOP_STRONG_VITAMINS_ITEM
    { -16.0f, 32.0f, -112.0f },  // SOUVENIR_SHOP_OCARINA_ITEM
    { -48.0f, 32.0f, -112.0f },  // SOUVENIR_SHOP_VASE_EARLY_ITEM
    { -48.0f, 32.0f, -112.0f },  // SOUVENIR_SHOP_BLUE_VASE_ITEM
    { 0.0f, 0.0f, 0.0f },        // TAVERN_WINE_ITEM
    { 0.0f, 0.0f, 0.0f },        // TAVERN_LIQUOR_ITEM
    { 0.0f, 0.0f, 0.0f },        // TAVERN_BEER_ITEM
    { 0.0f, 0.0f, 0.0f },        // TAVERN_MILK_ITEM
    { 0.0f, 0.0f, 0.0f },        // TAVERN_WATERN_ITEM
    { 0.0f, 0.0f, 0.0f },        // HORSE_RACE_TEA
    { 0.0f, 0.0f, 0.0f },        // HORSE_RACE_MILK
    { 0.0f, 0.0f, 0.0f },        // DOG_RACE_TEA
    { 0.0f, 0.0f, 0.0f },        // DOR_RACE_MILK
    { 0.0f, 0.0f, 0.0f },        // RACE_COOKIES
    { 0.0f, 0.0f, 0.0f },        // FESTIVAL_COTTON_CANDY
    { 0.0f, 0.0f, 0.0f },        // FESTIVAL_FRIED_OCTOPUS
    { 0.0f, 0.0f, 0.0f },        // FESTIVAL_ROASTED_CORN
    { -160.0f, 96.0f, -192.0f }, // FLOWER_FESTIVAL_PINK_CAT_MINT_SEEDS_ITEM
    { 80.0f, 128.0f, 208.0f },   // FLOWER_FESTIVAL_EMPTY_BOTTLE_ITEM
    { 80.0f, 128.0f, -240.0f }   // FIREWORKS_FESTIVAL_EMPTY_BOTTLE_ITEM
};

u8 *shopItemTextureBuffers[TOTAL_SHOP_ITEMS][2] = {
    { SHOP_DISPLAY_TEX1(SHOP_DISPLAY_REGION_1_BASE, 0), SHOP_DISPLAY_TEX2(SHOP_DISPLAY_REGION_1_BASE, 0) }, // FLOWER_SHOP_TURNIP_SEEDS_ITEM
    { SHOP_DISPLAY_TEX1(SHOP_DISPLAY_REGION_1_BASE, 1), SHOP_DISPLAY_TEX2(SHOP_DISPLAY_REGION_1_BASE, 1) }, // FLOWER_SHOP_POTATO_SEEDS_ITEM
    { SHOP_DISPLAY_TEX1(SHOP_DISPLAY_REGION_2_BASE, 0), SHOP_DISPLAY_TEX2(SHOP_DISPLAY_REGION_2_BASE, 0) }, // FLOWER_SHOP_CABBAGE_SEEDS_ITEM
    { SHOP_DISPLAY_TEX1(SHOP_DISPLAY_REGION_2_BASE, 1), SHOP_DISPLAY_TEX2(SHOP_DISPLAY_REGION_2_BASE, 1) }, // FLOWER_SHOP_GRASS_SEEDS_ITEM
    { SHOP_DISPLAY_TEX1(SHOP_DISPLAY_REGION_2_BASE, 2), SHOP_DISPLAY_TEX2(SHOP_DISPLAY_REGION_2_BASE, 2) }, // FLOWER_SHOP_TOMATO_SEEDS_ITEM
    { SHOP_DISPLAY_TEX1(SHOP_DISPLAY_REGION_2_BASE, 3), SHOP_DISPLAY_TEX2(SHOP_DISPLAY_REGION_2_BASE, 3) }, // FLOWER_SHOP_CORN_SEEDS_ITEM
    { SHOP_DISPLAY_TEX1(SHOP_DISPLAY_REGION_2_BASE, 4), SHOP_DISPLAY_TEX2(SHOP_DISPLAY_REGION_2_BASE, 4) }, // FLOWER_SHOP_EGGPLANT_SEEDS_ITEM
    { SHOP_DISPLAY_TEX1(SHOP_DISPLAY_REGION_2_BASE, 5), SHOP_DISPLAY_TEX2(SHOP_DISPLAY_REGION_2_BASE, 5) }, // FLOWER_SHOP_STRAWBERRY_SEEDS_ITEM
    { SHOP_DISPLAY_TEX1(SHOP_DISPLAY_REGION_2_BASE, 5), SHOP_DISPLAY_TEX2(SHOP_DISPLAY_REGION_2_BASE, 5) }, // FLOWER_SHOP_MOON_DROP_SEEDS_ITEM
    { 0, 0 },                                                                                                // (unused)
    { SHOP_DISPLAY_TEX1(SHOP_DISPLAY_REGION_2_BASE, 6), SHOP_DISPLAY_TEX2(SHOP_DISPLAY_REGION_2_BASE, 6) }, // FLOWER_SHOP_BLUE_MIST_SEEDS_ITEM
    { 0, 0 },                                                                                                // BAKERY_CAKE_ITEM
    { 0, 0 },                                                                                                // BAKERY_PIE_ITEM
    { 0, 0 },                                                                                                // BAKERY_COOKIES
    { 0, 0 },                                                                                                // BAKERY_CAKE
    { 0, 0 },                                                                                                // BAKERY_PIE
    { 0, 0 },                                                                                                // BAKERY_TEA
    { 0, 0 },                                                                                                // BAKERY_WATER
    { 0, 0 },                                                                                                // (gap)
    { SHOP_DISPLAY_TEX1(SHOP_DISPLAY_REGION_1_BASE, 0), SHOP_DISPLAY_TEX2(SHOP_DISPLAY_REGION_1_BASE, 0) }, // RICK_STORE_MILKER_ITEM
    { SHOP_DISPLAY_TEX1(SHOP_DISPLAY_REGION_1_BASE, 1), SHOP_DISPLAY_TEX2(SHOP_DISPLAY_REGION_1_BASE, 1) }, // RICK_STORE_BRUSH_ITEM
    { SHOP_DISPLAY_TEX1(SHOP_DISPLAY_REGION_2_BASE, 0), SHOP_DISPLAY_TEX2(SHOP_DISPLAY_REGION_2_BASE, 0) }, // RICK_STORE_CLIPPERS_ITEM
    { SHOP_DISPLAY_TEX1(SHOP_DISPLAY_REGION_2_BASE, 1), SHOP_DISPLAY_TEX2(SHOP_DISPLAY_REGION_2_BASE, 1) }, // RICK_STORE_BLUE_FEATHER_ITEM
    { SHOP_DISPLAY_TEX1(SHOP_DISPLAY_REGION_2_BASE, 3), SHOP_DISPLAY_TEX1(SHOP_DISPLAY_REGION_2_BASE, 4) }, // RICK_STORE_RUG_ITEM
    { SHOP_DISPLAY_TEX1(SHOP_DISPLAY_REGION_2_BASE, 2), SHOP_DISPLAY_TEX2(SHOP_DISPLAY_REGION_2_BASE, 2) }, // RICK_STORE_CABINET_ITEM
    { SHOP_DISPLAY_TEX1(SHOP_DISPLAY_REGION_2_BASE, 2), SHOP_DISPLAY_TEX2(SHOP_DISPLAY_REGION_2_BASE, 2) }, // RICK_STORE_ICE_CREAM_MAKER_ITEM
    { SHOP_DISPLAY_TEX1(SHOP_DISPLAY_REGION_1_BASE, 0), SHOP_DISPLAY_TEX2(SHOP_DISPLAY_REGION_1_BASE, 0) }, // RANCH_STORE_CHICKEN_FEED_ITEM
    { SHOP_DISPLAY_TEX1(SHOP_DISPLAY_REGION_1_BASE, 1), SHOP_DISPLAY_TEX2(SHOP_DISPLAY_REGION_1_BASE, 1) }, // RANCH_STORE_MIRACLE_POTION_ITEM
    { SHOP_DISPLAY_TEX1(SHOP_DISPLAY_REGION_2_BASE, 0), SHOP_DISPLAY_TEX2(SHOP_DISPLAY_REGION_2_BASE, 0) }, // RANCH_STORE_COW_MEDICINE_ITEM
    { SHOP_DISPLAY_TEX1(SHOP_DISPLAY_REGION_2_BASE, 1), SHOP_DISPLAY_TEX2(SHOP_DISPLAY_REGION_2_BASE, 1) }, // RANCH_STORE_FODDER_ITEM
    { 0, 0 },                                                                                                // RANCH_STORE_CHICKEN_ITEM
    { 0, 0 },                                                                                                // RANCH_STORE_SHEEP_ITEM
    { 0, 0 },                                                                                                // RANCH_STORE_COW_ITEM
    { 0, 0 },                                                                                                // RANCH_STORE_SHOP_CANCEL
    { 0, 0 },                                                                                                // POTION_SHOP_CURE_ALL_ITEM
    { 0, 0 },                                                                                                // POTION_SHOP_VITAMIN_ITEM
    { 0, 0 },                                                                                                // POTION_SHOP_STRONG_VITAMINS_ITEM
    { SHOP_DISPLAY_TEX1(SHOP_DISPLAY_REGION_1_BASE, 0), SHOP_DISPLAY_TEX2(SHOP_DISPLAY_REGION_1_BASE, 0) }, // SOUVENIR_SHOP_OCARINA_ITEM
    { SHOP_DISPLAY_TEX1(SHOP_DISPLAY_REGION_1_BASE, 1), SHOP_DISPLAY_TEX2(SHOP_DISPLAY_REGION_1_BASE, 1) }, // SOUVENIR_SHOP_VASE_EARLY_ITEM
    { SHOP_DISPLAY_TEX1(SHOP_DISPLAY_REGION_1_BASE, 1), SHOP_DISPLAY_TEX2(SHOP_DISPLAY_REGION_1_BASE, 1) }, // SOUVENIR_SHOP_BLUE_VASE_ITEM
    { 0, 0 },                                                                                                // TAVERN_WINE_ITEM
    { 0, 0 },                                                                                                // TAVERN_LIQUOR_ITEM
    { 0, 0 },                                                                                                // TAVERN_BEER_ITEM
    { 0, 0 },                                                                                                // TAVERN_MILK_ITEM
    { 0, 0 },                                                                                                // TAVERN_WATERN_ITEM
    { 0, 0 },                                                                                                // HORSE_RACE_TEA
    { 0, 0 },                                                                                                // HORSE_RACE_MILK
    { 0, 0 },                                                                                                // DOG_RACE_TEA
    { 0, 0 },                                                                                                // DOR_RACE_MILK
    { 0, 0 },                                                                                                // RACE_COOKIES
    { 0, 0 },                                                                                                // FESTIVAL_COTTON_CANDY
    { 0, 0 },                                                                                                // FESTIVAL_FRIED_OCTOPUS
    { 0, 0 },                                                                                                // FESTIVAL_ROASTED_CORN
    { SHOP_DISPLAY_TEX1(SHOP_DISPLAY_REGION_1_BASE, 0), SHOP_DISPLAY_TEX2(SHOP_DISPLAY_REGION_1_BASE, 0) }, // FLOWER_FESTIVAL_PINK_CAT_MINT_SEEDS_ITEM
    { SHOP_DISPLAY_TEX1(SHOP_DISPLAY_REGION_1_BASE, 1), SHOP_DISPLAY_TEX2(SHOP_DISPLAY_REGION_1_BASE, 1) }, // FLOWER_FESTIVAL_EMPTY_BOTTLE_ITEM
    { SHOP_DISPLAY_TEX1(SHOP_DISPLAY_REGION_1_BASE, 1), SHOP_DISPLAY_TEX2(SHOP_DISPLAY_REGION_1_BASE, 1) }  // FIREWORKS_FESTIVAL_EMPTY_BOTTLE_ITEM
};

// sprite index offsets for shop items
u8 shopItemSpriteIndexOffsets[TOTAL_SHOP_ITEMS] = {
    0,   // FLOWER_SHOP_TURNIP_SEEDS_ITEM
    1,   // FLOWER_SHOP_POTATO_SEEDS_ITEM
    2,   // FLOWER_SHOP_CABBAGE_SEEDS_ITEM
    3,   // FLOWER_SHOP_GRASS_SEEDS_ITEM
    4,   // FLOWER_SHOP_TOMATO_SEEDS_ITEM
    5,   // FLOWER_SHOP_CORN_SEEDS_ITEM
    6,   // FLOWER_SHOP_EGGPLANT_SEEDS_ITEM
    7,   // FLOWER_SHOP_STRAWBERRY_SEEDS_ITEM
    7,   // FLOWER_SHOP_MOON_DROP_SEEDS_ITEM
    255, // (unused)
    8,   // FLOWER_SHOP_BLUE_MIST_SEEDS_ITEM
    255, // BAKERY_CAKE_ITEM
    255, // BAKERY_PIE_ITEM
    255, // BAKERY_COOKIES
    255, // BAKERY_CAKE
    255, // BAKERY_PIE
    255, // BAKERY_TEA
    255, // BAKERY_WATER
    255, // (gap)
    0,   // RICK_STORE_MILKER_ITEM
    1,   // RICK_STORE_BRUSH_ITEM
    2,   // RICK_STORE_CLIPPERS_ITEM
    3,   // RICK_STORE_BLUE_FEATHER_ITEM
    5,   // RICK_STORE_RUG_ITEM
    4,   // RICK_STORE_CABINET_ITEM
    4,   // RICK_STORE_ICE_CREAM_MAKER_ITEM
    0,   // RANCH_STORE_CHICKEN_FEED_ITEM
    1,   // RANCH_STORE_MIRACLE_POTION_ITEM
    2,   // RANCH_STORE_COW_MEDICINE_ITEM
    3,   // RANCH_STORE_FODDER_ITEM
    255, // RANCH_STORE_CHICKEN_ITEM
    255, // RANCH_STORE_SHEEP_ITEM
    255, // RANCH_STORE_COW_ITEM
    255, // RANCH_STORE_SHOP_CANCEL
    255, // POTION_SHOP_CURE_ALL_ITEM
    255, // POTION_SHOP_VITAMIN_ITEM
    255, // POTION_SHOP_STRONG_VITAMINS_ITEM
    0,   // SOUVENIR_SHOP_OCARINA_ITEM
    1,   // SOUVENIR_SHOP_VASE_EARLY_ITEM
    1,   // SOUVENIR_SHOP_BLUE_VASE_ITEM
    255, // TAVERN_WINE_ITEM
    255, // TAVERN_LIQUOR_ITEM
    255, // TAVERN_BEER_ITEM
    255, // TAVERN_MILK_ITEM
    255, // TAVERN_WATERN_ITEM
    255, // HORSE_RACE_TEA
    255, // HORSE_RACE_MILK
    255, // DOG_RACE_TEA
    255, // DOR_RACE_MILK
    255, // RACE_COOKIES
    255, // FESTIVAL_COTTON_CANDY
    255, // FESTIVAL_FRIED_OCTOPUS
    255, // FESTIVAL_ROASTED_CORN
    1,   // FLOWER_FESTIVAL_PINK_CAT_MINT_SEEDS_ITEM
    2,   // FLOWER_FESTIVAL_EMPTY_BOTTLE_ITEM
    2    // FIREWORKS_FESTIVAL_EMPTY_BOTTLE_ITEM
};

u8 shopItemSkipsHeldDisplay[TOTAL_SHOP_ITEMS] = {
    FALSE, // FLOWER_SHOP_TURNIP_SEEDS_ITEM
    FALSE, // FLOWER_SHOP_POTATO_SEEDS_ITEM
    FALSE, // FLOWER_SHOP_CABBAGE_SEEDS_ITEM
    FALSE, // FLOWER_SHOP_GRASS_SEEDS_ITEM
    FALSE, // FLOWER_SHOP_TOMATO_SEEDS_ITEM
    FALSE, // FLOWER_SHOP_CORN_SEEDS_ITEM
    FALSE, // FLOWER_SHOP_EGGPLANT_SEEDS_ITEM
    FALSE, // FLOWER_SHOP_STRAWBERRY_SEEDS_ITEM
    FALSE, // FLOWER_SHOP_MOON_DROP_SEEDS_ITEM
    FALSE, // (unused)
    TRUE,  // FLOWER_SHOP_BLUE_MIST_SEEDS_ITEM
    FALSE, // BAKERY_CAKE_ITEM
    FALSE, // BAKERY_PIE_ITEM
    FALSE, // BAKERY_COOKIES
    FALSE, // BAKERY_CAKE
    FALSE, // BAKERY_PIE
    FALSE, // BAKERY_TEA
    FALSE, // BAKERY_WATER
    FALSE, // (gap)
    TRUE,  // RICK_STORE_MILKER_ITEM
    TRUE,  // RICK_STORE_BRUSH_ITEM
    TRUE,  // RICK_STORE_CLIPPERS_ITEM
    TRUE,  // RICK_STORE_BLUE_FEATHER_ITEM
    FALSE, // RICK_STORE_RUG_ITEM
    TRUE,  // RICK_STORE_CABINET_ITEM
    TRUE,  // RICK_STORE_ICE_CREAM_MAKER_ITEM
    FALSE, // RANCH_STORE_CHICKEN_FEED_ITEM
    TRUE,  // RANCH_STORE_MIRACLE_POTION_ITEM
    TRUE,  // RANCH_STORE_COW_MEDICINE_ITEM
    FALSE, // RANCH_STORE_FODDER_ITEM
    FALSE, // RANCH_STORE_CHICKEN_ITEM
    FALSE, // RANCH_STORE_SHEEP_ITEM
    FALSE, // RANCH_STORE_COW_ITEM
    FALSE, // RANCH_STORE_SHOP_CANCEL
    FALSE, // POTION_SHOP_CURE_ALL_ITEM
    FALSE, // POTION_SHOP_VITAMIN_ITEM
    FALSE, // POTION_SHOP_STRONG_VITAMINS_ITEM
    TRUE,  // SOUVENIR_SHOP_OCARINA_ITEM
    FALSE, // SOUVENIR_SHOP_VASE_EARLY_ITEM
    TRUE,  // SOUVENIR_SHOP_BLUE_VASE_ITEM
    FALSE, // TAVERN_WINE_ITEM
    FALSE, // TAVERN_LIQUOR_ITEM
    FALSE, // TAVERN_BEER_ITEM
    FALSE, // TAVERN_MILK_ITEM
    FALSE, // TAVERN_WATERN_ITEM
    FALSE, // HORSE_RACE_TEA
    FALSE, // HORSE_RACE_MILK
    FALSE, // DOG_RACE_TEA
    FALSE, // DOR_RACE_MILK
    FALSE, // RACE_COOKIES
    FALSE, // FESTIVAL_COTTON_CANDY
    FALSE, // FESTIVAL_FRIED_OCTOPUS
    FALSE, // FESTIVAL_ROASTED_CORN
    FALSE, // FLOWER_FESTIVAL_PINK_CAT_MINT_SEEDS_ITEM
    TRUE,  // FLOWER_FESTIVAL_EMPTY_BOTTLE_ITEM
    TRUE   // FIREWORKS_FESTIVAL_EMPTY_BOTTLE_ITEM
};

u8 shopItemPickUpEnabled[TOTAL_SHOP_ITEMS] = {
    TRUE,  // FLOWER_SHOP_TURNIP_SEEDS_ITEM
    TRUE,  // FLOWER_SHOP_POTATO_SEEDS_ITEM
    TRUE,  // FLOWER_SHOP_CABBAGE_SEEDS_ITEM
    TRUE,  // FLOWER_SHOP_GRASS_SEEDS_ITEM
    TRUE,  // FLOWER_SHOP_TOMATO_SEEDS_ITEM
    TRUE,  // FLOWER_SHOP_CORN_SEEDS_ITEM
    TRUE,  // FLOWER_SHOP_EGGPLANT_SEEDS_ITEM
    TRUE,  // FLOWER_SHOP_STRAWBERRY_SEEDS_ITEM
    TRUE,  // FLOWER_SHOP_MOON_DROP_SEEDS_ITEM
    TRUE,  // (unused)
    TRUE,  // FLOWER_SHOP_BLUE_MIST_SEEDS_ITEM
    FALSE, // BAKERY_CAKE_ITEM
    FALSE, // BAKERY_PIE_ITEM
    FALSE, // BAKERY_COOKIES
    FALSE, // BAKERY_CAKE
    FALSE, // BAKERY_PIE
    FALSE, // BAKERY_TEA
    FALSE, // BAKERY_WATER
    FALSE, // (gap)
    TRUE,  // RICK_STORE_MILKER_ITEM
    TRUE,  // RICK_STORE_BRUSH_ITEM
    TRUE,  // RICK_STORE_CLIPPERS_ITEM
    TRUE,  // RICK_STORE_BLUE_FEATHER_ITEM
    FALSE, // RICK_STORE_RUG_ITEM
    FALSE, // RICK_STORE_CABINET_ITEM
    FALSE, // RICK_STORE_ICE_CREAM_MAKER_ITEM
    TRUE,  // RANCH_STORE_CHICKEN_FEED_ITEM
    TRUE,  // RANCH_STORE_MIRACLE_POTION_ITEM
    TRUE,  // RANCH_STORE_COW_MEDICINE_ITEM
    TRUE,  // RANCH_STORE_FODDER_ITEM
    FALSE, // RANCH_STORE_CHICKEN_ITEM
    FALSE, // RANCH_STORE_SHEEP_ITEM
    FALSE, // RANCH_STORE_COW_ITEM
    FALSE, // RANCH_STORE_SHOP_CANCEL
    FALSE, // POTION_SHOP_CURE_ALL_ITEM
    FALSE, // POTION_SHOP_VITAMIN_ITEM
    FALSE, // POTION_SHOP_STRONG_VITAMINS_ITEM
    TRUE,  // SOUVENIR_SHOP_OCARINA_ITEM
    TRUE,  // SOUVENIR_SHOP_VASE_EARLY_ITEM
    TRUE,  // SOUVENIR_SHOP_BLUE_VASE_ITEM
    FALSE, // TAVERN_WINE_ITEM
    FALSE, // TAVERN_LIQUOR_ITEM
    FALSE, // TAVERN_BEER_ITEM
    FALSE, // TAVERN_MILK_ITEM
    FALSE, // TAVERN_WATERN_ITEM
    FALSE, // HORSE_RACE_TEA
    FALSE, // HORSE_RACE_MILK
    FALSE, // DOG_RACE_TEA
    FALSE, // DOR_RACE_MILK
    FALSE, // RACE_COOKIES
    FALSE, // FESTIVAL_COTTON_CANDY
    FALSE, // FESTIVAL_FRIED_OCTOPUS
    FALSE, // FESTIVAL_ROASTED_CORN
    TRUE,  // FLOWER_FESTIVAL_PINK_CAT_MINT_SEEDS_ITEM
    TRUE,  // FLOWER_FESTIVAL_EMPTY_BOTTLE_ITEM
    TRUE   // FIREWORKS_FESTIVAL_EMPTY_BOTTLE_ITEM
};

u8 shopItemToItemInfoIndices[TOTAL_SHOP_ITEMS] = {
    9, // FLOWER_SHOP_TURNIP_SEEDS_ITEM
    9, // FLOWER_SHOP_POTATO_SEEDS_ITEM
    9, // FLOWER_SHOP_CABBAGE_SEEDS_ITEM
    9, // FLOWER_SHOP_GRASS_SEEDS_ITEM
    9, // FLOWER_SHOP_TOMATO_SEEDS_ITEM
    9, // FLOWER_SHOP_CORN_SEEDS_ITEM
    9, // FLOWER_SHOP_EGGPLANT_SEEDS_ITEM
    9, // FLOWER_SHOP_STRAWBERRY_SEEDS_ITEM
    9, // FLOWER_SHOP_MOON_DROP_SEEDS_ITEM
    9, // (unused)
    9, // FLOWER_SHOP_BLUE_MIST_SEEDS_ITEM
    9, // BAKERY_CAKE_ITEM
    9, // BAKERY_PIE_ITEM
    9, // BAKERY_COOKIES
    9, // BAKERY_CAKE
    9, // BAKERY_PIE
    9, // BAKERY_TEA
    9, // BAKERY_WATER
    9, // (gap)
    9, // RICK_STORE_MILKER_ITEM
    9, // RICK_STORE_BRUSH_ITEM
    9, // RICK_STORE_CLIPPERS_ITEM
    9, // RICK_STORE_BLUE_FEATHER_ITEM
    9, // RICK_STORE_RUG_ITEM
    9, // RICK_STORE_CABINET_ITEM
    9, // RICK_STORE_ICE_CREAM_MAKER_ITEM
    9, // RANCH_STORE_CHICKEN_FEED_ITEM
    9, // RANCH_STORE_MIRACLE_POTION_ITEM
    9, // RANCH_STORE_COW_MEDICINE_ITEM
    9, // RANCH_STORE_FODDER_ITEM
    9, // RANCH_STORE_CHICKEN_ITEM
    9, // RANCH_STORE_SHEEP_ITEM
    9, // RANCH_STORE_COW_ITEM
    9, // RANCH_STORE_SHOP_CANCEL
    9, // POTION_SHOP_CURE_ALL_ITEM
    9, // POTION_SHOP_VITAMIN_ITEM
    9, // POTION_SHOP_STRONG_VITAMINS_ITEM
    9, // SOUVENIR_SHOP_OCARINA_ITEM
    9, // SOUVENIR_SHOP_VASE_EARLY_ITEM
    9, // SOUVENIR_SHOP_BLUE_VASE_ITEM
    9, // TAVERN_WINE_ITEM
    9, // TAVERN_LIQUOR_ITEM
    9, // TAVERN_BEER_ITEM
    9, // TAVERN_MILK_ITEM
    9, // TAVERN_WATERN_ITEM
    9, // HORSE_RACE_TEA
    9, // HORSE_RACE_MILK
    9, // DOG_RACE_TEA
    9, // DOR_RACE_MILK
    9, // RACE_COOKIES
    9, // FESTIVAL_COTTON_CANDY
    9, // FESTIVAL_FRIED_OCTOPUS
    9, // FESTIVAL_ROASTED_CORN
    0, // FLOWER_FESTIVAL_PINK_CAT_MINT_SEEDS_ITEM
    0, // FLOWER_FESTIVAL_EMPTY_BOTTLE_ITEM
    0  // FIREWORKS_FESTIVAL_EMPTY_BOTTLE_ITEM
};

// TRUE = description box transitions to a Yes/No purchase prompt (uses MESSAGE_BOX_MODE_NO_AUTO_RESET);
// FALSE = description ends and goes straight to handlePurchase (only the early Saibara vase).
u8 shopItemHasPurchaseConfirmation[TOTAL_SHOP_ITEMS] = {
    TRUE,  // FLOWER_SHOP_TURNIP_SEEDS_ITEM
    TRUE,  // FLOWER_SHOP_POTATO_SEEDS_ITEM
    TRUE,  // FLOWER_SHOP_CABBAGE_SEEDS_ITEM
    TRUE,  // FLOWER_SHOP_GRASS_SEEDS_ITEM
    TRUE,  // FLOWER_SHOP_TOMATO_SEEDS_ITEM
    TRUE,  // FLOWER_SHOP_CORN_SEEDS_ITEM
    TRUE,  // FLOWER_SHOP_EGGPLANT_SEEDS_ITEM
    TRUE,  // FLOWER_SHOP_STRAWBERRY_SEEDS_ITEM
    TRUE,  // FLOWER_SHOP_MOON_DROP_SEEDS_ITEM
    TRUE,  // (unused)
    TRUE,  // FLOWER_SHOP_BLUE_MIST_SEEDS_ITEM
    TRUE,  // BAKERY_CAKE_ITEM
    TRUE,  // BAKERY_PIE_ITEM
    TRUE,  // BAKERY_COOKIES
    TRUE,  // BAKERY_CAKE
    TRUE,  // BAKERY_PIE
    TRUE,  // BAKERY_TEA
    TRUE,  // BAKERY_WATER
    TRUE,  // (gap)
    TRUE,  // RICK_STORE_MILKER_ITEM
    TRUE,  // RICK_STORE_BRUSH_ITEM
    TRUE,  // RICK_STORE_CLIPPERS_ITEM
    TRUE,  // RICK_STORE_BLUE_FEATHER_ITEM
    TRUE,  // RICK_STORE_RUG_ITEM
    TRUE,  // RICK_STORE_CABINET_ITEM
    TRUE,  // RICK_STORE_ICE_CREAM_MAKER_ITEM
    TRUE,  // RANCH_STORE_CHICKEN_FEED_ITEM
    TRUE,  // RANCH_STORE_MIRACLE_POTION_ITEM
    TRUE,  // RANCH_STORE_COW_MEDICINE_ITEM
    TRUE,  // RANCH_STORE_FODDER_ITEM
    TRUE,  // RANCH_STORE_CHICKEN_ITEM
    TRUE,  // RANCH_STORE_SHEEP_ITEM
    TRUE,  // RANCH_STORE_COW_ITEM
    TRUE,  // RANCH_STORE_SHOP_CANCEL
    TRUE,  // POTION_SHOP_CURE_ALL_ITEM
    TRUE,  // POTION_SHOP_VITAMIN_ITEM
    TRUE,  // POTION_SHOP_STRONG_VITAMINS_ITEM
    TRUE,  // SOUVENIR_SHOP_OCARINA_ITEM
    FALSE, // SOUVENIR_SHOP_VASE_EARLY_ITEM
    TRUE,  // SOUVENIR_SHOP_BLUE_VASE_ITEM
    TRUE,  // TAVERN_WINE_ITEM
    TRUE,  // TAVERN_LIQUOR_ITEM
    TRUE,  // TAVERN_BEER_ITEM
    TRUE,  // TAVERN_MILK_ITEM
    TRUE,  // TAVERN_WATERN_ITEM
    TRUE,  // HORSE_RACE_TEA
    TRUE,  // HORSE_RACE_MILK
    TRUE,  // DOG_RACE_TEA
    TRUE,  // DOR_RACE_MILK
    TRUE,  // RACE_COOKIES
    TRUE,  // FESTIVAL_COTTON_CANDY
    TRUE,  // FESTIVAL_FRIED_OCTOPUS
    TRUE,  // FESTIVAL_ROASTED_CORN
    TRUE,  // FLOWER_FESTIVAL_PINK_CAT_MINT_SEEDS_ITEM
    TRUE,  // FLOWER_FESTIVAL_EMPTY_BOTTLE_ITEM
    TRUE   // FIREWORKS_FESTIVAL_EMPTY_BOTTLE_ITEM
};

u8 shopItemStartingMode[TOTAL_SHOP_ITEMS] = {
    SHOP_MODE_OPEN_DESCRIPTION, // FLOWER_SHOP_TURNIP_SEEDS_ITEM
    SHOP_MODE_OPEN_DESCRIPTION, // FLOWER_SHOP_POTATO_SEEDS_ITEM
    SHOP_MODE_OPEN_DESCRIPTION, // FLOWER_SHOP_CABBAGE_SEEDS_ITEM
    SHOP_MODE_OPEN_DESCRIPTION, // FLOWER_SHOP_GRASS_SEEDS_ITEM
    SHOP_MODE_OPEN_DESCRIPTION, // FLOWER_SHOP_TOMATO_SEEDS_ITEM
    SHOP_MODE_OPEN_DESCRIPTION, // FLOWER_SHOP_CORN_SEEDS_ITEM
    SHOP_MODE_OPEN_DESCRIPTION, // FLOWER_SHOP_EGGPLANT_SEEDS_ITEM
    SHOP_MODE_OPEN_DESCRIPTION, // FLOWER_SHOP_STRAWBERRY_SEEDS_ITEM
    SHOP_MODE_OPEN_DESCRIPTION, // FLOWER_SHOP_MOON_DROP_SEEDS_ITEM
    SHOP_MODE_OPEN_DESCRIPTION, // (unused)
    SHOP_MODE_OPEN_DESCRIPTION, // FLOWER_SHOP_BLUE_MIST_SEEDS_ITEM
    SHOP_MODE_COMMIT_PURCHASE,  // BAKERY_CAKE_ITEM
    SHOP_MODE_COMMIT_PURCHASE,  // BAKERY_PIE_ITEM
    SHOP_MODE_COMMIT_PURCHASE,  // BAKERY_COOKIES
    SHOP_MODE_COMMIT_PURCHASE,  // BAKERY_CAKE
    SHOP_MODE_COMMIT_PURCHASE,  // BAKERY_PIE
    SHOP_MODE_COMMIT_PURCHASE,  // BAKERY_TEA
    SHOP_MODE_COMMIT_PURCHASE,  // BAKERY_WATER
    SHOP_MODE_DECLINE_PURCHASE, // (gap)
    SHOP_MODE_OPEN_DESCRIPTION, // RICK_STORE_MILKER_ITEM
    SHOP_MODE_OPEN_DESCRIPTION, // RICK_STORE_BRUSH_ITEM
    SHOP_MODE_OPEN_DESCRIPTION, // RICK_STORE_CLIPPERS_ITEM
    SHOP_MODE_OPEN_DESCRIPTION, // RICK_STORE_BLUE_FEATHER_ITEM
    SHOP_MODE_OPEN_DESCRIPTION, // RICK_STORE_RUG_ITEM
    SHOP_MODE_OPEN_DESCRIPTION, // RICK_STORE_CABINET_ITEM
    SHOP_MODE_OPEN_DESCRIPTION, // RICK_STORE_ICE_CREAM_MAKER_ITEM
    SHOP_MODE_OPEN_DESCRIPTION, // RANCH_STORE_CHICKEN_FEED_ITEM
    SHOP_MODE_OPEN_DESCRIPTION, // RANCH_STORE_MIRACLE_POTION_ITEM
    SHOP_MODE_OPEN_DESCRIPTION, // RANCH_STORE_COW_MEDICINE_ITEM
    SHOP_MODE_OPEN_DESCRIPTION, // RANCH_STORE_FODDER_ITEM
    SHOP_MODE_COMMIT_PURCHASE,  // RANCH_STORE_CHICKEN_ITEM
    SHOP_MODE_COMMIT_PURCHASE,  // RANCH_STORE_SHEEP_ITEM
    SHOP_MODE_COMMIT_PURCHASE,  // RANCH_STORE_COW_ITEM
    SHOP_MODE_DECLINE_PURCHASE, // RANCH_STORE_SHOP_CANCEL
    SHOP_MODE_OPEN_DESCRIPTION, // POTION_SHOP_CURE_ALL_ITEM
    SHOP_MODE_OPEN_DESCRIPTION, // POTION_SHOP_VITAMIN_ITEM
    SHOP_MODE_OPEN_DESCRIPTION, // POTION_SHOP_STRONG_VITAMINS_ITEM
    SHOP_MODE_OPEN_DESCRIPTION, // SOUVENIR_SHOP_OCARINA_ITEM
    SHOP_MODE_OPEN_DESCRIPTION, // SOUVENIR_SHOP_VASE_EARLY_ITEM
    SHOP_MODE_OPEN_DESCRIPTION, // SOUVENIR_SHOP_BLUE_VASE_ITEM
    SHOP_MODE_COMMIT_PURCHASE,  // TAVERN_WINE_ITEM
    SHOP_MODE_COMMIT_PURCHASE,  // TAVERN_LIQUOR_ITEM
    SHOP_MODE_COMMIT_PURCHASE,  // TAVERN_BEER_ITEM
    SHOP_MODE_COMMIT_PURCHASE,  // TAVERN_MILK_ITEM
    SHOP_MODE_COMMIT_PURCHASE,  // TAVERN_WATERN_ITEM
    SHOP_MODE_COMMIT_PURCHASE,  // HORSE_RACE_TEA
    SHOP_MODE_COMMIT_PURCHASE,  // HORSE_RACE_MILK
    SHOP_MODE_COMMIT_PURCHASE,  // DOG_RACE_TEA
    SHOP_MODE_COMMIT_PURCHASE,  // DOR_RACE_MILK
    SHOP_MODE_COMMIT_PURCHASE,  // RACE_COOKIES
    SHOP_MODE_COMMIT_PURCHASE,  // FESTIVAL_COTTON_CANDY
    SHOP_MODE_COMMIT_PURCHASE,  // FESTIVAL_FRIED_OCTOPUS
    SHOP_MODE_COMMIT_PURCHASE,  // FESTIVAL_ROASTED_CORN
    SHOP_MODE_OPEN_DESCRIPTION, // FLOWER_FESTIVAL_PINK_CAT_MINT_SEEDS_ITEM
    SHOP_MODE_OPEN_DESCRIPTION, // FLOWER_FESTIVAL_EMPTY_BOTTLE_ITEM
    SHOP_MODE_OPEN_DESCRIPTION  // FIREWORKS_FESTIVAL_EMPTY_BOTTLE_ITEM
};

u8 playerShopActionPhase[TOTAL_SHOP_ITEMS] = {
    2, // FLOWER_SHOP_TURNIP_SEEDS_ITEM
    2, // FLOWER_SHOP_POTATO_SEEDS_ITEM
    2, // FLOWER_SHOP_CABBAGE_SEEDS_ITEM
    2, // FLOWER_SHOP_GRASS_SEEDS_ITEM
    2, // FLOWER_SHOP_TOMATO_SEEDS_ITEM
    2, // FLOWER_SHOP_CORN_SEEDS_ITEM
    2, // FLOWER_SHOP_EGGPLANT_SEEDS_ITEM
    2, // FLOWER_SHOP_STRAWBERRY_SEEDS_ITEM
    2, // FLOWER_SHOP_MOON_DROP_SEEDS_ITEM
    2, // (unused)
    2, // FLOWER_SHOP_BLUE_MIST_SEEDS_ITEM
    2, // BAKERY_CAKE_ITEM
    2, // BAKERY_PIE_ITEM
    2, // BAKERY_COOKIES
    0, // BAKERY_CAKE
    0, // BAKERY_PIE
    0, // BAKERY_TEA
    0, // BAKERY_WATER
    2, // (gap)
    2, // RICK_STORE_MILKER_ITEM
    2, // RICK_STORE_BRUSH_ITEM
    2, // RICK_STORE_CLIPPERS_ITEM
    2, // RICK_STORE_BLUE_FEATHER_ITEM
    2, // RICK_STORE_RUG_ITEM
    2, // RICK_STORE_CABINET_ITEM
    2, // RICK_STORE_ICE_CREAM_MAKER_ITEM
    2, // RANCH_STORE_CHICKEN_FEED_ITEM
    2, // RANCH_STORE_MIRACLE_POTION_ITEM
    2, // RANCH_STORE_COW_MEDICINE_ITEM
    2, // RANCH_STORE_FODDER_ITEM
    0, // RANCH_STORE_CHICKEN_ITEM
    0, // RANCH_STORE_SHEEP_ITEM
    0, // RANCH_STORE_COW_ITEM
    2, // RANCH_STORE_SHOP_CANCEL
    2, // POTION_SHOP_CURE_ALL_ITEM
    2, // POTION_SHOP_VITAMIN_ITEM
    2, // POTION_SHOP_STRONG_VITAMINS_ITEM
    2, // SOUVENIR_SHOP_OCARINA_ITEM
    2, // SOUVENIR_SHOP_VASE_EARLY_ITEM
    2, // SOUVENIR_SHOP_BLUE_VASE_ITEM
    0, // TAVERN_WINE_ITEM
    0, // TAVERN_LIQUOR_ITEM
    0, // TAVERN_BEER_ITEM
    0, // TAVERN_MILK_ITEM
    0, // TAVERN_WATERN_ITEM
    0, // HORSE_RACE_TEA
    0, // HORSE_RACE_MILK
    0, // DOG_RACE_TEA
    0, // DOR_RACE_MILK
    0, // RACE_COOKIES
    0, // FESTIVAL_COTTON_CANDY
    0, // FESTIVAL_FRIED_OCTOPUS
    0, // FESTIVAL_ROASTED_CORN
    2, // FLOWER_FESTIVAL_PINK_CAT_MINT_SEEDS_ITEM
    2, // FLOWER_FESTIVAL_EMPTY_BOTTLE_ITEM
    2  // FIREWORKS_FESTIVAL_EMPTY_BOTTLE_ITEM
};

u8 playerShopEndActionPhase[TOTAL_SHOP_ITEMS] = {
    2,   // FLOWER_SHOP_TURNIP_SEEDS_ITEM
    2,   // FLOWER_SHOP_POTATO_SEEDS_ITEM
    2,   // FLOWER_SHOP_CABBAGE_SEEDS_ITEM
    2,   // FLOWER_SHOP_GRASS_SEEDS_ITEM
    2,   // FLOWER_SHOP_TOMATO_SEEDS_ITEM
    2,   // FLOWER_SHOP_CORN_SEEDS_ITEM
    2,   // FLOWER_SHOP_EGGPLANT_SEEDS_ITEM
    2,   // FLOWER_SHOP_STRAWBERRY_SEEDS_ITEM
    2,   // FLOWER_SHOP_MOON_DROP_SEEDS_ITEM
    2,   // (unused)
    2,   // FLOWER_SHOP_BLUE_MIST_SEEDS_ITEM
    2,   // BAKERY_CAKE_ITEM
    2,   // BAKERY_PIE_ITEM
    2,   // BAKERY_COOKIES
    0xFF, // BAKERY_CAKE
    0xFF, // BAKERY_PIE
    0xFF, // BAKERY_TEA
    0xFF, // BAKERY_WATER
    2,   // (gap)
    2,   // RICK_STORE_MILKER_ITEM
    2,   // RICK_STORE_BRUSH_ITEM
    2,   // RICK_STORE_CLIPPERS_ITEM
    2,   // RICK_STORE_BLUE_FEATHER_ITEM
    2,   // RICK_STORE_RUG_ITEM
    2,   // RICK_STORE_CABINET_ITEM
    2,   // RICK_STORE_ICE_CREAM_MAKER_ITEM
    2,   // RANCH_STORE_CHICKEN_FEED_ITEM
    2,   // RANCH_STORE_MIRACLE_POTION_ITEM
    2,   // RANCH_STORE_COW_MEDICINE_ITEM
    2,   // RANCH_STORE_FODDER_ITEM
    0,   // RANCH_STORE_CHICKEN_ITEM
    0,   // RANCH_STORE_SHEEP_ITEM
    0,   // RANCH_STORE_COW_ITEM
    2,   // RANCH_STORE_SHOP_CANCEL
    2,   // POTION_SHOP_CURE_ALL_ITEM
    2,   // POTION_SHOP_VITAMIN_ITEM
    2,   // POTION_SHOP_STRONG_VITAMINS_ITEM
    2,   // SOUVENIR_SHOP_OCARINA_ITEM
    2,   // SOUVENIR_SHOP_VASE_EARLY_ITEM
    2,   // SOUVENIR_SHOP_BLUE_VASE_ITEM
    0xFF, // TAVERN_WINE_ITEM
    0xFF, // TAVERN_LIQUOR_ITEM
    0xFF, // TAVERN_BEER_ITEM
    0xFF, // TAVERN_MILK_ITEM
    0xFF, // TAVERN_WATERN_ITEM
    0xFF, // HORSE_RACE_TEA
    0xFF, // HORSE_RACE_MILK
    0xFF, // DOG_RACE_TEA
    0xFF, // DOR_RACE_MILK
    0xFF, // RACE_COOKIES
    0xFF, // FESTIVAL_COTTON_CANDY
    0xFF, // FESTIVAL_FRIED_OCTOPUS
    0xFF, // FESTIVAL_ROASTED_CORN
    2,   // FLOWER_FESTIVAL_PINK_CAT_MINT_SEEDS_ITEM
    2,   // FLOWER_FESTIVAL_EMPTY_BOTTLE_ITEM
    2    // FIREWORKS_FESTIVAL_EMPTY_BOTTLE_ITEM
};

// player animations table when interacting with shop items
AnimationIndices playerShopAnimationIndices[TOTAL_SHOP_ITEMS] = {
    { 11, 13 }, // FLOWER_SHOP_TURNIP_SEEDS_ITEM
    { 11, 13 }, // FLOWER_SHOP_POTATO_SEEDS_ITEM
    { 11, 13 }, // FLOWER_SHOP_CABBAGE_SEEDS_ITEM
    { 11, 13 }, // FLOWER_SHOP_GRASS_SEEDS_ITEM
    { 11, 13 }, // FLOWER_SHOP_TOMATO_SEEDS_ITEM
    { 11, 13 }, // FLOWER_SHOP_CORN_SEEDS_ITEM
    { 11, 13 }, // FLOWER_SHOP_EGGPLANT_SEEDS_ITEM
    { 11, 13 }, // FLOWER_SHOP_STRAWBERRY_SEEDS_ITEM
    { 11, 13 }, // FLOWER_SHOP_MOON_DROP_SEEDS_ITEM
    { 11, 13 }, // (unused)
    { 11, 13 }, // FLOWER_SHOP_BLUE_MIST_SEEDS_ITEM
    { 0, 0 },   // BAKERY_CAKE_ITEM
    { 0, 0 },   // BAKERY_PIE_ITEM
    { 0, 0 },   // BAKERY_COOKIES
    { 6, 8 },   // BAKERY_CAKE
    { 6, 8 },   // BAKERY_PIE
    { 20, 21 }, // BAKERY_TEA
    { 20, 21 }, // BAKERY_WATER
    { 0, 0 },   // (gap)
    { 11, 13 }, // RICK_STORE_MILKER_ITEM
    { 11, 13 }, // RICK_STORE_BRUSH_ITEM
    { 11, 13 }, // RICK_STORE_CLIPPERS_ITEM
    { 11, 13 }, // RICK_STORE_BLUE_FEATHER_ITEM
    { 11, 13 }, // RICK_STORE_RUG_ITEM
    { 11, 13 }, // RICK_STORE_CABINET_ITEM
    { 11, 13 }, // RICK_STORE_ICE_CREAM_MAKER_ITEM
    { 11, 13 }, // RANCH_STORE_CHICKEN_FEED_ITEM
    { 11, 13 }, // RANCH_STORE_MIRACLE_POTION_ITEM
    { 11, 13 }, // RANCH_STORE_COW_MEDICINE_ITEM
    { 11, 13 }, // RANCH_STORE_FODDER_ITEM
    { 0, 0 },   // RANCH_STORE_CHICKEN_ITEM
    { 0, 0 },   // RANCH_STORE_SHEEP_ITEM
    { 0, 0 },   // RANCH_STORE_COW_ITEM
    { 0, 0 },   // RANCH_STORE_SHOP_CANCEL
    { 0, 0 },   // POTION_SHOP_CURE_ALL_ITEM
    { 0, 0 },   // POTION_SHOP_VITAMIN_ITEM
    { 0, 0 },   // POTION_SHOP_STRONG_VITAMINS_ITEM
    { 11, 13 }, // SOUVENIR_SHOP_OCARINA_ITEM
    { 11, 13 }, // SOUVENIR_SHOP_VASE_EARLY_ITEM
    { 11, 13 }, // SOUVENIR_SHOP_BLUE_VASE_ITEM
    { 20, 21 }, // TAVERN_WINE_ITEM
    { 20, 21 }, // TAVERN_LIQUOR_ITEM
    { 20, 21 }, // TAVERN_BEER_ITEM
    { 20, 21 }, // TAVERN_MILK_ITEM
    { 20, 21 }, // TAVERN_WATERN_ITEM
    { 20, 21 }, // HORSE_RACE_TEA
    { 20, 21 }, // HORSE_RACE_MILK
    { 20, 21 }, // DOG_RACE_TEA
    { 20, 21 }, // DOR_RACE_MILK
    { 6, 8 },   // RACE_COOKIES
    { 6, 8 },   // FESTIVAL_COTTON_CANDY
    { 6, 8 },   // FESTIVAL_FRIED_OCTOPUS
    { 6, 8 },   // FESTIVAL_ROASTED_CORN
    { 11, 13 }, // FLOWER_FESTIVAL_PINK_CAT_MINT_SEEDS_ITEM
    { 11, 13 }, // FLOWER_FESTIVAL_EMPTY_BOTTLE_ITEM
    { 11, 13 }  // FIREWORKS_FESTIVAL_EMPTY_BOTTLE_ITEM
};


// forward declarations
u8 handlePurchase(u16 storeItemIndex, s32 quantity);


//INCLUDE_ASM("asm/nonmatchings/game/shop", intializeShopDialogue);

void intializeShopDialogue(u8 storeItemIndex) {

    shopContext.mode = shopItemStartingMode[storeItemIndex];

    shopContext.storeItemIndex = storeItemIndex;
    
    shopContext.itemTextIndex = itemDescriptionTextIndices[storeItemIndex];
    
    shopContext.quantity = 1;
    shopContext.buySelected = FALSE;

    setMainLoopCallbackFunctionIndex(SHOP_DIALOGUE);

}

//INCLUDE_ASM("asm/nonmatchings/game/shop", loadShopItemSprite);

void loadShopItemSprite(u8 index) {
    
    // TODO: label 98 with offset macro
    dmaSprite(shopItemSpriteIndexOffsets[index] + 98,
        &_holdableItemsTextureSegmentRomStart, &_holdableItemsTextureSegmentRomEnd, 
        &_holdableItemsAssetsIndexSegmentRomStart, &_holdableItemsAssetsIndexSegmentRomEnd, 
        &_holdableItemsSpritesheetIndexSegmentRomStart, &_holdableItemsSpritesheetIndexSegmentRomEnd, 
        shopItemTextureBuffers[index][0], shopItemTextureBuffers[index][1], 
        (u16*)ENTITY_SLOTS_8_13_PALETTE,
        (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA,
        (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX,
        (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP, 
        1, TRUE);

    setSpriteScale(SHOP_ITEMS + shopItemSpriteIndexOffsets[index], 1.0f, 1.0f, 1.0f);
    setSpriteBlendMode(SHOP_ITEMS + shopItemSpriteIndexOffsets[index], SPRITE_BLEND_ALPHA_DECAL);
    setSpriteBaseRGBA(SHOP_ITEMS + shopItemSpriteIndexOffsets[index], 255, 255, 255, 255);
    setSpriteColor(SHOP_ITEMS + shopItemSpriteIndexOffsets[index], 255, 255, 255, 255);

    setMapObject(MAIN_MAP_INDEX, shopItemSpriteIndexOffsets[index], SHOP_ITEMS + shopItemSpriteIndexOffsets[index], getAnimationOffsetFromScript(&heldItemsAnimationScripts, getItemAnimationIndex(shopItemAnimationIndices[index])), shopItemMapCoordinates[index].x, shopItemMapCoordinates[index].y, shopItemMapCoordinates[index].z, 0xFF, 0xFF, 0, 0);

}

//INCLUDE_ASM("asm/nonmatchings/game/shop", deactivateShopItemMapObject);

void deactivateShopItemMapObject(u8 index) {

    if (shopItemSpriteIndexOffsets[index] != 0xFF) {
        deactivateMapObject(MAIN_MAP_INDEX, shopItemSpriteIndexOffsets[index]);
    }

}

//INCLUDE_ASM("asm/nonmatchings/game/shop", handlePickUpShopItem);

void handlePickUpShopItem(u8 shopItemIndex) {
    
    gPlayer.shopItemIndex = shopItemIndex;

    if (checkCanPickUpShopItem(shopItemIndex)) {

        gPlayer.itemInfoIndex = initializeHeldItem(shopItemToItemInfoIndices[shopItemIndex], ITEM_STATE_PICKUP, shopItemAnimationIndices[shopItemIndex], 0, 0);
        playSfx(PICKING_UP_SFX);

        if (shopItemSpriteIndexOffsets[shopItemIndex] != 0xFF) {
            deactivateMapObject(MAIN_MAP_INDEX, shopItemSpriteIndexOffsets[shopItemIndex]);
        }
    }

    setPlayerAction(SHOPPING, ANIM_SHOPPING);
    
}

//INCLUDE_ASM("asm/nonmatchings/game/shop", checkCanPickUpShopItem);

u8 checkCanPickUpShopItem(u8 index) {
    return shopItemPickUpEnabled[index];
}

//INCLUDE_ASM("asm/nonmatchings/game/shop", shopDialogueCallback);

void shopDialogueCallback(void) {

    bool set = FALSE;
    u8 temp;
    u8 *temp2;
    u8 index;

    switch (shopContext.mode) {

        case SHOP_MODE_OPEN_DESCRIPTION:
            
            setMessageBoxViewSpacePosition(0, 24.0f, -64.0f, 352.0f);
            setMessageBoxSpriteIndices(0, 0, 0, 0);
            setMessageBoxInterpolationWithFlags(0, -4, 0);
            
            if (shopItemHasPurchaseConfirmation[shopContext.storeItemIndex] == FALSE) {
                initializeMessageBox(MAIN_MESSAGE_BOX_INDEX, shopItemTextAddressesIndex[shopContext.storeItemIndex], shopContext.itemTextIndex, 0);
                shopContext.mode = SHOP_MODE_COMMIT_PURCHASE;
            } else {
                initializeMessageBox(MAIN_MESSAGE_BOX_INDEX, shopItemTextAddressesIndex[shopContext.storeItemIndex], shopContext.itemTextIndex, 0x8000);
                shopContext.mode++; // SHOP_MODE_OPEN_PURCHASE_PROMPT
            }
            
            break;
        
        case SHOP_MODE_OPEN_PURCHASE_PROMPT:
            
            if (messageBoxes[MAIN_MESSAGE_BOX_INDEX].flags & 4) {
                
                loadShopIcons();

                if (shopItemMaxQuantities[shopContext.storeItemIndex] >= 2) {
                    setNumberSprites(0, 0x8F, &_shopIconsTextureSegmentRomStart, &_shopIconsTextureSegmentRomEnd, &_shopIconsAssetsIndexSegmentRomStart, &_shopIconsAssetsIndexSegmentRomEnd, (u8*)SHOP_ICONS_TEXTURE_BUFFER, (u16*)SHOP_ICONS_PALETTE_BUFFER, (AnimationFrameMetadata*)SHOP_ICONS_ANIMATION_FRAME_METADATA_BUFFER, (u32*)SHOP_ICONS_TEXTURE_TO_PALETTE_LOOKUP_BUFFER, 0, 2, 0, -16.0f, 64.0f, 256.0f, 10);
                    dmaNumberSprites(0, shopContext.quantity, 1, 3);
                    updateShopQuantityArrows(shopItemMaxQuantities[shopContext.storeItemIndex]);
                }
                
                setMessageBoxInterpolationWithFlags(0, -4, 2);
                convertNumberToGameVariableString(0x12, shopContext.quantity * prices[shopContext.storeItemIndex], 0);
                setMessageBoxViewSpacePosition(0, 24.0f, -64.0f, 352.0f);
                setMessageBoxSpriteIndices(0, 0, 0, 0);
                initializeMessageBox(MAIN_MESSAGE_BOX_INDEX, shopItemTextAddressesIndex[shopContext.storeItemIndex], purchaseConfirmationTextIndices[shopContext.storeItemIndex], MESSAGE_BOX_MODE_NO_INPUT);

                shopContext.mode++; // SHOP_MODE_AWAIT_QUANTITY_INPUT

            }
            
            break;
        
        case SHOP_MODE_AWAIT_QUANTITY_INPUT:
            
            if (checkButtonRepeat(CONTROLLER_1, BUTTON_STICK_NORTHWEST)) {

                if (!set) {
                    
                    if (shopContext.buySelected) {
                        playSfx(2);
                    }
                    
                    shopContext.buySelected = FALSE;
                    
                    updateShopBuyAnimation();
                    set = TRUE;

                }
                
            }
            
            if (checkButtonRepeat(CONTROLLER_1, BUTTON_STICK_SOUTHEAST)) {

                if (!set) {

                    if (shopContext.buySelected == FALSE) {
                        playSfx(2);
                    }
                    
                    shopContext.buySelected = TRUE;
                    
                    updateShopBuyAnimation();
                    set = TRUE;
                
                }
                
            }
            
            if (checkButtonRepeat(CONTROLLER_1, BUTTON_STICK_NORTHEAST)) {

                if (!set) {

                    if (shopContext.quantity < shopItemMaxQuantities[shopContext.storeItemIndex]) {
                    
                        shopContext.quantity++;
                    
                        dmaNumberSprites(0, shopContext.quantity, 1, 3);
                        convertNumberToGameVariableString(0x12, shopContext.quantity * prices[shopContext.storeItemIndex], 0);
                    
                        if (shopItemMaxQuantities[shopContext.storeItemIndex] >= 2) {
                            updateShopQuantityArrows(shopItemMaxQuantities[shopContext.storeItemIndex]);
                            playSfx(2);                           
                        }
                        
                    }

                    set = TRUE;       

                }

            }
            
            if (checkButtonRepeat(CONTROLLER_1, BUTTON_STICK_SOUTHWEST)) {

                if (!set) {

                    if (shopContext.quantity< 2) {
                        set = TRUE;
                    } else {
                    
                        shopContext.quantity--;
                    
                        dmaNumberSprites(0, shopContext.quantity, 1, 3);
                        convertNumberToGameVariableString(0x12, shopContext.quantity * prices[shopContext.storeItemIndex], 0);

                        if (shopItemMaxQuantities[shopContext.storeItemIndex] >= 2) {
                            updateShopQuantityArrows(shopItemMaxQuantities[shopContext.storeItemIndex]);
                            playSfx(2);
                        }

                    }

                    set = TRUE;  

                }

            }
            
            if (checkButtonPressed(CONTROLLER_1, BUTTON_A)) {

                if (!set) {

                    deactivateNumberSprites(0);

                    resetAnimationState(0x82);
                    resetAnimationState(0x83);
                    resetAnimationState(0x84);
                    deactivateSprite(0x85);
                    deactivateSprite(0x86);
                    deactivateSprite(0x87);
                    
                    if (shopContext.buySelected == FALSE) {
                        shopContext.mode = SHOP_MODE_COMMIT_PURCHASE;
                        playSfx(0);
                    } else {
                        shopContext.mode = SHOP_MODE_DECLINE_PURCHASE;
                        playSfx(1);
                    }
                    
                    set = TRUE;

                }
                
            }
            
            if (checkButtonPressed(CONTROLLER_1, BUTTON_B)) {

                if (!set) {
                    
                    deactivateNumberSprites(0);

                    deactivateSprite(0x82);
                    deactivateSprite(0x83);
                    deactivateSprite(0x84);
                    deactivateSprite(0x85);
                    deactivateSprite(0x86);
                    deactivateSprite(0x87);
                    
                    shopContext.buySelected = TRUE;
                    shopContext.mode = SHOP_MODE_DECLINE_PURCHASE;

                    playSfx(1);

                }
                
            }
            
            break;     

        case SHOP_MODE_COMMIT_PURCHASE:

            temp = handlePurchase(shopContext.storeItemIndex, shopContext.quantity);

            dmaNumberSprites(1, gGold, 8, 3);
            setMessageBoxViewSpacePosition(0, 24.0f, -64.0f, 352.0f);
            setMessageBoxSpriteIndices(0, 0, 0, 0);
            setMessageBoxInterpolationWithFlags(0, -4, 0);

            switch (temp) {                        
                
                // not enough money
                case 0:                                     
                    initializeMessageBox(MAIN_MESSAGE_BOX_INDEX, shopItemTextAddressesIndex[shopContext.storeItemIndex], notEnoughMoneyTextIndices[shopContext.storeItemIndex], 0);
                    shopContext.mode = SHOP_MODE_EXIT_AFTER_INSUFFICIENT_FUNDS;
                    return;
                
                // successful purchase
                case 1:
                    // FIXME: fake
                    temp2 = &shopContext.storeItemIndex;
                    initializeMessageBox(MAIN_MESSAGE_BOX_INDEX, shopItemTextAddressesIndex[temp2[0]], postPurchaseTextIndices[shopContext.storeItemIndex], 0);
                    break;
                
                // no space in rucksack
                case 2:                
                    temp2 = &shopContext.storeItemIndex;
                    if (sendToFarmTextIndices[temp2[0]]) {
                        initializeMessageBox(MAIN_MESSAGE_BOX_INDEX, shopItemTextAddressesIndex[temp2[0]], sendToFarmTextIndices[shopContext.storeItemIndex], 0);
                    } 
                    
                    break;
                
                // exceed max quantity
                case 3:
                    initializeMessageBox(MAIN_MESSAGE_BOX_INDEX, shopItemTextAddressesIndex[shopContext.storeItemIndex], exceedMaxQuantityTextIndices[shopContext.storeItemIndex], 0);
                    shopContext.mode = SHOP_MODE_EXIT_DEFAULT;
                    return;
                
                case 4:
                    temp2 = &shopContext.storeItemIndex;
                    initializeMessageBox(MAIN_MESSAGE_BOX_INDEX, shopItemTextAddressesIndex[temp2[0]], shopGiftTextIndex, 0);
                    break;
                
                default:
                    return;
                    
            }

            if (shopItemSkipsHeldDisplay[temp2[0]]) {
                shopContext.mode = SHOP_MODE_EXIT_SKIP_HELD_DISPLAY;
            } else {
                shopContext.mode = SHOP_MODE_EXIT_DEFAULT;
            }

            break;

        case SHOP_MODE_DECLINE_PURCHASE:

            setMessageBoxViewSpacePosition(0, 24.0f, -64.0f, 352.0f);
            setMessageBoxSpriteIndices(0, 0, 0, 0);
            setMessageBoxInterpolationWithFlags(0, -4, 0);
            initializeMessageBox(MAIN_MESSAGE_BOX_INDEX, shopItemTextAddressesIndex[shopContext.storeItemIndex], declinePurchaseTextIndices[shopContext.storeItemIndex], 0);
            shopContext.mode = SHOP_MODE_EXIT_DEFAULT;

            break;
        
        case SHOP_MODE_EXIT_DEFAULT:

            if (messageBoxes[MAIN_MESSAGE_BOX_INDEX].flags & 4) {
                closeOverlayScreen();
                setMainLoopCallbackFunctionIndex(MAIN_GAME);
                setPlayerAction(playerShopAnimationIndices[shopContext.storeItemIndex].animationIndex, playerShopAnimationIndices[shopContext.storeItemIndex].nextAnimationIndex);
                gPlayer.actionPhase = playerShopActionPhase[shopContext.storeItemIndex];
                shopContext.mode = SHOP_MODE_DONE;
                resumeGameplay();
            }

            break;

        case SHOP_MODE_EXIT_SKIP_HELD_DISPLAY:

            if (messageBoxes[MAIN_MESSAGE_BOX_INDEX].flags & 4) {
                closeOverlayScreen();
                setMainLoopCallbackFunctionIndex(MAIN_GAME);
                setPlayerAction(playerShopAnimationIndices[shopContext.storeItemIndex].animationIndex, playerShopAnimationIndices[shopContext.storeItemIndex].nextAnimationIndex);
                gPlayer.actionPhase = 3;
                shopContext.mode = SHOP_MODE_DONE;
                resumeGameplay();
            }

            break;

        case SHOP_MODE_EXIT_AFTER_INSUFFICIENT_FUNDS:

            if (messageBoxes[MAIN_MESSAGE_BOX_INDEX].flags & 4) {
                closeOverlayScreen();
                setMainLoopCallbackFunctionIndex(MAIN_GAME);
                setPlayerAction(playerShopAnimationIndices[shopContext.storeItemIndex].animationIndex, playerShopAnimationIndices[shopContext.storeItemIndex].nextAnimationIndex);
                gPlayer.actionPhase = playerShopEndActionPhase[shopContext.storeItemIndex];
                shopContext.mode = SHOP_MODE_DONE;
                resumeGameplay();
            }

            break;

        default:
            break;
    }
    
}

//INCLUDE_ASM("asm/nonmatchings/game/shop", handlePurchase);

u8 handlePurchase(u16 storeItemIndex, s32 quantity) {

    u8 result = 0;
    u8 temp;

    if (gGold >= quantity*prices[storeItemIndex]) {

        result = 1;

        switch (storeItemIndex) {

            case FLOWER_SHOP_TURNIP_SEEDS_ITEM:

                result = 3;

                if ((turnipSeedsQuantity + quantity) < MAX_SEEDS + 1) {
                    result = storeTool(TURNIP_SEEDS);
                    turnipSeedsQuantity += adjustValue(turnipSeedsQuantity, quantity, MAX_SEEDS);
                }

                break;

            case FLOWER_SHOP_POTATO_SEEDS_ITEM:

                result = 3;

                if ((potatoSeedsQuantity + quantity) < MAX_SEEDS + 1) {
                    result = storeTool(POTATO_SEEDS);
                    potatoSeedsQuantity += adjustValue(potatoSeedsQuantity, quantity, MAX_SEEDS);
                }

                break;

            case FLOWER_SHOP_CABBAGE_SEEDS_ITEM:

                result = 3;

                if ((cabbageSeedsQuantity + quantity) < MAX_SEEDS + 1) {
                    result = storeTool(CABBAGE_SEEDS);
                    cabbageSeedsQuantity += adjustValue(cabbageSeedsQuantity, quantity, MAX_SEEDS);
                }

                break;

            case FLOWER_SHOP_GRASS_SEEDS_ITEM:

                result = 3;

                if ((grassSeedsQuantity + quantity) < MAX_SEEDS + 1) {
                    result = storeTool(GRASS_SEEDS);
                    grassSeedsQuantity += adjustValue(grassSeedsQuantity, quantity, MAX_SEEDS);
                }

                break;

            case FLOWER_SHOP_TOMATO_SEEDS_ITEM:

                result = 3;

                if ((tomatoSeedsQuantity + quantity) < MAX_SEEDS + 1) {
                    result = storeTool(TOMATO_SEEDS);
                    tomatoSeedsQuantity += adjustValue(tomatoSeedsQuantity, quantity, MAX_SEEDS);
                }

                break;

            case FLOWER_SHOP_CORN_SEEDS_ITEM:

                result = 3;

                if ((cornSeedsQuantity + quantity) < MAX_SEEDS + 1) {
                    result = storeTool(CORN_SEEDS);
                    cornSeedsQuantity += adjustValue(cornSeedsQuantity, quantity, MAX_SEEDS);
                }

                break;

            case FLOWER_SHOP_EGGPLANT_SEEDS_ITEM:

                result = 3;

                if ((eggplantSeedsQuantity + quantity) < MAX_SEEDS + 1) {
                    result = storeTool(EGGPLANT_SEEDS);
                    eggplantSeedsQuantity += adjustValue(eggplantSeedsQuantity, quantity, MAX_SEEDS);
                }

                break;

            case FLOWER_SHOP_STRAWBERRY_SEEDS_ITEM:

                result = 3;

                if ((strawberrySeedsQuantity + quantity) < MAX_SEEDS + 1) {
                    result = storeTool(STRAWBERRY_SEEDS);
                    strawberrySeedsQuantity += adjustValue(strawberrySeedsQuantity, quantity, MAX_SEEDS);
                }

                break;

            case FLOWER_SHOP_MOON_DROP_SEEDS_ITEM:
                
                result = 3;
                
                if ((moondropSeedsQuantity + quantity) < MAX_SEEDS + 1) {
                    
                    result = storeTool(MOON_DROP_SEEDS);
                    moondropSeedsQuantity += adjustValue(moondropSeedsQuantity, quantity, MAX_SEEDS);

                    if (!checkLifeEventBit(HAVE_FLOWER_SHOP_GIFT_CARD)) {
                        
                        acquireKeyItem(FLOWER_SHOP_CARD);
                        shopGiftTextIndex = 0x24;
                        setLifeEventBit(HAVE_FLOWER_SHOP_GIFT_CARD);
                        flowerShopPoints += adjustValue(flowerShopPoints, quantity, MAX_FLOWER_SHOP_POINTS);
                        result = 4;
                        
                    } else {
                        
                        flowerShopPoints += adjustValue(flowerShopPoints, quantity, MAX_FLOWER_SHOP_POINTS);
                    }
                    
                }
                
                break;
            
            case FLOWER_SHOP_BLUE_MIST_SEEDS_ITEM:

                result = 3;

                if ((blueMistSeedsQuantity + quantity) < MAX_BLUE_MIST_SEEDS + 1) {

                    result = storeTool(BLUE_MIST_SEEDS);
                    blueMistSeedsQuantity += adjustValue(blueMistSeedsQuantity, quantity, MAX_BLUE_MIST_SEEDS);

                    if (!checkLifeEventBit(HAVE_FLOWER_SHOP_GIFT_CARD)) {

                        acquireKeyItem(FLOWER_SHOP_CARD);
                        shopGiftTextIndex = 0x24;
                        setLifeEventBit(HAVE_FLOWER_SHOP_GIFT_CARD);
                        flowerShopPoints += adjustValue(flowerShopPoints, quantity, MAX_FLOWER_SHOP_POINTS);
                        result = 4;

                    } else {

                        flowerShopPoints += adjustValue(flowerShopPoints, quantity, MAX_FLOWER_SHOP_POINTS);

                    }

                    setLifeEventBit(BOUGHT_BLUE_MIST_SEEDS);

                }

                break;

            case BAKERY_CAKE_ITEM:

                gPlayer.heldItem = CAKE_HELD_ITEM;

                initializePlayerHeldItem();

                if (!checkLifeEventBit(HAVE_BAKEY_CARD)) {

                    acquireKeyItem(BAKERY_CARD);
                    shopGiftTextIndex = 0x41;
                    setLifeEventBit(HAVE_BAKEY_CARD);

                    bakeryCardPoints += adjustValue(bakeryCardPoints, quantity, MAX_BAKERY_CARD_POINTS);

                    result = 4;

                } else {

                    bakeryCardPoints += adjustValue(bakeryCardPoints, quantity, MAX_BAKERY_CARD_POINTS);

                }

                break;

            case BAKERY_PIE_ITEM:

                gPlayer.heldItem = PIE_HELD_ITEM;
                initializePlayerHeldItem();

                if (!checkLifeEventBit(HAVE_BAKEY_CARD)) {

                    acquireKeyItem(BAKERY_CARD);

                    shopGiftTextIndex = 0x41;

                    setLifeEventBit(HAVE_BAKEY_CARD);

                    bakeryCardPoints += adjustValue(bakeryCardPoints, quantity, MAX_BAKERY_CARD_POINTS);

                    result = 4;

                } else {
                    bakeryCardPoints += adjustValue(bakeryCardPoints, quantity, MAX_BAKERY_CARD_POINTS);
                }

                break;

            case BAKERY_COOKIES:
                gPlayer.heldItem = COOKIES_HELD_ITEM;
                initializePlayerHeldItem();
                temp = 0;
                break;

            case BAKERY_CAKE:
                gPlayer.heldItem = CAKE_HELD_ITEM;
                initializePlayerHeldItem();
                temp = 0;
                break;

            case BAKERY_PIE:
                gPlayer.heldItem = PIE_HELD_ITEM;
                initializePlayerHeldItem();
                temp = 0;
                break;

            case BAKERY_TEA:
                gPlayer.heldItem = BOTTLE_WITH_TEA_HELD_ITEM;
                initializePlayerHeldItem();
                temp = 0;
                break;

            case BAKERY_WATER:
                gPlayer.heldItem = BOTTLE_WITH_WATER_HELD_ITEM;
                initializePlayerHeldItem();
                temp = 0;
                break;

            case RICK_STORE_MILKER_ITEM:
                result = storeTool(MILKER);
                break;

            case RICK_STORE_BRUSH_ITEM:
                result = storeTool(BRUSH);
                break;

            case RICK_STORE_CLIPPERS_ITEM:
                result = storeTool(CLIPPERS);
                break;

            case RICK_STORE_BLUE_FEATHER_ITEM:
                result = storeTool(BLUE_FEATHER);
                break;

            case RICK_STORE_RUG_ITEM:
                setLifeEventBit(HAVE_RUG);
                result = 1;
                temp = 0;
                break;

            case RICK_STORE_CABINET_ITEM:
                setLifeEventBit(HAVE_CABINET);
                setAnimalLocations(HOUSE);
                result = 1;
                temp = 0;
                break;

            case RICK_STORE_ICE_CREAM_MAKER_ITEM:

                setLifeEventBit(HAVE_ICE_CREAM_MAKER);
                setAnimalLocations(FARM);
                result = 1;
                temp = 0;

                break;

            case RANCH_STORE_CHICKEN_FEED_ITEM:

                result = 3;

                if ((chickenFeedQuantity + quantity) < MAX_CHICKEN_FEED + 1) {
                    result = storeTool(CHICKEN_FEED);
                    chickenFeedQuantity += adjustValue(chickenFeedQuantity, quantity, MAX_CHICKEN_FEED);
                }

                break;

            case RANCH_STORE_MIRACLE_POTION_ITEM:
                result = storeTool(MIRACLE_POTION);
                break;

            case RANCH_STORE_COW_MEDICINE_ITEM:
                result = storeTool(COW_MEDICINE);
                break;

            case RANCH_STORE_FODDER_ITEM:

                if ((fodderQuantity + quantity) < 999 + 1) {
                    fodderQuantity += adjustValue(fodderQuantity, quantity, 999);
                    result = 2;
                } else {
                    result = 3;
                }

                break;

            case RANCH_STORE_CHICKEN_ITEM:

                // check animal count
                if (getTotalChickenCount() != 6) {

                    result = 1;

                    setDailyEventBit(PURCHASED_ANIMAL);
                    setDailyEventBit(DAILY_ANIMAL_TRANSACTION);

                    selectedAnimalType = CHICKEN_TYPE;

                } else {
                    result = 3;
                }

                break;

            case RANCH_STORE_SHEEP_ITEM:

                if (getTotalFarmAnimalsCount() != 8) {
                
                    result = 1;
                    
                    if (!checkLifeEventBit(HAVE_BELL)) {
                        
                        storeTool(BELL);
                        shopGiftTextIndex = 83;
                        result = 4;
                        setLifeEventBit(HAVE_BELL);
                        
                    }

                    setDailyEventBit(PURCHASED_ANIMAL);
                    setDailyEventBit(DAILY_ANIMAL_TRANSACTION);
                    selectedAnimalType = SHEEP_TYPE;
                    
                } else {
                    
                    result = 3;
                    
                }

                break;

            case RANCH_STORE_COW_ITEM:

                if (getTotalFarmAnimalsCount() != 8) {

                    result = 1;

                    if (!checkLifeEventBit(HAVE_BELL)) {

                        storeTool(BELL);
                        shopGiftTextIndex = 83;
                        result = 4;
                        setLifeEventBit(HAVE_BELL);

                    }

                    setDailyEventBit(PURCHASED_ANIMAL);
                    setDailyEventBit(DAILY_ANIMAL_TRANSACTION);
                    selectedAnimalType = COW_TYPE;

                } else {
                    result = 3;
                }

                break;

            case POTION_SHOP_CURE_ALL_ITEM:
                gPlayer.bottleContents = BOTTLE_CONTENTS_CURE_ALL_MEDICINE;
                result = 1;

                break;

            case POTION_SHOP_VITAMIN_ITEM:
                gPlayer.bottleContents = BOTTLE_CONTENTS_VITAMIN_PREPARATION;
                result = 1;

                break;

            case POTION_SHOP_STRONG_VITAMINS_ITEM:
                gPlayer.bottleContents = BOTTLE_CONTENTS_VITAMIN_GOLD;
                result = 1;

                break;

            case SOUVENIR_SHOP_OCARINA_ITEM:
                acquireKeyItem(OCARINA);
                setLifeEventBit(HAVE_OCARINA);
                result = 1;
                temp = 0;

                break;

            case SOUVENIR_SHOP_BLUE_VASE_ITEM:
                setLifeEventBit(HAVE_VASE);
                temp = 0;
                break;

            case TAVERN_WINE_ITEM:
                gPlayer.heldItem = BOTTLE_WITH_WINE_HELD_ITEM;
                initializePlayerHeldItem();
                temp = 0;
                break;

            case TAVERN_LIQUOR_ITEM:
                gPlayer.heldItem = 121;
                initializePlayerHeldItem();
                temp = 0;
                break;

            case TAVERN_BEER_ITEM:
                gPlayer.heldItem = 122;
                initializePlayerHeldItem();
                temp = 0;
                break;

            case TAVERN_MILK_ITEM:
                gPlayer.heldItem = BOTTLE_WITH_MILK_HELD_ITEM;
                initializePlayerHeldItem();
                temp = 0;
                break;

            case TAVERN_WATERN_ITEM:
                gPlayer.heldItem = BOTTLE_WITH_WATER_HELD_ITEM;
                initializePlayerHeldItem();
                temp = 0;
                break;

            case HORSE_RACE_TEA:
                gPlayer.heldItem = BOTTLE_WITH_TEA_HELD_ITEM;
                initializePlayerHeldItem();
                temp = 0;
                break;

            case HORSE_RACE_MILK:
                gPlayer.heldItem = BOTTLE_WITH_MILK_HELD_ITEM;
                initializePlayerHeldItem();
                temp = 0;
                break;

            case DOG_RACE_TEA:
                gPlayer.heldItem = BOTTLE_WITH_TEA_HELD_ITEM;
                initializePlayerHeldItem();
                temp = 0;
                break;

            case DOR_RACE_MILK:
                gPlayer.heldItem = BOTTLE_WITH_MILK_HELD_ITEM;
                initializePlayerHeldItem();
                temp = 0;
                break;

            case RACE_COOKIES:
                gPlayer.heldItem = COOKIES_HELD_ITEM;
                initializePlayerHeldItem();
                temp = 0;
                break;

            case FESTIVAL_COTTON_CANDY:
                gPlayer.heldItem = COTTON_CANDY_HELD_ITEM;
                initializePlayerHeldItem();
                temp = 0;
                break;

            case FESTIVAL_FRIED_OCTOPUS:
                gPlayer.heldItem = FRIED_OCTUPUS_HELD_ITEM;
                initializePlayerHeldItem();
                temp = 0;
                break;

            case FESTIVAL_ROASTED_CORN:
                gPlayer.heldItem = ROASTED_CORN_HELD_ITEM;
                initializePlayerHeldItem();
                temp = 0;
                break;
            
            case FLOWER_FESTIVAL_PINK_CAT_MINT_SEEDS_ITEM:

                if ((pinkCatMintSeedsQuantity + quantity) < 20 + 1) {

                    result = storeTool(PINK_CAT_MINT_SEEDS);
                    pinkCatMintSeedsQuantity += adjustValue(pinkCatMintSeedsQuantity, quantity, 20);

                    if (checkLifeEventBit(HAVE_FLOWER_SHOP_GIFT_CARD)) {
                        flowerShopPoints += adjustValue(flowerShopPoints, quantity, MAX_FLOWER_SHOP_POINTS);
                    }

                } else {
                    result = 3;
                }

                break;

            case FLOWER_FESTIVAL_EMPTY_BOTTLE_ITEM:
            case FIREWORKS_FESTIVAL_EMPTY_BOTTLE_ITEM:
                result = storeTool(EMPTY_BOTTLE);
                break;

            default:
                break;
       
        }

        // FIXME: shouldn't be necessary
        temp = result - 1;

        // should be:        
        // if (0 < result && result < 3 || result == 4) {
        if (temp < 2 || result == 4) {
            gGold += adjustValue(gGold, (-quantity * prices[storeItemIndex]), MAX_GOLD);
        }

    }
    
    return result;
    
}

//INCLUDE_ASM("asm/nonmatchings/game/shop", checkShopItemShouldBeDisplayed);

bool checkShopItemShouldBeDisplayed(u16 itemIndex) {

    bool result = FALSE;

    switch (itemIndex) {

        case FLOWER_SHOP_TURNIP_SEEDS_ITEM:

            if (gSeason != SPRING) {
                if (checkLifeEventBit(HAVE_GREENHOUSE)) {
                    result = 1;
                }
            } else {
                result = 1;
            }

            break;

        case FLOWER_SHOP_POTATO_SEEDS_ITEM:

            if (gSeason != SPRING) {
                if (checkLifeEventBit(HAVE_GREENHOUSE)) {
                    result = 1;
                }
            } else {
                result = 1;
            }

            break;

        case FLOWER_SHOP_CABBAGE_SEEDS_ITEM:

            if (gSeason != SPRING) {
                if (checkLifeEventBit(HAVE_GREENHOUSE)) {
                    result = 1;
                }
            } else {
                result = 1;
            }

            break;


        case FLOWER_SHOP_GRASS_SEEDS_ITEM:

            // FIXME: should be a range
            if ((u32)(gSeason - 1) < SUMMER) {
                result = 1;
            }

            break;

        case FLOWER_SHOP_TOMATO_SEEDS_ITEM:

            if (gSeason != SUMMER) {
                if (checkLifeEventBit(HAVE_GREENHOUSE)) {
                    result = 1;
                }
            } else {
                result = 1;
            }

            break;

        case FLOWER_SHOP_CORN_SEEDS_ITEM:

            if (gSeason != SUMMER) {
                if (checkLifeEventBit(HAVE_GREENHOUSE)) {
                    result = 1;
                }
            } else {
                result = 1;
            }

            break;

       case FLOWER_SHOP_EGGPLANT_SEEDS_ITEM:

            if (gSeason != AUTUMN) {
                if (checkLifeEventBit(HAVE_GREENHOUSE)) {
                    result = 1;
                }
            } else {
                result = 1;
            }

            break;

       case FLOWER_SHOP_STRAWBERRY_SEEDS_ITEM:

            if (gSeason == WINTER) {
                if (checkLifeEventBit(HAVE_GREENHOUSE)) {
                    result = 1;
                }
            }

            break;

        case FLOWER_SHOP_MOON_DROP_SEEDS_ITEM:

            if (gSeason == SPRING) {
                result = 1;
            }

            break;

        case FLOWER_SHOP_BLUE_MIST_SEEDS_ITEM:

            if (!checkLifeEventBit(BOUGHT_BLUE_MIST_SEEDS)) {

                if (gYear >= 2) {

                    // FIXME: probably should be a switch
                    if (gSeason != SUMMER) {

                        if (gSeason == SPRING) {

                            if (gDayOfMonth >= 24) {
                                result = 1;
                                break;
                            }
                        }

                        break;

                    }

                    result = 1;

                }
            }

            break;

        case RICK_STORE_MILKER_ITEM:

            if (!getTotalFarmAnimalsByType(2) && !getTotalFarmAnimalsByType(1) && !getTotalFarmAnimalsByType(0) && !getTotalFarmAnimalsByType(3)) {
                // removed code
            } else if (!checkHaveTool(MILKER)) {
                result = 1;
            }

            break;

        case RICK_STORE_BRUSH_ITEM:

            if (!checkHaveTool(BRUSH)) {
                result = 1;
            }

            break;

        case RICK_STORE_CLIPPERS_ITEM:

            if (!getTotalFarmAnimalsByType(5) && !getTotalFarmAnimalsByType(4) && !getTotalFarmAnimalsByType(6)) {
                // removed code
            } else if (!checkHaveTool(CLIPPERS)) {
                result = 1;
            }

            break;

        case RICK_STORE_BLUE_FEATHER_ITEM:

            if (checkBacheloretteReadyForMarriage() && !checkHaveTool(BLUE_FEATHER) && checkLifeEventBit(HAVE_KITCHEN) && !checkLifeEventBit(MARRIED) && !checkLifeEventBit(ENGAGED)) {
                result = 1;
            }

            break;

        case RICK_STORE_RUG_ITEM:

            if (gYear == 1 && !(gSeason < AUTUMN) || !(gYear < 2)) {
                if (!checkLifeEventBit(HAVE_RUG)) {
                    result = 1;
                }
            }

            break;

        case RICK_STORE_CABINET_ITEM:

            if (gYear == 1 && !(gSeason < SUMMER) || !(gYear < 2)) {
                if (!checkLifeEventBit(HAVE_CABINET)) {
                    result = 1;
                }
            }

            break;

        case RANCH_STORE_CHICKEN_FEED_ITEM:
            result = 1;
            break;

        case RANCH_STORE_MIRACLE_POTION_ITEM:

            if (getTotalFarmAnimalsByType(2) && !getTotalFarmAnimalsByType(3) && getTotalPregnantFamAnimals() == 0) {
                if (!checkHaveTool(MIRACLE_POTION)) {
                    result = 1;
                }
            }

            break;

        case RANCH_STORE_COW_MEDICINE_ITEM:

            if (getTotalFarmAnimalsCount() != 0) {
                if (!checkHaveTool(COW_MEDICINE)) {
                    result = 1;
                }
            }

            break;

        case RANCH_STORE_FODDER_ITEM:
            result = 1;
            break;

        case POTION_SHOP_CURE_ALL_ITEM:

            if (gYear == 1 && !(gSeason < SUMMER) || !(gYear < 2)) {
                if (checkHaveTool(EMPTY_BOTTLE) == TRUE) {
                    if (gPlayer.bottleContents == BOTTLE_CONTENTS_EMPTY) {
                        result = 1;
                    } else {
                        result = 2;
                    }
                } else {
                    result = 3;
                }
            }

            break;

        case POTION_SHOP_VITAMIN_ITEM:

            if (gYear == 1 && !(gSeason < AUTUMN) || !(gYear < 2)) {
                if (checkHaveTool(EMPTY_BOTTLE) == TRUE) {
                    if (gPlayer.bottleContents == BOTTLE_CONTENTS_EMPTY) {
                        result = 1;
                    } else {
                        result = 2;
                    }
                } else {
                    result = 3;
                }
            }

            break;

        case POTION_SHOP_STRONG_VITAMINS_ITEM:

            if (checkLifeEventBit(GAVE_PONTATA_ROOT_TO_POTION_SHOP_DEALER)) {

                if (checkHaveTool(EMPTY_BOTTLE) == TRUE) {

                    if (gPlayer.bottleContents == BOTTLE_CONTENTS_EMPTY) {
                        result = 1;
                    } else {
                        result = 2;
                    }

                } else {
                    result = 3;
                }
            }

            break;

        case SOUVENIR_SHOP_OCARINA_ITEM:

            if (gYear == 1 && !(gSeason < AUTUMN) || !(gYear < SUMMER)) {
                if (!checkHaveKeyItem(OCARINA)) {
                    result = 1;
                }
            }

            break;

        case SOUVENIR_SHOP_VASE_EARLY_ITEM:

            if (!checkLifeEventBit(GAVE_BLUE_ROCK_TO_SAIBARA) && !checkLifeEventBit(HAVE_VASE)) {
                result = 1;
            }

            break;

        case SOUVENIR_SHOP_BLUE_VASE_ITEM:

            if (checkLifeEventBit(GAVE_BLUE_ROCK_TO_SAIBARA) && !checkLifeEventBit(HAVE_VASE)) {
                result = 1;
            }

            break;

        case FLOWER_FESTIVAL_PINK_CAT_MINT_SEEDS_ITEM:

            if (gCutsceneIndex == CUTSCENE_FLOWER_FESTIVAL) {
                result = 1;
            }

            break;

        case FLOWER_FESTIVAL_EMPTY_BOTTLE_ITEM:

            if (gCutsceneIndex == CUTSCENE_FLOWER_FESTIVAL) {
                if (!checkHaveTool(EMPTY_BOTTLE)) {
                    result = 1;
                }
            }

            break;

        case FIREWORKS_FESTIVAL_EMPTY_BOTTLE_ITEM:

            if (gCutsceneIndex == CUTSCENE_FIREWORKS_FESTIVAL) {
                if (!checkHaveTool(EMPTY_BOTTLE)) {
                    result = 1;
                }
            }

            break;


        default:
            break;

    }

    return result;
    
}
