#include "common.h"

#include "game/transition.h"

#include "system/audio.h"
#include "system/controller.h"
#include "system/entity.h"
#include "system/globalSprites.h"
#include "system/map.h"
#include "system/math.h"
#include "system/message.h"
#include "system/mapController.h"

#include "game/animals.h"
#include "game/cutscenes.h"
#include "game/game.h"
#include "game/gameAudio.h"
#include "game/gameFile.h"
#include "game/gameStatus.h"
#include "game/initialize.h"
#include "game/items.h"
#include "game/level.h"
#include "game/load.h"
#include "game/npc.h"
#include "game/overlayScreens.h"
#include "game/player.h"
#include "game/time.h"
#include "game/weather.h"

#include "mainLoop.h"

#include "buffers/buffers.h"

#include "assetIndices/cutscenes.h"
#include "assetIndices/entities.h"
#include "assetIndices/maps.h"
#include "assetIndices/sprites.h"
      
// bss
// unused: likely to show player coordinates on screen for debugging
s16 D_80182D8C;
s16 D_8018A062;
s16 D_80237A20; 

//INCLUDE_ASM("asm/nonmatchings/game/transition", mainGameLoopCallback);

void mainGameLoopCallback(void) {
    
    // for debugging?
    D_8018A062 = (s16)entities[ENTITY_PLAYER].coordinates.x;
    D_80237A20 = (s16)entities[ENTITY_PLAYER].coordinates.y;
    D_80182D8C = (s16)entities[ENTITY_PLAYER].coordinates.z;
    
    if (checkEntityMapSpaceDependent(ENTITY_PLAYER) && !(checkEntityPaused(ENTITY_PLAYER))) {

        // increment clock and handle audio changes
        func_800D7C20();
        // handle button input and player animation
        updatePlayerAction();
        setNpcAnimations();
        updateAnimals();
        handlePlayerAnimation();

    }

    handleCutsceneCompletion();

    // dead code
    checkButtonPressed(CONTROLLER_1, BUTTON_C_RIGHT);
    checkButtonPressed(CONTROLLER_1, BUTTON_C_DOWN);
    checkButtonPressed(CONTROLLER_1, BUTTON_Z);
    
}

//INCLUDE_ASM("asm/nonmatchings/game/transition", func_80055F08);

// setup title/demo/non game cutscenes
// used by game.c
inline void func_80055F08(u16 cutsceneIndex, u16 entranceIndex, u8 arg2) {
    
    deactivateSprites();
    deactivateGlobalSprites();
    initializeMessageBoxes();
    initializeCutsceneExecutors();
    func_80053088();
    
    resetGlobalLighting();

    setEntitiesColor(0, 0, 0, 0);
    setMapControllerRGBA(MAIN_MAP_INDEX, 0, 0, 0, 0);

    gHour = 12;
    
    initializeEntityInstances(arg2);

    setEntrance(entranceIndex);

    gCutsceneIndex = cutsceneIndex;

    // trigger cutscene and load cutscene assets
    loadCutscene(0);
    
    // set up map/level
    loadLevelFromEntrance(gEntranceIndex);
 
    setupPlayerEntity(gEntranceIndex, FALSE);
    handlePlayerAnimation();

    setMainLoopCallbackFunctionIndex(SET_AUDIO_AND_LIGHTING);

}

//INCLUDE_ASM("asm/nonmatchings/game/transition", loadLevel);

// arg0 = entering new location
// called by map load callback, end of day callback, cutscene completion
void loadLevel(u8 arg0) {

    u8 mapIndex;
    u32 *ptr;

    gCutsceneCompletionFlags = 0;
    gCutsceneIndex = 0;
    gCutsceneFlags = 0;    
    
    toggleDailyEventBit(0x28);
    toggleDailyEventBit(0x4B);

    func_8005CDCC();
    syncPlayerCoordinatesFromEntity();
    updateAnimalCoordinates();
    updateNPCCoordinates();
    deactivateSprites();
    deactivateGlobalSprites();
    initializeCutsceneExecutors();
    deactivateNPCEntities();
    deactivateAnimalEntities();
    clearAllItemContextSlots();
    
    if (!checkDailyEventBit(0x2F)) {
        handleEndOfDayCutscenes();
    }

    setDailyEventBit(0x2F);
    
    mapIndex = getMapFromExit(gEntranceIndex);
    loadLevelFromEntrance(gEntranceIndex);

    if ((mapIndex == FARM || mapIndex == BARN) == 0 && mapIndex != COOP) {

        switch (gCutsceneIndex) {

            case SQUARE_FIREWORKS:
            case SOWING_FESTIVAL_POTION_SHOP_DEALER ... SOWING_FESTIVAL_HARRIS:
            case HORSE_RACE_SQUARE ... HORSE_RACE_STARTING_ANNOUNCEMENT:
            case FLOWER_FESTIVAL:
            case VEGETABLE_FESTIVAL_SQUARE:
            case FIREFLY_FESTIVAL:
            case HARVEST_FESTIVAL:
            case SEA_FESTIVAL:
            case EGG_FESTIVAL:
            case DOG_RACE_SQUARE ... DOG_RACE_AFTER_RACE:
            // spirit festival
            case 0x546 ... 0x548:
            case NEW_YEAR_FESTIVAL:
                initializeEntityInstances(2);
                break;            

            default:

                switch (gCutsceneIndex) {

                    case COW_FESTIVAL:
                        initializeEntityInstances(3);
                        break;
                    case HARVEST_FESTIVAL:
                    case SEA_FESTIVAL:
                    default:
                        initializeEntityInstances(1);
                        break;

                }

                break;

        }
        
    } else {
        initializeEntityInstances(0);
    }

   if (checkDailyEventBit(0x54)) {

        if (checkDailyEventBit(0x53)) {
            setPlayerAction(6, 8);
            gPlayer.heldItem = RICE_CAKE;
        } else {
            setPlayerAction(0, 0);
            gPlayer.heldItem = 0;
        }

        if (!(gCutsceneFlags & 1) && func_8009B5E0()) {
            playSfx(63);
        }

    }
    
    toggleDailyEventBit(0x53);
    toggleDailyEventBit(0x54);
    
    setupPlayerEntity(gEntranceIndex, arg0);
    
    func_80065AA0();
    loadActiveItemEntities();

    if (arg0 != 2) {

        ptr = &gCutsceneFlags;
        
        if (!(*ptr & (2 | 4))) {
            
            if (!checkDailyEventBit(0x4D)) {
                func_80088D54();
            }

            if (!(*ptr & (2 | 4))) {
                clearTempSpecialDialogueBits();
                setupActiveNPCs();
            }
        }

        if (!(gCutsceneFlags & 4)) {
            initializeAnimalEntities();
        }

    }
    
    handlePlayerAnimation();
    // handle item state
    updateHeldItemStates();
    // handle tool use
    processToolUseState();

    setEntitiesColor(0, 0, 0, 0);
    setMapControllerRGBA(MAIN_MAP_INDEX, 0, 0, 0, 0);
    
    unknownRGBA.r = 0;
    unknownRGBA.g = 0;
    unknownRGBA.b = 0;
    unknownRGBA.a = 0;
    
}


//INCLUDE_ASM("asm/nonmatchings/game/transition", initializeEntityInstances);

void initializeEntityInstances(u8 arg0) {

    switch (arg0) {       
        
        // farm or barn, how to play cutscene
        case 0:

            // Player
            initializeEntity(ENTITY_PLAYER, 0, 0x31, (u8*)PLAYER_TEXTURE_1_BUFFER, (u8*)PLAYER_TEXTURE_2_BUFFER, (u16*)PLAYER_PALETTE_BUFFER, (AnimationFrameMetadata*)PLAYER_ANIMATION_FRAME_METADATA_BUFFER, (u32*)PLAYER_SPRITESHEET_INDEX_BUFFER, (u32*)PLAYER_TEXTURE_TO_PALETTE_LOOKUP_BUFFER);

            // Dog
            initializeEntity(1, 1, 0x32, (u8*)ENTITY_REGION_SLOT_1_BASE, (u8*)(ENTITY_REGION_SLOT_1_BASE + DOG_SIZE_TEX), (u16*)ENTITY_SLOTS_1_20_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_1_20_ANIM_METADATA, (u32*)ENTITY_SLOTS_1_20_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_1_20_TEXTURE_TO_PALETTE_LOOKUP);
 
            // Chickens
            initializeEntity(2, 2, 0x33, CHICKEN_TEX1(ENTITY_REGION_CHICKEN_BASE, 0), CHICKEN_TEX2(ENTITY_REGION_CHICKEN_BASE, 0), (u16*)ENTITY_SLOTS_2_7_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_2_7_ANIM_METADATA, (u32*)ENTITY_SLOTS_2_7_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_2_7_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(3, 3, 0x34, CHICKEN_TEX1(ENTITY_REGION_CHICKEN_BASE, 1), CHICKEN_TEX2(ENTITY_REGION_CHICKEN_BASE, 1), (u16*)ENTITY_SLOTS_2_7_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_2_7_ANIM_METADATA, (u32*)ENTITY_SLOTS_2_7_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_2_7_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(4, 4, 0x35, CHICKEN_TEX1(ENTITY_REGION_CHICKEN_BASE, 2), CHICKEN_TEX2(ENTITY_REGION_CHICKEN_BASE, 2), (u16*)ENTITY_SLOTS_2_7_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_2_7_ANIM_METADATA, (u32*)ENTITY_SLOTS_2_7_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_2_7_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(5, 5, 0x36, CHICKEN_TEX1(ENTITY_REGION_CHICKEN_BASE, 3), CHICKEN_TEX2(ENTITY_REGION_CHICKEN_BASE, 3), (u16*)ENTITY_SLOTS_2_7_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_2_7_ANIM_METADATA, (u32*)ENTITY_SLOTS_2_7_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_2_7_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(6, 6, 0x37, CHICKEN_TEX1(ENTITY_REGION_CHICKEN_BASE, 4), CHICKEN_TEX2(ENTITY_REGION_CHICKEN_BASE, 4), (u16*)ENTITY_SLOTS_2_7_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_2_7_ANIM_METADATA, (u32*)ENTITY_SLOTS_2_7_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_2_7_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(7, 7, 0x38, CHICKEN_TEX1(ENTITY_REGION_CHICKEN_BASE, 5), CHICKEN_TEX2(ENTITY_REGION_CHICKEN_BASE, 5), (u16*)ENTITY_SLOTS_2_7_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_2_7_ANIM_METADATA, (u32*)ENTITY_SLOTS_2_7_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_2_7_TEXTURE_TO_PALETTE_LOOKUP);

            // Chicks
            initializeEntity(8, 8, 0x39, CHICK_TEX1(ENTITY_REGION_CHICK_BASE, 0), CHICK_TEX2(ENTITY_REGION_CHICK_BASE, 0), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(9, 9, 0x3A, CHICK_TEX1(ENTITY_REGION_CHICK_BASE, 1), CHICK_TEX2(ENTITY_REGION_CHICK_BASE, 1), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(10, 10, 0x3B, CHICK_TEX1(ENTITY_REGION_CHICK_BASE, 2), CHICK_TEX2(ENTITY_REGION_CHICK_BASE, 2), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(11, 11, 0x3C, CHICK_TEX1(ENTITY_REGION_CHICK_BASE, 3), CHICK_TEX2(ENTITY_REGION_CHICK_BASE, 3), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(12, 12, 0x3D, CHICK_TEX1(ENTITY_REGION_CHICK_BASE, 4), CHICK_TEX2(ENTITY_REGION_CHICK_BASE, 4), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(13, 13, 0x3E, CHICK_TEX1(ENTITY_REGION_CHICK_BASE, 5), CHICK_TEX2(ENTITY_REGION_CHICK_BASE, 5), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);

            // Cows
            initializeEntity(14, 14, 0x3F, (u8*)ENTITY_SLOT_14_TEXTURE_1, (u8*)ENTITY_SLOT_14_TEXTURE_2, (u16*)ENTITY_SLOT_14_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_14_ANIM_METADATA, (u32*)ENTITY_SLOT_14_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_14_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(15, 15, 0x40, (u8*)ENTITY_SLOT_15_TEXTURE_1, (u8*)ENTITY_SLOT_15_TEXTURE_2, (u16*)ENTITY_SLOT_15_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_15_ANIM_METADATA, (u32*)ENTITY_SLOT_15_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_15_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(16, 16, 0x41, (u8*)ENTITY_SLOT_16_TEXTURE_1, (u8*)ENTITY_SLOT_16_TEXTURE_2, (u16*)ENTITY_SLOT_16_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_16_ANIM_METADATA, (u32*)ENTITY_SLOT_16_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_16_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(17, 17, 0x42, (u8*)ENTITY_SLOT_17_TEXTURE_1, (u8*)ENTITY_SLOT_17_TEXTURE_2, (u16*)ENTITY_SLOT_17_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_17_ANIM_METADATA, (u32*)ENTITY_SLOT_17_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_17_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(18, 18, 0x43, (u8*)ENTITY_SLOT_18_TEXTURE_1, (u8*)ENTITY_SLOT_18_TEXTURE_2, (u16*)ENTITY_SLOT_18_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_18_ANIM_METADATA, (u32*)ENTITY_SLOT_18_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_18_TEXTURE_TO_PALETTE_LOOKUP);

            // Pony
            initializeEntity(19, 19, 0x44, (u8*)ENTITY_SLOT_19_TEXTURE_1, (u8*)ENTITY_SLOT_19_TEXTURE_2, (u16*)ENTITY_SLOTS_21_28_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_21_28_ANIM_METADATA, (u32*)ENTITY_SLOTS_21_28_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_21_28_TEXTURE_TO_PALETTE_LOOKUP);

            initializeEntity(20, 20, 0x45, (u8*)ENTITY_SLOT_20_TEXTURE_1, (u8*)ENTITY_SLOT_20_TEXTURE_2, (u16*)ENTITY_SLOTS_1_20_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_1_20_ANIM_METADATA, (u32*)ENTITY_SLOTS_1_20_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_1_20_TEXTURE_TO_PALETTE_LOOKUP);

            initializeEntity(0x27, 0x15, 0x46, (u8*)ENTITY_REGION_SLOT_39_BASE, (u8*)(ENTITY_REGION_SLOT_39_BASE + ITEM_SIZE_TEX), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);

            // Items
            initializeEntity(0x28, 0x16, 0x47, ITEM_TEX1(ENTITY_REGION_SLOTS_40_48_BASE, 0), ITEM_TEX2(ENTITY_REGION_SLOTS_40_48_BASE, 0), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x29, 0x17, 0x48, ITEM_TEX1(ENTITY_REGION_SLOTS_40_48_BASE, 1), ITEM_TEX2(ENTITY_REGION_SLOTS_40_48_BASE, 1), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x2A, 0x18, 0x49, ITEM_TEX1(ENTITY_REGION_SLOTS_40_48_BASE, 2), ITEM_TEX2(ENTITY_REGION_SLOTS_40_48_BASE, 2), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x2B, 0x19, 0x4A, ITEM_TEX1(ENTITY_REGION_SLOTS_40_48_BASE, 3), ITEM_TEX2(ENTITY_REGION_SLOTS_40_48_BASE, 3), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x2C, 0x1A, 0x4B, ITEM_TEX1(ENTITY_REGION_SLOTS_40_48_BASE, 4), ITEM_TEX2(ENTITY_REGION_SLOTS_40_48_BASE, 4), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x2D, 0x1B, 0x4C, ITEM_TEX1(ENTITY_REGION_SLOTS_40_48_BASE, 5), ITEM_TEX2(ENTITY_REGION_SLOTS_40_48_BASE, 5), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x2E, 0x1C, 0x4D, ITEM_TEX1(ENTITY_REGION_SLOTS_40_48_BASE, 6), ITEM_TEX2(ENTITY_REGION_SLOTS_40_48_BASE, 6), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x2F, 0x1D, 0x4E, ITEM_TEX1(ENTITY_REGION_SLOTS_40_48_BASE, 7), ITEM_TEX2(ENTITY_REGION_SLOTS_40_48_BASE, 7), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x30, 0x1E, 0x4F, ITEM_TEX1(ENTITY_REGION_SLOTS_40_48_BASE, 8), ITEM_TEX2(ENTITY_REGION_SLOTS_40_48_BASE, 8), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);

            // NPCs
            initializeEntity(0x15, 0x1F, 0x50, (u8*)ENTITY_SLOT_21_TEXTURE_1, (u8*)ENTITY_SLOT_21_TEXTURE_2, (u16*)ENTITY_SLOTS_21_28_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_21_28_ANIM_METADATA, (u32*)ENTITY_SLOTS_21_28_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_21_28_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x16, 0x20, 0x51, (u8*)ENTITY_SLOT_22_TEXTURE_1, (u8*)ENTITY_SLOT_22_TEXTURE_2, (u16*)ENTITY_SLOTS_21_28_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_21_28_ANIM_METADATA, (u32*)ENTITY_SLOTS_21_28_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_21_28_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x17, 0x21, 0x52, (u8*)ENTITY_SLOT_23_TEXTURE_1, (u8*)ENTITY_SLOT_23_TEXTURE_2, (u16*)ENTITY_SLOTS_21_28_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_21_28_ANIM_METADATA, (u32*)ENTITY_SLOTS_21_28_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_21_28_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x18, 0x22, 0x53, (u8*)ENTITY_SLOT_24_TEXTURE_1, (u8*)ENTITY_SLOT_24_TEXTURE_2, (u16*)ENTITY_SLOTS_21_28_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_21_28_ANIM_METADATA, (u32*)ENTITY_SLOTS_21_28_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_21_28_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x19, 0x23, 0x54, (u8*)ENTITY_SLOT_25_TEXTURE_1, (u8*)ENTITY_SLOT_25_TEXTURE_2, (u16*)ENTITY_SLOTS_21_28_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_21_28_ANIM_METADATA, (u32*)ENTITY_SLOTS_21_28_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_21_28_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x1A, 0x24, 0x55, (u8*)ENTITY_SLOT_26_TEXTURE_1, (u8*)ENTITY_SLOT_26_TEXTURE_2, (u16*)ENTITY_SLOTS_21_28_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_21_28_ANIM_METADATA, (u32*)ENTITY_SLOTS_21_28_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_21_28_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x1B, 0x25, 0x56, (u8*)ENTITY_SLOT_27_TEXTURE_1, (u8*)ENTITY_SLOT_27_TEXTURE_2, (u16*)ENTITY_SLOTS_21_28_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_21_28_ANIM_METADATA, (u32*)ENTITY_SLOTS_21_28_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_21_28_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x1C, 0x26, 0x57, (u8*)ENTITY_SLOT_28_TEXTURE_1, (u8*)ENTITY_SLOT_28_TEXTURE_2, (u16*)ENTITY_SLOTS_21_28_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_21_28_ANIM_METADATA, (u32*)ENTITY_SLOTS_21_28_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_21_28_TEXTURE_TO_PALETTE_LOOKUP);

            // Grown horse
            initializeEntity(0x26, 0x27, 0x58, (u8*)ENTITY_SLOT_38_TEXTURE_1, (u8*)ENTITY_SLOT_38_TEXTURE_2, (u16*)ENTITY_SLOT_38_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_38_ANIM_METADATA, (u32*)ENTITY_SLOT_38_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_38_TEXTURE_TO_PALETTE_LOOKUP);

            // Large spritesheet NPCs
            initializeEntity(0x1D, 0x28, 0x59, (u8*)ENTITY_SLOT_29_TEXTURE_1, (u8*)ENTITY_SLOT_29_TEXTURE_2, (u16*)ENTITY_SLOT_29_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_29_ANIM_METADATA, (u32*)ENTITY_SLOT_29_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_29_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x1E, 0x29, 0x5A, (u8*)ENTITY_SLOT_30_TEXTURE_1, (u8*)ENTITY_SLOT_30_TEXTURE_2, (u16*)ENTITY_SLOT_30_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_30_ANIM_METADATA, (u32*)ENTITY_SLOT_30_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_30_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x1F, 0x2A, 0x5B, (u8*)ENTITY_SLOT_31_TEXTURE_1, (u8*)ENTITY_SLOT_31_TEXTURE_2, (u16*)ENTITY_SLOT_31_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_31_ANIM_METADATA, (u32*)ENTITY_SLOT_31_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_31_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x20, 0x2B, 0x5C, (u8*)ENTITY_SLOT_32_TEXTURE_1, (u8*)ENTITY_SLOT_32_TEXTURE_2, (u16*)ENTITY_SLOT_32_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_32_ANIM_METADATA, (u32*)ENTITY_SLOT_32_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_32_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x21, 0x2C, 0x5D, (u8*)ENTITY_SLOT_33_TEXTURE_1, (u8*)ENTITY_SLOT_33_TEXTURE_2, (u16*)ENTITY_SLOT_33_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_33_ANIM_METADATA, (u32*)ENTITY_SLOT_33_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_33_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x22, 0x2D, 0x5E, (u8*)ENTITY_SLOT_34_TEXTURE_1, (u8*)ENTITY_SLOT_34_TEXTURE_2, (u16*)ENTITY_SLOT_34_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_34_ANIM_METADATA, (u32*)ENTITY_SLOT_34_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_34_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x23, 0x2E, 0x5F, (u8*)ENTITY_SLOT_35_TEXTURE_1, (u8*)ENTITY_SLOT_35_TEXTURE_2, (u16*)ENTITY_SLOT_35_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_35_ANIM_METADATA, (u32*)ENTITY_SLOT_35_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_35_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x24, 0x2F, 0x60, (u8*)ENTITY_SLOT_36_TEXTURE_1, (u8*)ENTITY_SLOT_36_TEXTURE_2, (u16*)ENTITY_SLOT_36_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_36_ANIM_METADATA, (u32*)ENTITY_SLOT_36_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_36_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x25, 0x30, 0x61, (u8*)ENTITY_SLOT_37_TEXTURE_1, (u8*)ENTITY_SLOT_37_TEXTURE_2, (u16*)ENTITY_SLOT_37_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_37_ANIM_METADATA, (u32*)ENTITY_SLOT_37_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_37_TEXTURE_TO_PALETTE_LOOKUP);

            break;
        
        // default, opening, demo cutscenes
        case 1:

            // Player
            initializeEntity(ENTITY_PLAYER, 0, 0x31, (u8*)PLAYER_TEXTURE_1_BUFFER, (u8*)PLAYER_TEXTURE_2_BUFFER, (u16*)PLAYER_PALETTE_BUFFER, (AnimationFrameMetadata*)PLAYER_ANIMATION_FRAME_METADATA_BUFFER, (u32*)PLAYER_SPRITESHEET_INDEX_BUFFER, (u32*)PLAYER_TEXTURE_TO_PALETTE_LOOKUP_BUFFER);

            // Dog
            initializeEntity(1, 1, 0x32, (u8*)ENTITY_REGION_SLOT_1_BASE, (u8*)(ENTITY_REGION_SLOT_1_BASE + DOG_SIZE_TEX), (u16*)ENTITY_SLOTS_1_20_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_1_20_ANIM_METADATA, (u32*)ENTITY_SLOTS_1_20_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_1_20_TEXTURE_TO_PALETTE_LOOKUP);

            // Chickens
            initializeEntity(2, 2, 0x33, CHICKEN_TEX1(ENTITY_REGION_CHICKEN_BASE, 0), CHICKEN_TEX2(ENTITY_REGION_CHICKEN_BASE, 0), (u16*)ENTITY_SLOTS_2_7_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_2_7_ANIM_METADATA, (u32*)ENTITY_SLOTS_2_7_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_2_7_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(3, 3, 0x34, CHICKEN_TEX1(ENTITY_REGION_CHICKEN_BASE, 1), CHICKEN_TEX2(ENTITY_REGION_CHICKEN_BASE, 1), (u16*)ENTITY_SLOTS_2_7_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_2_7_ANIM_METADATA, (u32*)ENTITY_SLOTS_2_7_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_2_7_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(4, 4, 0x35, CHICKEN_TEX1(ENTITY_REGION_CHICKEN_BASE, 2), CHICKEN_TEX2(ENTITY_REGION_CHICKEN_BASE, 2), (u16*)ENTITY_SLOTS_2_7_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_2_7_ANIM_METADATA, (u32*)ENTITY_SLOTS_2_7_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_2_7_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(5, 5, 0x36, CHICKEN_TEX1(ENTITY_REGION_CHICKEN_BASE, 3), CHICKEN_TEX2(ENTITY_REGION_CHICKEN_BASE, 3), (u16*)ENTITY_SLOTS_2_7_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_2_7_ANIM_METADATA, (u32*)ENTITY_SLOTS_2_7_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_2_7_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(6, 6, 0x37, CHICKEN_TEX1(ENTITY_REGION_CHICKEN_BASE, 4), CHICKEN_TEX2(ENTITY_REGION_CHICKEN_BASE, 4), (u16*)ENTITY_SLOTS_2_7_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_2_7_ANIM_METADATA, (u32*)ENTITY_SLOTS_2_7_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_2_7_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(7, 7, 0x38, CHICKEN_TEX1(ENTITY_REGION_CHICKEN_BASE, 5), CHICKEN_TEX2(ENTITY_REGION_CHICKEN_BASE, 5), (u16*)ENTITY_SLOTS_2_7_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_2_7_ANIM_METADATA, (u32*)ENTITY_SLOTS_2_7_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_2_7_TEXTURE_TO_PALETTE_LOOKUP);

            // Chicks
            initializeEntity(8, 8, 0x39, CHICK_TEX1(ENTITY_REGION_CHICK_BASE, 0), CHICK_TEX2(ENTITY_REGION_CHICK_BASE, 0), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(9, 9, 0x3A, CHICK_TEX1(ENTITY_REGION_CHICK_BASE, 1), CHICK_TEX2(ENTITY_REGION_CHICK_BASE, 1), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0xA, 0xA, 0x3B, CHICK_TEX1(ENTITY_REGION_CHICK_BASE, 2), CHICK_TEX2(ENTITY_REGION_CHICK_BASE, 2), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0xB, 0xB, 0x3C, CHICK_TEX1(ENTITY_REGION_CHICK_BASE, 3), CHICK_TEX2(ENTITY_REGION_CHICK_BASE, 3), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0xC, 0xC, 0x3D, CHICK_TEX1(ENTITY_REGION_CHICK_BASE, 4), CHICK_TEX2(ENTITY_REGION_CHICK_BASE, 4), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0xD, 0xD, 0x3E, CHICK_TEX1(ENTITY_REGION_CHICK_BASE, 5), CHICK_TEX2(ENTITY_REGION_CHICK_BASE, 5), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);

            // Cows
            initializeEntity(0xE, 0xE, 0x3F, (u8*)ENTITY_SLOT_14_TEXTURE_1, (u8*)ENTITY_SLOT_14_TEXTURE_2, (u16*)ENTITY_SLOT_14_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_14_ANIM_METADATA, (u32*)ENTITY_SLOT_14_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_14_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0xF, 0xF, 0x40, (u8*)ENTITY_SLOT_15_TEXTURE_1, (u8*)ENTITY_SLOT_15_TEXTURE_2, (u16*)ENTITY_SLOT_15_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_15_ANIM_METADATA, (u32*)ENTITY_SLOT_15_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_15_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x10, 0x10, 0x41, (u8*)ENTITY_SLOT_16_TEXTURE_1, (u8*)ENTITY_SLOT_16_TEXTURE_2, (u16*)ENTITY_SLOT_16_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_16_ANIM_METADATA, (u32*)ENTITY_SLOT_16_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_16_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x11, 0x11, 0x42, (u8*)ENTITY_SLOT_17_TEXTURE_1, (u8*)ENTITY_SLOT_17_TEXTURE_2, (u16*)ENTITY_SLOT_17_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_17_ANIM_METADATA, (u32*)ENTITY_SLOT_17_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_17_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x12, 0x12, 0x43, (u8*)ENTITY_SLOT_18_TEXTURE_1, (u8*)ENTITY_SLOT_18_TEXTURE_2, (u16*)ENTITY_SLOT_18_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_18_ANIM_METADATA, (u32*)ENTITY_SLOT_18_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_18_TEXTURE_TO_PALETTE_LOOKUP);

            // Pony
            initializeEntity(0x13, 0x13, 0x44, (u8*)ENTITY_SLOT_19_TEXTURE_1, (u8*)ENTITY_SLOT_19_TEXTURE_2, (u16*)ENTITY_SLOTS_21_28_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_21_28_ANIM_METADATA, (u32*)ENTITY_SLOTS_21_28_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_21_28_TEXTURE_TO_PALETTE_LOOKUP);

            initializeEntity(0x14, 0x14, 0x45, (u8*)ENTITY_SLOT_20_TEXTURE_1, (u8*)ENTITY_SLOT_20_TEXTURE_2, (u16*)ENTITY_SLOTS_1_20_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_1_20_ANIM_METADATA, (u32*)ENTITY_SLOTS_1_20_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_1_20_TEXTURE_TO_PALETTE_LOOKUP);

            initializeEntity(0x27, 0x15, 0x46, (u8*)ENTITY_REGION_SLOT_39_BASE, (u8*)(ENTITY_REGION_SLOT_39_BASE + ITEM_SIZE_TEX), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);

            // Items
            initializeEntity(0x28, 0x16, 0x47, ITEM_TEX1(ENTITY_REGION_SLOTS_40_48_BASE, 0), ITEM_TEX2(ENTITY_REGION_SLOTS_40_48_BASE, 0), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x29, 0x17, 0x48, ITEM_TEX1(ENTITY_REGION_SLOTS_40_48_BASE, 1), ITEM_TEX2(ENTITY_REGION_SLOTS_40_48_BASE, 1), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x2A, 0x18, 0x49, ITEM_TEX1(ENTITY_REGION_SLOTS_40_48_BASE, 2), ITEM_TEX2(ENTITY_REGION_SLOTS_40_48_BASE, 2), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x2B, 0x19, 0x4A, ITEM_TEX1(ENTITY_REGION_SLOTS_40_48_BASE, 3), ITEM_TEX2(ENTITY_REGION_SLOTS_40_48_BASE, 3), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x2C, 0x1A, 0x4B, ITEM_TEX1(ENTITY_REGION_SLOTS_40_48_BASE, 4), ITEM_TEX2(ENTITY_REGION_SLOTS_40_48_BASE, 4), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x2D, 0x1B, 0x4C, ITEM_TEX1(ENTITY_REGION_SLOTS_40_48_BASE, 5), ITEM_TEX2(ENTITY_REGION_SLOTS_40_48_BASE, 5), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x2E, 0x1C, 0x4D, ITEM_TEX1(ENTITY_REGION_SLOTS_40_48_BASE, 6), ITEM_TEX2(ENTITY_REGION_SLOTS_40_48_BASE, 6), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x2F, 0x1D, 0x4E, ITEM_TEX1(ENTITY_REGION_SLOTS_40_48_BASE, 7), ITEM_TEX2(ENTITY_REGION_SLOTS_40_48_BASE, 7), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x30, 0x1E, 0x4F, ITEM_TEX1(ENTITY_REGION_SLOTS_40_48_BASE, 8), ITEM_TEX2(ENTITY_REGION_SLOTS_40_48_BASE, 8), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);

            // NPCs
            initializeEntity(0x15, 0x1F, 0x50, (u8*)ENTITY_SLOT_21_CUTSCENE_TEXTURE_1, (u8*)ENTITY_SLOT_21_CUTSCENE_TEXTURE_2, (u16*)ENTITY_SLOT_21_CUTSCENE_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_21_CUTSCENE_ANIM_METADATA, (u32*)ENTITY_SLOT_21_CUTSCENE_SPRITESHEET, (u32*)ENTITY_SLOT_21_CUTSCENE_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x16, 0x20, 0x51, (u8*)ENTITY_SLOT_22_CUTSCENE_TEXTURE_1, (u8*)ENTITY_SLOT_22_CUTSCENE_TEXTURE_2, (u16*)ENTITY_SLOT_22_CUTSCENE_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_22_CUTSCENE_ANIM_METADATA, (u32*)ENTITY_SLOT_22_CUTSCENE_SPRITESHEET, (u32*)ENTITY_SLOT_22_CUTSCENE_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x17, 0x21, 0x52, (u8*)ENTITY_SLOT_23_CUTSCENE_TEXTURE_1, (u8*)ENTITY_SLOT_23_CUTSCENE_TEXTURE_2, (u16*)ENTITY_SLOT_23_CUTSCENE_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_23_CUTSCENE_ANIM_METADATA, (u32*)ENTITY_SLOT_23_CUTSCENE_SPRITESHEET, (u32*)ENTITY_SLOT_23_CUTSCENE_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x18, 0x22, 0x53, (u8*)ENTITY_SLOT_24_CUTSCENE_TEXTURE_1, (u8*)ENTITY_SLOT_24_CUTSCENE_TEXTURE_2, (u16*)ENTITY_SLOT_24_CUTSCENE_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_24_CUTSCENE_ANIM_METADATA, (u32*)ENTITY_SLOT_24_CUTSCENE_SPRITESHEET, (u32*)ENTITY_SLOT_24_CUTSCENE_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x19, 0x23, 0x54, (u8*)ENTITY_SLOT_25_CUTSCENE_TEXTURE_1, (u8*)ENTITY_SLOT_25_CUTSCENE_TEXTURE_2, (u16*)ENTITY_SLOT_25_CUTSCENE_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_25_CUTSCENE_ANIM_METADATA, (u32*)ENTITY_SLOT_25_CUTSCENE_SPRITESHEET, (u32*)ENTITY_SLOT_25_CUTSCENE_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x1A, 0x24, 0x55, (u8*)ENTITY_SLOT_26_CUTSCENE_TEXTURE_1, (u8*)ENTITY_SLOT_26_CUTSCENE_TEXTURE_2, (u16*)ENTITY_SLOT_26_CUTSCENE_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_26_CUTSCENE_ANIM_METADATA, (u32*)ENTITY_SLOT_26_CUTSCENE_SPRITESHEET, (u32*)ENTITY_SLOT_26_CUTSCENE_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x1B, 0x25, 0x56, (u8*)ENTITY_SLOT_27_CUTSCENE_TEXTURE_1, (u8*)ENTITY_SLOT_27_CUTSCENE_TEXTURE_2, (u16*)ENTITY_SLOT_27_CUTSCENE_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_27_CUTSCENE_ANIM_METADATA, (u32*)ENTITY_SLOT_27_CUTSCENE_SPRITESHEET, (u32*)ENTITY_SLOT_27_CUTSCENE_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x1C, 0x26, 0x57, (u8*)ENTITY_SLOT_28_CUTSCENE_TEXTURE_1, (u8*)ENTITY_SLOT_28_CUTSCENE_TEXTURE_2, (u16*)ENTITY_SLOT_28_CUTSCENE_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_28_CUTSCENE_ANIM_METADATA, (u32*)ENTITY_SLOT_28_CUTSCENE_SPRITESHEET, (u32*)ENTITY_SLOT_28_CUTSCENE_TEXTURE_TO_PALETTE_LOOKUP);

            // Large spritesheet NPCs
            initializeEntity(0x1D, 0x28, 0x59, (u8*)ENTITY_SLOT_29_TEXTURE_1, (u8*)ENTITY_SLOT_29_TEXTURE_2, (u16*)ENTITY_SLOT_29_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_29_ANIM_METADATA, (u32*)ENTITY_SLOT_29_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_29_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x1E, 0x29, 0x5A, (u8*)ENTITY_SLOT_30_TEXTURE_1, (u8*)ENTITY_SLOT_30_TEXTURE_2, (u16*)ENTITY_SLOT_30_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_30_ANIM_METADATA, (u32*)ENTITY_SLOT_30_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_30_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x1F, 0x2A, 0x5B, (u8*)ENTITY_SLOT_31_TEXTURE_1, (u8*)ENTITY_SLOT_31_TEXTURE_2, (u16*)ENTITY_SLOT_31_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_31_ANIM_METADATA, (u32*)ENTITY_SLOT_31_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_31_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x20, 0x2B, 0x5C, (u8*)ENTITY_SLOT_32_TEXTURE_1, (u8*)ENTITY_SLOT_32_TEXTURE_2, (u16*)ENTITY_SLOT_32_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_32_ANIM_METADATA, (u32*)ENTITY_SLOT_32_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_32_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x21, 0x2C, 0x5D, (u8*)ENTITY_SLOT_33_TEXTURE_1, (u8*)ENTITY_SLOT_33_TEXTURE_2, (u16*)ENTITY_SLOT_33_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_33_ANIM_METADATA, (u32*)ENTITY_SLOT_33_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_33_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x22, 0x2D, 0x5E, (u8*)ENTITY_SLOT_34_TEXTURE_1, (u8*)ENTITY_SLOT_34_TEXTURE_2, (u16*)ENTITY_SLOT_34_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_34_ANIM_METADATA, (u32*)ENTITY_SLOT_34_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_34_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x23, 0x2E, 0x5F, (u8*)ENTITY_SLOT_35_TEXTURE_1, (u8*)ENTITY_SLOT_35_TEXTURE_2, (u16*)ENTITY_SLOT_35_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_35_ANIM_METADATA, (u32*)ENTITY_SLOT_35_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_35_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x24, 0x2F, 0x60, (u8*)ENTITY_SLOT_36_TEXTURE_1, (u8*)ENTITY_SLOT_36_TEXTURE_2, (u16*)ENTITY_SLOT_36_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_36_ANIM_METADATA, (u32*)ENTITY_SLOT_36_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_36_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x25, 0x30, 0x61, (u8*)ENTITY_SLOT_37_TEXTURE_1, (u8*)ENTITY_SLOT_37_TEXTURE_2, (u16*)ENTITY_SLOT_37_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_37_ANIM_METADATA, (u32*)ENTITY_SLOT_37_SPRITESHEET_INDEX, (u32*)ENTITY_SLOT_37_TEXTURE_TO_PALETTE_LOOKUP);

            break;
        
        // new year's festival, vegetable festival, spirit festival
        case 2:

            // player
            initializeEntity(ENTITY_PLAYER, 0, 0x31, (u8*)PLAYER_TEXTURE_1_BUFFER, (u8*)PLAYER_TEXTURE_2_BUFFER, (u16*)PLAYER_PALETTE_BUFFER, (AnimationFrameMetadata*)PLAYER_ANIMATION_FRAME_METADATA_BUFFER, (u32*)PLAYER_SPRITESHEET_INDEX_BUFFER, (u32*)PLAYER_TEXTURE_TO_PALETTE_LOOKUP_BUFFER);

            // item
            initializeEntity(0x27, 0x15, 0x46, (u8*)ENTITY_REGION_SLOT_39_BASE, (u8*)(ENTITY_REGION_SLOT_39_BASE + ITEM_SIZE_TEX), (u16*)ENTITY_SLOTS_8_13_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_8_13_ANIM_METADATA, (u32*)ENTITY_SLOTS_8_13_SPRITESHEET_INDEX, (u32*)ENTITY_SLOTS_8_13_TEXTURE_TO_PALETTE_LOOKUP);

            // Festival NPCs
            initializeEntity(1, 1, 0x2C, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_1_BASE, 0), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_1_BASE, 0), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_1_BASE, 0), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_1_BASE, 0), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_1_BASE, 0), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_1_BASE, 0));
            initializeEntity(2, 2, 0x2D, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_1_BASE, 1), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_1_BASE, 1), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_1_BASE, 1), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_1_BASE, 1), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_1_BASE, 1), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_1_BASE, 1));
            initializeEntity(3, 3, 0x2E, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_1_BASE, 2), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_1_BASE, 2), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_1_BASE, 2), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_1_BASE, 2), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_1_BASE, 2), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_1_BASE, 2));
            initializeEntity(4, 4, 0x2F, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_1_BASE, 3), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_1_BASE, 3), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_1_BASE, 3), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_1_BASE, 3), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_1_BASE, 3), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_1_BASE, 3));
            initializeEntity(5, 5, 0x30, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_1_BASE, 4), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_1_BASE, 4), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_1_BASE, 4), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_1_BASE, 4), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_1_BASE, 4), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_1_BASE, 4));
            initializeEntity(6, 6, 0x32, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_1_BASE, 5), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_1_BASE, 5), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_1_BASE, 5), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_1_BASE, 5), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_1_BASE, 5), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_1_BASE, 5));
            initializeEntity(7, 7, 0x33, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_1_BASE, 6), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_1_BASE, 6), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_1_BASE, 6), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_1_BASE, 6), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_1_BASE, 6), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_1_BASE, 6));
            initializeEntity(8, 8, 0x34, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_1_BASE, 7), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_1_BASE, 7), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_1_BASE, 7), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_1_BASE, 7), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_1_BASE, 7), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_1_BASE, 7));
   
            // Festival NPCs
            initializeEntity(9, 9, 0x35, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_2_BASE, 0), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_2_BASE, 0), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_2_BASE, 0), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_2_BASE, 0), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_2_BASE, 0), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_2_BASE, 0));
            initializeEntity(0xA, 0xA, 0x36, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_2_BASE, 1), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_2_BASE, 1), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_2_BASE, 1), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_2_BASE, 1), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_2_BASE, 1), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_2_BASE, 1));
            initializeEntity(0xB, 0xB, 0x37, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_2_BASE, 2), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_2_BASE, 2), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_2_BASE, 2), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_2_BASE, 2), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_2_BASE, 2), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_2_BASE, 2));
            initializeEntity(0xC, 0xC, 0x38, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_2_BASE, 3), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_2_BASE, 3), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_2_BASE, 3), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_2_BASE, 3), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_2_BASE, 3), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_2_BASE, 3));
            initializeEntity(0xD, 0xD, 0x39, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_2_BASE, 4), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_2_BASE, 4), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_2_BASE, 4), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_2_BASE, 4), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_2_BASE, 4), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_2_BASE, 4));
            initializeEntity(0xE, 0xE, 0x3A, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_2_BASE, 5), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_2_BASE, 5), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_2_BASE, 5), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_2_BASE, 5), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_2_BASE, 5), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_2_BASE, 5));
            initializeEntity(0xF, 0xF, 0x3B, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_2_BASE, 6), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_2_BASE, 6), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_2_BASE, 6), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_2_BASE, 6), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_2_BASE, 6), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_2_BASE, 6));
            initializeEntity(0x10, 0x10, 0x3C, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_2_BASE, 7), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_2_BASE, 7), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_2_BASE, 7), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_2_BASE, 7), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_2_BASE, 7), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_2_BASE, 7));
            initializeEntity(0x11, 0x11, 0x3D, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_2_BASE, 8), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_2_BASE, 8), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_2_BASE, 8), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_2_BASE, 8), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_2_BASE, 8), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_2_BASE, 8));
            initializeEntity(0x12, 0x12, 0x3E, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_2_BASE, 9), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_2_BASE, 9), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_2_BASE, 9), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_2_BASE, 9), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_2_BASE, 9), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_2_BASE, 9));
            initializeEntity(0x13, 0x13, 0x3F, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_2_BASE, 10), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_2_BASE, 10), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_2_BASE, 10), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_2_BASE, 10), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_2_BASE, 10), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_2_BASE, 10));
            initializeEntity(0x14, 0x14, 0x40, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_2_BASE, 11), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_2_BASE, 11), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_2_BASE, 11), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_2_BASE, 11), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_2_BASE, 11), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_2_BASE, 11));
 
            // Festival small sprites (shared metadata)
            initializeEntity(0x16, 0x16, 0x41, SMALL_SPRITE_TEX1(ENTITY_REGION_SMALL_SPRITE_BASE, 0), SMALL_SPRITE_TEX2(ENTITY_REGION_SMALL_SPRITE_BASE, 0), (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x17, 0x17, 0x42, SMALL_SPRITE_TEX1(ENTITY_REGION_SMALL_SPRITE_BASE, 1), SMALL_SPRITE_TEX2(ENTITY_REGION_SMALL_SPRITE_BASE, 1), (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x18, 0x18, 0x43, SMALL_SPRITE_TEX1(ENTITY_REGION_SMALL_SPRITE_BASE, 2), SMALL_SPRITE_TEX2(ENTITY_REGION_SMALL_SPRITE_BASE, 2), (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x19, 0x19, 0x44, SMALL_SPRITE_TEX1(ENTITY_REGION_SMALL_SPRITE_BASE, 3), SMALL_SPRITE_TEX2(ENTITY_REGION_SMALL_SPRITE_BASE, 3), (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x1A, 0x1A, 0x45, SMALL_SPRITE_TEX1(ENTITY_REGION_SMALL_SPRITE_BASE, 4), SMALL_SPRITE_TEX2(ENTITY_REGION_SMALL_SPRITE_BASE, 4), (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x1B, 0x1B, 0x47, SMALL_SPRITE_TEX1(ENTITY_REGION_SMALL_SPRITE_BASE, 5), SMALL_SPRITE_TEX2(ENTITY_REGION_SMALL_SPRITE_BASE, 5), (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
 
            if (gCutsceneIndex == SEA_FESTIVAL) {
                initializeEntity(0x1E, 0x1E, 0x4A, SMALL_SPRITE_TEX1(ENTITY_REGION_SMALL_SPRITE_BASE, 7), SMALL_SPRITE_TEX1(ENTITY_REGION_SMALL_SPRITE_BASE, 8), (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
            } else {
                
                initializeEntity(0x1C, 0x1C, 0x48, SMALL_SPRITE_TEX1(ENTITY_REGION_SMALL_SPRITE_BASE, 6), SMALL_SPRITE_TEX2(ENTITY_REGION_SMALL_SPRITE_BASE, 6), (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
                initializeEntity(0x1D, 0x1D, 0x49, SMALL_SPRITE_TEX1(ENTITY_REGION_SMALL_SPRITE_BASE, 7), SMALL_SPRITE_TEX2(ENTITY_REGION_SMALL_SPRITE_BASE, 7), (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
                initializeEntity(0x1E, 0x1E, 0x4A, SMALL_SPRITE_TEX1(ENTITY_REGION_SMALL_SPRITE_BASE, 8), SMALL_SPRITE_TEX2(ENTITY_REGION_SMALL_SPRITE_BASE, 8), (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
                initializeEntity(0x1F, 0x1F, 0x4B, SMALL_SPRITE_TEX1(ENTITY_REGION_SMALL_SPRITE_BASE, 9), SMALL_SPRITE_TEX2(ENTITY_REGION_SMALL_SPRITE_BASE, 9), (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
                initializeEntity(0x20, 0x20, 0x4C, SMALL_SPRITE_TEX1(ENTITY_REGION_SMALL_SPRITE_BASE, 10), SMALL_SPRITE_TEX2(ENTITY_REGION_SMALL_SPRITE_BASE, 10), (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
                initializeEntity(0x21, 0x21, 0x4D, SMALL_SPRITE_TEX1(ENTITY_REGION_SMALL_SPRITE_BASE, 11), SMALL_SPRITE_TEX2(ENTITY_REGION_SMALL_SPRITE_BASE, 11), (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
                initializeEntity(0x22, 0x22, 0x4E, SMALL_SPRITE_TEX1(ENTITY_REGION_SMALL_SPRITE_BASE, 12), SMALL_SPRITE_TEX2(ENTITY_REGION_SMALL_SPRITE_BASE, 12), (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
                initializeEntity(0x23, 0x23, 0x4F, SMALL_SPRITE_TEX1(ENTITY_REGION_SMALL_SPRITE_BASE, 13), SMALL_SPRITE_TEX2(ENTITY_REGION_SMALL_SPRITE_BASE, 13), (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
                initializeEntity(0x24, 0x24, 0x50, SMALL_SPRITE_TEX1(ENTITY_REGION_SMALL_SPRITE_BASE, 14), SMALL_SPRITE_TEX2(ENTITY_REGION_SMALL_SPRITE_BASE, 14), (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
                initializeEntity(0x25, 0x25, 0x51, SMALL_SPRITE_TEX1(ENTITY_REGION_SMALL_SPRITE_BASE, 15), SMALL_SPRITE_TEX2(ENTITY_REGION_SMALL_SPRITE_BASE, 15), (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
                initializeEntity(0x26, 0x27, 0x52, SMALL_SPRITE_TEX1(ENTITY_REGION_SMALL_SPRITE_BASE, 16), SMALL_SPRITE_TEX2(ENTITY_REGION_SMALL_SPRITE_BASE, 16), (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
                
                // Slots 0x28-0x2B (non-standard layout, overlaps with slots 35-37 region)
                initializeEntity(0x28, 0x28, 0x53, (u8*)ENTITY_SLOT_FESTIVAL_40_TEXTURE_1, (u8*)ENTITY_SLOT_FESTIVAL_40_TEXTURE_2, (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
                initializeEntity(0x29, 0x29, 0x54, (u8*)ENTITY_SLOT_FESTIVAL_41_TEXTURE_1, (u8*)ENTITY_SLOT_FESTIVAL_41_TEXTURE_2, (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
                initializeEntity(0x2A, 0x2A, 0x55, (u8*)ENTITY_SLOT_FESTIVAL_42_TEXTURE_1, (u8*)ENTITY_SLOT_FESTIVAL_42_TEXTURE_2, (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
                initializeEntity(0x2B, 0x2B, 0x56, (u8*)ENTITY_SLOT_FESTIVAL_43_TEXTURE_1, (u8*)ENTITY_SLOT_FESTIVAL_43_TEXTURE_2, (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
                // Slot 0x2C (large cutscene entity with unique layout)
                initializeEntity(0x2C, 0x57, 0x58, (u8*)ENTITY_SLOT_FESTIVAL_44_TEXTURE_1, (u8*)ENTITY_SLOT_FESTIVAL_44_TEXTURE_2, (u16*)ENTITY_SLOT_FESTIVAL_44_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOT_FESTIVAL_44_ANIM_METADATA, (u32*)ENTITY_SLOT_FESTIVAL_44_SPRITESHEET, (u32*)ENTITY_SLOT_FESTIVAL_44_TEXTURE_TO_PALETTE_LOOKUP);
            
            }

            break;
        
        // cow festival
        case 3:

            // Player
            initializeEntity(ENTITY_PLAYER, 0, 0x31, (u8*)PLAYER_TEXTURE_1_BUFFER, (u8*)PLAYER_TEXTURE_2_BUFFER, (u16*)PLAYER_PALETTE_BUFFER, (AnimationFrameMetadata*)PLAYER_ANIMATION_FRAME_METADATA_BUFFER, (u32*)PLAYER_SPRITESHEET_INDEX_BUFFER, (u32*)PLAYER_TEXTURE_TO_PALETTE_LOOKUP_BUFFER);

            // Slots 6-10 (Cow festival large NPCs, first group - each has unique metadata)
            initializeEntity(6, 6, 0x32, NPC_LARGE_TEX1(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 0), NPC_LARGE_TEX2(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 0), NPC_LARGE_PALETTE(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 0), NPC_LARGE_ANIM(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 0), NPC_LARGE_SPRITESHEET(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 0), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 0));
            initializeEntity(7, 7, 0x33, NPC_LARGE_TEX1(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 1), NPC_LARGE_TEX2(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 1), NPC_LARGE_PALETTE(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 1), NPC_LARGE_ANIM(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 1), NPC_LARGE_SPRITESHEET(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 1), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 1));
            initializeEntity(8, 8, 0x34, NPC_LARGE_TEX1(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 2), NPC_LARGE_TEX2(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 2), NPC_LARGE_PALETTE(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 2), NPC_LARGE_ANIM(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 2), NPC_LARGE_SPRITESHEET(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 2), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 2));
            initializeEntity(9, 9, 0x35, NPC_LARGE_TEX1(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 3), NPC_LARGE_TEX2(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 3), NPC_LARGE_PALETTE(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 3), NPC_LARGE_ANIM(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 3), NPC_LARGE_SPRITESHEET(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 3), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 3));
            initializeEntity(0xA, 0xA, 0x36, NPC_LARGE_TEX1(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 4), NPC_LARGE_TEX2(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 4), NPC_LARGE_PALETTE(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 4), NPC_LARGE_ANIM(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 4), NPC_LARGE_SPRITESHEET(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 4), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_COW_FESTIVAL_NPC_BASE, 4));

            // Slots 11-21 (Cow festival large NPCs, second group - each has unique metadata)
            initializeEntity(0xB, 0xB, 0x37, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_2_BASE, 0), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_2_BASE, 0), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_2_BASE, 0), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_2_BASE, 0), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_2_BASE, 0), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_2_BASE, 0));
            initializeEntity(0xC, 0xC, 0x38, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_2_BASE, 1), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_2_BASE, 1), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_2_BASE, 1), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_2_BASE, 1), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_2_BASE, 1), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_2_BASE, 1));
            initializeEntity(0xD, 0xD, 0x39, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_2_BASE, 2), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_2_BASE, 2), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_2_BASE, 2), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_2_BASE, 2), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_2_BASE, 2), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_2_BASE, 2));
            initializeEntity(0xE, 0xE, 0x3A, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_2_BASE, 3), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_2_BASE, 3), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_2_BASE, 3), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_2_BASE, 3), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_2_BASE, 3), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_2_BASE, 3));
            initializeEntity(0xF, 0xF, 0x3B, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_2_BASE, 4), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_2_BASE, 4), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_2_BASE, 4), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_2_BASE, 4), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_2_BASE, 4), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_2_BASE, 4));
            initializeEntity(0x10, 0x10, 0x3C, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_2_BASE, 5), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_2_BASE, 5), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_2_BASE, 5), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_2_BASE, 5), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_2_BASE, 5), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_2_BASE, 5));
            initializeEntity(0x11, 0x11, 0x3D, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_2_BASE, 6), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_2_BASE, 6), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_2_BASE, 6), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_2_BASE, 6), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_2_BASE, 6), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_2_BASE, 6));
            initializeEntity(0x12, 0x12, 0x3E, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_2_BASE, 7), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_2_BASE, 7), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_2_BASE, 7), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_2_BASE, 7), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_2_BASE, 7), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_2_BASE, 7));
            initializeEntity(0x13, 0x13, 0x3F, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_2_BASE, 8), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_2_BASE, 8), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_2_BASE, 8), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_2_BASE, 8), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_2_BASE, 8), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_2_BASE, 8));
            initializeEntity(0x14, 0x14, 0x40, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_2_BASE, 9), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_2_BASE, 9), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_2_BASE, 9), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_2_BASE, 9), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_2_BASE, 9), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_2_BASE, 9));
            initializeEntity(0x15, 0x15, 0x59, NPC_LARGE_TEX1(ENTITY_REGION_NPC_LARGE_2_BASE, 10), NPC_LARGE_TEX2(ENTITY_REGION_NPC_LARGE_2_BASE, 10), NPC_LARGE_PALETTE(ENTITY_REGION_NPC_LARGE_2_BASE, 10), NPC_LARGE_ANIM(ENTITY_REGION_NPC_LARGE_2_BASE, 10), NPC_LARGE_SPRITESHEET(ENTITY_REGION_NPC_LARGE_2_BASE, 10), NPC_LARGE_TEX_LOOKUP(ENTITY_REGION_NPC_LARGE_2_BASE, 10));

            // Slots 1-5 (Cow festival participants - shared metadata)
            initializeEntity(1, 1, 0x2C, STANDARD_NPC_TEX1(ENTITY_REGION_SLOT_1_BASE, 0), STANDARD_NPC_TEX2(ENTITY_REGION_SLOT_1_BASE, 0), (u16*)ENTITY_SLOTS_COW_FESTIVAL_1_5_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_COW_FESTIVAL_1_5_ANIM_METADATA, (u32*)ENTITY_SLOTS_COW_FESTIVAL_1_5_SPRITESHEET, (u32*)ENTITY_SLOTS_COW_FESTIVAL_1_5_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(2, 2, 0x2D, STANDARD_NPC_TEX1(ENTITY_REGION_SLOT_1_BASE, 1), STANDARD_NPC_TEX2(ENTITY_REGION_SLOT_1_BASE, 1), (u16*)ENTITY_SLOTS_COW_FESTIVAL_1_5_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_COW_FESTIVAL_1_5_ANIM_METADATA, (u32*)ENTITY_SLOTS_COW_FESTIVAL_1_5_SPRITESHEET, (u32*)ENTITY_SLOTS_COW_FESTIVAL_1_5_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(3, 3, 0x2E, STANDARD_NPC_TEX1(ENTITY_REGION_SLOT_1_BASE, 2), STANDARD_NPC_TEX2(ENTITY_REGION_SLOT_1_BASE, 2), (u16*)ENTITY_SLOTS_COW_FESTIVAL_1_5_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_COW_FESTIVAL_1_5_ANIM_METADATA, (u32*)ENTITY_SLOTS_COW_FESTIVAL_1_5_SPRITESHEET, (u32*)ENTITY_SLOTS_COW_FESTIVAL_1_5_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(4, 4, 0x2F, STANDARD_NPC_TEX1(ENTITY_REGION_SLOT_1_BASE, 3), STANDARD_NPC_TEX2(ENTITY_REGION_SLOT_1_BASE, 3), (u16*)ENTITY_SLOTS_COW_FESTIVAL_1_5_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_COW_FESTIVAL_1_5_ANIM_METADATA, (u32*)ENTITY_SLOTS_COW_FESTIVAL_1_5_SPRITESHEET, (u32*)ENTITY_SLOTS_COW_FESTIVAL_1_5_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(5, 5, 0x30, STANDARD_NPC_TEX1(ENTITY_REGION_SLOT_1_BASE, 4), STANDARD_NPC_TEX2(ENTITY_REGION_SLOT_1_BASE, 4), (u16*)ENTITY_SLOTS_COW_FESTIVAL_1_5_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_COW_FESTIVAL_1_5_ANIM_METADATA, (u32*)ENTITY_SLOTS_COW_FESTIVAL_1_5_SPRITESHEET, (u32*)ENTITY_SLOTS_COW_FESTIVAL_1_5_TEXTURE_TO_PALETTE_LOOKUP);

            // Slots 22-30 (Festival small sprites - shared metadata)
            initializeEntity(0x16, 0x16, 0x41, SMALL_SPRITE_TEX1(ENTITY_REGION_SMALL_SPRITE_BASE, 0), SMALL_SPRITE_TEX2(ENTITY_REGION_SMALL_SPRITE_BASE, 0), (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x17, 0x17, 0x42, SMALL_SPRITE_TEX1(ENTITY_REGION_SMALL_SPRITE_BASE, 1), SMALL_SPRITE_TEX2(ENTITY_REGION_SMALL_SPRITE_BASE, 1), (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x18, 0x18, 0x43, SMALL_SPRITE_TEX1(ENTITY_REGION_SMALL_SPRITE_BASE, 2), SMALL_SPRITE_TEX2(ENTITY_REGION_SMALL_SPRITE_BASE, 2), (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x19, 0x19, 0x44, SMALL_SPRITE_TEX1(ENTITY_REGION_SMALL_SPRITE_BASE, 3), SMALL_SPRITE_TEX2(ENTITY_REGION_SMALL_SPRITE_BASE, 3), (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x1A, 0x1A, 0x45, SMALL_SPRITE_TEX1(ENTITY_REGION_SMALL_SPRITE_BASE, 4), SMALL_SPRITE_TEX2(ENTITY_REGION_SMALL_SPRITE_BASE, 4), (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x1B, 0x1B, 0x47, SMALL_SPRITE_TEX1(ENTITY_REGION_SMALL_SPRITE_BASE, 5), SMALL_SPRITE_TEX2(ENTITY_REGION_SMALL_SPRITE_BASE, 5), (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x1C, 0x1C, 0x48, SMALL_SPRITE_TEX1(ENTITY_REGION_SMALL_SPRITE_BASE, 6), SMALL_SPRITE_TEX2(ENTITY_REGION_SMALL_SPRITE_BASE, 6), (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x1D, 0x1D, 0x49, SMALL_SPRITE_TEX1(ENTITY_REGION_SMALL_SPRITE_BASE, 7), SMALL_SPRITE_TEX2(ENTITY_REGION_SMALL_SPRITE_BASE, 7), (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);
            initializeEntity(0x1E, 0x1E, 0x4A, SMALL_SPRITE_TEX1(ENTITY_REGION_SMALL_SPRITE_BASE, 8), SMALL_SPRITE_TEX2(ENTITY_REGION_SMALL_SPRITE_BASE, 8), (u16*)ENTITY_SLOTS_FESTIVAL_PALETTE, (AnimationFrameMetadata*)ENTITY_SLOTS_FESTIVAL_ANIM_METADATA, (u32*)ENTITY_SLOTS_FESTIVAL_SPRITESHEET, (u32*)ENTITY_SLOTS_FESTIVAL_TEXTURE_TO_PALETTE_LOOKUP);

            break;

    }
    
}

//INCLUDE_ASM("asm/nonmatchings/game/transition", resumeGameplay);

void resumeGameplay(void) {
    togglePauseEntities();
    resumeCutsceneExecutors();
    setEntityMapSpaceIndependent(ENTITY_PLAYER, TRUE);
}

//INCLUDE_ASM("asm/nonmatchings/game/transition", pauseGameplay);

void inline pauseGameplay(void) {
    pauseEntities();
    pauseAllCutsceneExecutors();
    setEntityMapSpaceIndependent(ENTITY_PLAYER, FALSE);
}
 
//INCLUDE_ASM("asm/nonmatchings/game/transition", exitOverlayScreen);

void exitOverlayScreen(void) {

    loadAllPendingEntities();
    resumeCutsceneExecutors();
    setEntityMapSpaceIndependent(ENTITY_PLAYER, TRUE);
    func_80065AA0();

    dmaMapAssets(0, gMapWithSeasonIndex);
    
    setupLevelMap(gBaseMapIndex);
    //setupLevelMap(currentMapContext.currentMapIndex);
    
    setPlayerAction(0xFE, 0);
    updatePlayerAction();
    
    setMainLoopCallbackFunctionIndex(MAIN_GAME);
    setPlayerAction(0, 0);

}

//INCLUDE_ASM("asm/nonmatchings/game/transition", openOverlayScreen);

// pause before going to overlay screen or naming screen
void inline openOverlayScreen(void) {
    pauseAllEntityLoads();
    pauseAllCutsceneExecutors();
    setEntityMapSpaceIndependent(ENTITY_PLAYER, FALSE);
    unloadMapAssets(MAIN_MAP_INDEX);
}

//INCLUDE_ASM("asm/nonmatchings/game/transition", startNewDay);

void startNewDay(void) {
    
    u8 i, j;
    
    if (checkLifeEventBit(HOUSE_EXTENSION_CONSTRUCTION)) {
        houseExtensionConstructionCounter++;
    }
    
    if (checkDailyEventBit(CARPENTER_ESTIMATE)) {
        setLifeEventBit(HOUSE_EXTENSION_CONSTRUCTION);
    }
     
    if (gSeason == AUTUMN && gDayOfMonth == 28) {
        setLifeEventBit(BRIDGE_COMPLETED);
    }
    
    if (gSeason == WINTER && gDayOfMonth == 17) {
        setLifeEventBit(HOT_SPRINGS_COMPLETED);
        setDailyEventBit(0x38);
    }
    
    if (gDayOfMonth == 1) {
        
        for (i = 0; i < 5; i++) {
            for (j = 0; j < 7; j++) {
                D_80189108[i][j] = 0xFF;
            }
        }
        
    }
    
    if (gSeason == SPRING && gDayOfMonth == 23) {
        setFlowerFestivalGoddess();
    }

    if (gSeason == AUTUMN) {

        if (gDayOfMonth == 12) {
            gHarvestCoinFinder = getRandomNumberInRange(0, 5);
            if (checkLifeEventBit(CLIFF_GONE) && gHarvestCoinFinder == 4) {
                gHarvestCoinFinder = 1;
            }
            if (checkLifeEventBit(KAI_GONE) && gHarvestCoinFinder == 5) {
                gHarvestCoinFinder = 2;
            }
        }

        if (gSeason == AUTUMN && gDayOfMonth == 13 && !checkDailyEventBit(0x5D) && gHarvestCoinFinder == PLAYER) {
            gHarvestCoinFinder = 3;
        }
    }
    
    if (checkLifeEventBit(ELLEN_DIED)) {
        if (gElliGrievingCounter >= 31) {
            toggleSpecialDialogueBit(ELLI_FINISH_GRIEVING);
        } else {
            gElliGrievingCounter++;
        }
    }
    
    if (gWeather == TYPHOON) {
        
        // get average of sprite affection
        if (((npcAffection[HARVEST_SPRITE_1] + npcAffection[HARVEST_SPRITE_2] + npcAffection[HARVEST_SPRITE_3]) / 3) >= 120) {
            
            // check animal score
            if ((func_8009B564() + func_8009B374()) >= 2) {
                setLifeEventBit(HARVEST_SPRITES_ANIMAL_HELP);
            }

        }
        
        // harvest sprites help with animals during typhoon
        if (gWeather == TYPHOON && checkLifeEventBit(HARVEST_SPRITES_ANIMAL_HELP)) {
            func_80087D5C();
        }

    }
    
    // dog/horse race
    if (checkLifeEventBit(0x51) && checkDailyEventBit(0x41)) {
        toggleLifeEventBit(0x51);
    }
    
    if (checkLifeEventBit(0x52) && checkDailyEventBit(0x42)) {
        toggleLifeEventBit(0x52);
    }
    
    // Mrs. Mana's cow
    if (checkLifeEventBit(0x93)) {
        toggleLifeEventBit(0x93);
        setLifeEventBit(0x94);
        setMrsManaCowsNames();
    }
    
    removeKeyItem(HORSE_RACE_TICKET);

    // equalize harvest sprite affection
    npcAffection[HARVEST_SPRITE_2] = npcAffection[HARVEST_SPRITE_1];
    npcAffection[HARVEST_SPRITE_3] = npcAffection[HARVEST_SPRITE_1];
    
    if (gWeather == RAIN) {
        // update animal status based on rain
        func_80064114();
    }
    
    if (gWeather == SNOW) {
        // update animal status based on snow
        func_800644B0();
    }
    
    if (gWeather == TYPHOON) {
        // update animal status based on typhoon
        func_80064814();
    }
    
    gWeather = gForecast;
    
    incrementVarietyShowCounter();
    setForecast();
    
    if (checkLifeEventBit(0x7E)) {
        // unused code?
        checkLifeEventBit(0x7F);
    }
    
    func_800DB424();

    resetAnimalStatuses();
    updateCropsIfRain();
    randomlyAddWeedsToFarmField();
    updateFamilyStates();
    setLetters();
    
    if (checkLifeEventBit(MARRIED)) {
        handleWifeMorningHelp();
    }
    
    if (checkDailyEventBit(7)) {
        // save game
        func_800E53E8(gCurrentGameIndex);
    }
    
    // update more game state
    func_800598E0();
    
}
