#include <nusys.h>

// ============================================================================
// Header
// ============================================================================

beginseg
    name    "header"
    flags   RAW
    include "$(BUILD_DIR)/config/us/header.o"
endseg

// ============================================================================
// Boot
// ============================================================================

beginseg
    name "boot"
    include "$(BUILD_DIR)/makerom/ipl3.o"
endseg

beginseg
    name "entry"
    address 0x80025C00
    include "$(BUILD_DIR)/makerom/entry.o"
endseg

beginseg
    name    "code"
    flags    OBJECT
    address  0x80025C50
    include "$(BUILD_DIR)/codesegment.o"
    include "$(BUILD_DIR)/lib/ucode/rspboot.o"
    include "$(BUILD_DIR)/lib/ucode/n_aspMain.o"
    include "$(BUILD_DIR)/lib/ucode/gspF3DEX2.fifo.o"
endseg

// ============================================================================
// Buffers
// ============================================================================

beginseg
    name "messageBoxBuffer"
    flags OBJECT
    address 0x80238800
    include "build/src/buffers/messageBoxBuffer.o"
endseg

beginseg
    name "dialogueIconSpriteBuffer"
    flags OBJECT
    address 0x8023B400
    include "build/src/buffers/dialogueIconSpriteBuffer.o"
endseg

beginseg
    name "characterAvatarsSpriteBuffer"
    flags OBJECT
    address 0x8023D300
    include "build/src/buffers/characterAvatarsSpriteBuffer.o"
endseg

beginseg
    name "shadowSpriteBuffer"
    flags OBJECT
    address 0x80240300
    include "build/src/buffers/shadowSpriteBuffer.o"
endseg

beginseg
    name "playerSpriteBuffer"
    flags OBJECT
    address 0x80240B00
    include "build/src/buffers/playerSpriteBuffer.o"
endseg

beginseg
    name "namingScreenBuffer"
    flags OBJECT
    address 0x80253B00
    include "build/src/buffers/namingScreenBuffer.o"
endseg

beginseg
    name "mapDataBuffer"
    flags OBJECT
    address 0x80255000
    include "build/src/buffers/mapDataBuffer.o"
endseg

beginseg
    name "spriteBuffer"
    flags OBJECT
    address 0x8026F000
    include "build/src/buffers/spriteBuffer.o"
endseg

beginseg
    name "mapObjectBuffer"
    flags OBJECT
    address 0x802E4000
    include "build/src/buffers/mapObjectBuffer.o"
endseg

beginseg
    name "cutsceneBytecodeBuffer"
    flags OBJECT
    address 0x802F4000
    include "build/src/buffers/cutsceneBytecodeBuffer.o"
endseg

beginseg
    name "fontBuffer"
    flags OBJECT
    address 0x802FF000
    include "build/src/buffers/fontBuffer.o"
endseg

beginseg
    name "textBuffer"
    flags OBJECT
    address 0x8030A800
    include "build/src/buffers/textBuffer.o"
endseg

beginseg
    name "messageBoxesBuffer"
    flags OBJECT
    address 0x8030B000
    include "build/src/buffers/messageBoxesBuffer.o"
endseg

beginseg
    name "dialogueBytecodeBuffer"
    flags OBJECT
    address 0x8030C800
    include "build/src/buffers/dialogueBytecodeBuffer.o"
endseg

beginseg
    name "sramBuffer"
    flags OBJECT
    address 0x8030D000
    include "build/src/buffers/sramBuffer.o"
endseg

beginseg
    name "farmRankingsBuffer"
    flags OBJECT
    address 0x8030E000
    include "build/src/buffers/farmRankingsBuffer.o"
endseg

beginseg
    name "unknownBuffer"
    flags OBJECT
    address 0x8030F800
    include "build/src/buffers/unknownBuffer.o"
endseg

beginseg
    name "frameBuffer"
    flags OBJECT
    address 0x8038F800
    include "build/src/buffers/frameBuffer.o"
endseg

// ============================================================================
// Asset Segments
// ============================================================================

#include "assets/cutscenes/cutscenes.spec"
#include "assets/sprites/entity-sprites/entitySprites.spec"
#include "assets/maps/maps.spec"
#include "assets/sprites/map-objects/mapObjects.spec"
#include "assets/sprites/misc/miscSprites.spec"
#include "assets/sprites/overlay-screens/overlayScreens.spec"
#include "assets/font/font.spec"
#include "assets/text/texts.spec"
#include "assets/dialogue/dialogues.spec"
#include "assets/audio/audio.spec"

// ============================================================================
// WAVE SECTION
// ============================================================================

beginwave
    name    "game"

    include "code"

    include "messageBoxBuffer"
    include "dialogueIconSpriteBuffer"
    include "characterAvatarsSpriteBuffer"
    include "shadowSpriteBuffer"
    include "playerSpriteBuffer"
    include "namingScreenBuffer"
    include "mapDataBuffer"
    include "spriteBuffer"
    include "mapObjectBuffer"
    include "cutsceneBytecodeBuffer"
    include "fontBuffer"
    include "textBuffer"
    include "messageBoxesBuffer"
    include "dialogueBytecodeBuffer"
    include "sramBuffer"
    include "farmRankingsBuffer"
    include "unknownBuffer"
    include "frameBuffer"

    include "cutsceneBank1"
    include "cutsceneBank2"
    include "cutsceneBank3"
    include "cutsceneBank4"
    include "cutsceneBank5"
    include "cutsceneBank6"
    include "cutsceneBank7"
    include "cutsceneBank8"
    include "cutsceneBank9"
    include "cutsceneBank10"
    include "cutsceneBank11"
    include "cutsceneBank12"
    include "cutsceneBank13"
    include "cutsceneBank14"
    include "fireworksFestival"
    include "cutsceneBank16"
    include "cutsceneBank17"
    include "cutsceneBank18"
    include "cutsceneBank19"
    include "cutsceneBank20"
    include "cutsceneBank21"
    include "cutsceneBank22"
    include "cutsceneBank23"
    include "cutsceneBank24"
    include "cutsceneBank25"
    include "cutsceneBank26"
    include "cutsceneBank27"

    include "playerTexture"
    include "playerAssetsIndex"
    include "playerSpritesheetIndex"

    include "mariaTexture"
    include "mariaAssetsIndex"
    include "mariaSpritesheetIndex"
    include "popuriTexture"
    include "popuriAssetsIndex"
    include "popuriSpritesheetIndex"
    include "elliTexture"
    include "elliAssetsIndex"
    include "elliSpritesheetIndex"
    include "annTexture"
    include "annAssetsIndex"
    include "annSpritesheetIndex"
    include "karenTexture"
    include "karenAssetsIndex"
    include "karenSpritesheetIndex"

    include "babyTexture"
    include "babyAssetsIndex"
    include "babySpritesheetIndex"

    include "harrisTexture"
    include "harrisAssetsIndex"
    include "harrisSpritesheetIndex"
    include "grayTexture"
    include "grayAssetsIndex"
    include "graySpritesheetIndex"
    include "jeffTexture"
    include "jeffAssetsIndex"
    include "jeffSpritesheetIndex"
    include "cliffTexture"
    include "cliffAssetsIndex"
    include "cliffSpritesheetIndex"
    include "kaiTexture"
    include "kaiAssetsIndex"
    include "kaiSpritesheetIndex"

    include "mayorTexture"
    include "mayorAssetsIndex"
    include "mayorSpritesheetIndex"
    include "mayorWifeTexture"
    include "mayorWifeAssetsIndex"
    include "mayorWifeSpritesheetIndex"
    include "liliaTexture"
    include "liliaAssetsIndex"
    include "liliaSpritesheetIndex"
    include "basilTexture"
    include "basilAssetsIndex"
    include "basilSpritesheetIndex"
    include "ellenTexture"
    include "ellenAssetsIndex"
    include "ellenSpritesheetIndex"
    include "dougTexture"
    include "dougAssetsIndex"
    include "dougSpritesheetIndex"
    include "gotzTexture"
    include "gotzAssetsIndex"
    include "gotzSpritesheetIndex"
    include "sashaTexture"
    include "sashaAssetsIndex"
    include "sashaSpritesheetIndex"
    include "potionShopDealerTexture"
    include "potionShopDealerAssetsIndex"
    include "potionShopDealerSpritesheetIndex"
    include "kentTexture"
    include "kentAssetsIndex"
    include "kentSpritesheetIndex"
    include "stuTexture"
    include "stuAssetsIndex"
    include "stuSpritesheetIndex"
    include "midwifeTexture"
    include "midwifeAssetsIndex"
    include "midwifeSpritesheetIndex"
    include "mayTexture"
    include "mayAssetsIndex"
    include "maySpritesheetIndex"
    include "rickTexture"
    include "rickAssetsIndex"
    include "rickSpritesheetIndex"
    include "pastorTexture"
    include "pastorAssetsIndex"
    include "pastorSpritesheetIndex"
    include "shipperTexture"
    include "shipperAssetsIndex"
    include "shipperSpritesheetIndex"
    include "saibaraTexture"
    include "saibaraAssetsIndex"
    include "saibaraSpritesheetIndex"
    include "dukeTexture"
    include "dukeAssetsIndex"
    include "dukeSpritesheetIndex"
    include "gregTexture"
    include "gregAssetsIndex"
    include "gregSpritesheetIndex"
    include "assistantCarpentersTexture"
    include "assistantCarpentersAssetsIndex"
    include "assistantCarpentersSpritesheetIndex"
    include "masterCarpenterTexture"
    include "masterCarpenterAssetsIndex"
    include "masterCarpenterSpritesheetIndex"
    include "harvestSpriteTexture"
    include "harvestSpriteAssetsIndex"
    include "harvestSpriteSpritesheetIndex"
    include "barleyTexture"
    include "barleyAssetsIndex"
    include "barleySpritesheetIndex"
    include "sydneyTexture"
    include "sydneyAssetsIndex"
    include "sydneySpritesheetIndex"
    include "entomologistTexture"
    include "entomologistAssetsIndex"
    include "entomologistSpritesheetIndex"
    include "gourmetJudgeTexture"
    include "gourmetJudgeAssetsIndex"
    include "gourmetJudgeSpritesheetIndex"
    include "photographerTexture"
    include "photographerAssetsIndex"
    include "photographerSpritesheetIndex"
    include "shadySalesmanTexture"
    include "shadySalesmanAssetsIndex"
    include "shadySalesmanSpritesheetIndex"
    include "mrsManaSonTexture"
    include "mrsManaSonAssetsIndex"
    include "mrsManaSonSpritesheetIndex"
    include "manaTexture"
    include "manaAssetsIndex"
    include "manaSpritesheetIndex"
    include "oldManTexture"
    include "oldManAssetsIndex"
    include "oldManSpritesheetIndex"
    include "oldWomanTexture"
    include "oldWomanAssetsIndex"
    include "oldWomanSpritesheetIndex"
    include "touristCoupleManTexture"
    include "touristCoupleManAssetsIndex"
    include "touristCoupleManSpritesheetIndex"
    include "touristCoupleWomanTexture"
    include "touristCoupleWomanAssetsIndex"
    include "touristCoupleWomanSpritesheetIndex"
    include "festivalGirl1Texture"
    include "festivalGirl1AssetsIndex"
    include "festivalGirl1SpritesheetIndex"
    include "festivalGirl2Texture"
    include "festivalGirl2AssetsIndex"
    include "festivalGirl2SpritesheetIndex"
    include "festivalGirl3Texture"
    include "festivalGirl3AssetsIndex"
    include "festivalGirl3SpritesheetIndex"
    include "harvestGoddessTexture"
    include "harvestGoddessAssetsIndex"
    include "harvestGoddessSpritesheetIndex"
    include "spiritFestivalOcarinaPerformerTexture"
    include "spiritFestivalOcarinaPerformerAssetsIndex"
    include "spiritFestivalOcarinaPerformerSpritesheetIndex"
    include "kappaTexture"
    include "kappaAssetsIndex"
    include "kappaSpritesheetIndex"
    include "princessTexture"
    include "princessAssetsIndex"
    include "princessSpritesheetIndex"
    include "emptyNPCTexture"
    include "emptyNPCAssetsIndex"
    include "emptyNPCSpritesheetIndex"
    include "bunnyTexture"
    include "bunnyAssetsIndex"
    include "bunnySpritesheetIndex"
    include "mouseTexture"
    include "mouseAssetsIndex"
    include "mouseSpritesheetIndex"
    include "foxTexture"
    include "foxAssetsIndex"
    include "foxSpritesheetIndex"
    include "monkeyTexture"
    include "monkeyAssetsIndex"
    include "monkeySpritesheetIndex"
    include "hawkTexture"
    include "hawkAssetsIndex"
    include "hawkSpritesheetIndex"
    include "moleTexture"
    include "moleAssetsIndex"
    include "moleSpritesheetIndex"
    include "squirrelTexture"
    include "squirrelAssetsIndex"
    include "squirrelSpritesheetIndex"
    include "birdTexture"
    include "birdAssetsIndex"
    include "birdSpritesheetIndex"

    include "catTexture"
    include "catAssetsIndex"
    include "catSpritesheetIndex"
    include "dogTexture"
    include "dogAssetsIndex"
    include "dogSpritesheetIndex"
    include "dogTitleTexture"
    include "dogTitleAssetsIndex"
    include "dogTitleSpritesheetIndex"
    include "horsePonyTexture"
    include "horsePonyAssetsIndex"
    include "horsePonySpritesheetIndex"
    include "horseGrownTexture"
    include "horseGrownAssetsIndex"
    include "horseGrownSpritesheetIndex"
    include "chickTexture"
    include "chickAssetsIndex"
    include "chickSpritesheetIndex"
    include "chickenTexture"
    include "chickenAssetsIndex"
    include "chickenSpritesheetIndex"
    include "calfTexture"
    include "calfAssetsIndex"
    include "calfSpritesheetIndex"
    include "youngCowTexture"
    include "youngCowAssetsIndex"
    include "youngCowSpritesheetIndex"
    include "cowTexture"
    include "cowAssetsIndex"
    include "cowSpritesheetIndex"
    include "lambTexture"
    include "lambAssetsIndex"
    include "lambSpritesheetIndex"
    include "sheepTexture"
    include "sheepAssetsIndex"
    include "sheepSpritesheetIndex"
    include "frogTexture"
    include "frogAssetsIndex"
    include "frogSpritesheetIndex"
    include "crabTexture"
    include "crabAssetsIndex"
    include "crabSpritesheetIndex"
    include "hornedBeetleTexture"
    include "hornedBeetleAssetsIndex"
    include "hornedBeetleSpritesheetIndex"
    include "stagBeetleTexture"
    include "stagBeetleAssetsIndex"
    include "stagBeetleSpritesheetIndex"
    include "cricketTexture"
    include "cricketAssetsIndex"
    include "cricketSpritesheetIndex"
    include "cicadaTexture"
    include "cicadaAssetsIndex"
    include "cicadaSpritesheetIndex"
    include "whiteButterflyTexture"
    include "whiteButterflyAssetsIndex"
    include "whiteButterflySpritesheetIndex"
    include "ladybugTexture"
    include "ladybugAssetsIndex"
    include "ladybugSpritesheetIndex"
    include "dragonflyTexture"
    include "dragonflyAssetsIndex"
    include "dragonflySpritesheetIndex"
    include "grasshopperTexture"
    include "grasshopperAssetsIndex"
    include "grasshopperSpritesheetIndex"
    include "snakeTexture"
    include "snakeAssetsIndex"
    include "snakeSpritesheetIndex"
    include "purpleButterflyTexture"
    include "purpleButterflyAssetsIndex"
    include "purpleButterflySpritesheetIndex"

    include "dadTexture"
    include "dadAssetsIndex"
    include "dadSpritesheetIndex"
    include "cowIndoorsTexture"
    include "cowIndoorsAssetsIndex"
    include "cowIndoorsSpritesheetIndex"
    include "horseUnbridledTexture"
    include "horseUnbridledAssetsIndex"
    include "horseUnbridledSpritesheetIndex"
    include "horseRacerTexture"
    include "horseRacerAssetsIndex"
    include "horseRacerSpritesheetIndex"
    include "emptyEntityTexture"
    include "emptyEntityAssetsIndex"
    include "emptyEntitySpritesheetIndex"

    include "mariaHarrisBabyTexture"
    include "mariaHarrisBabyAssetsIndex"
    include "mariaHarrisBabySpritesheetIndex"
    include "popuriGrayBabyTexture"
    include "popuriGrayBabyAssetsIndex"
    include "popuriGrayBabySpritesheetIndex"
    include "elliJeffBabyTexture"
    include "elliJeffBabyAssetsIndex"
    include "elliJeffBabySpritesheetIndex"
    include "annCliffBabyTexture"
    include "annCliffBabyAssetsIndex"
    include "annCliffBabySpritesheetIndex"
    include "karenKaiBabyTexture"
    include "karenKaiBabyAssetsIndex"
    include "karenKaiBabySpritesheetIndex"

    include "shadowsTexture"
    include "shadowsIndex"
    include "expressionBubblesTexture"
    include "expressionBubblesAssetsIndex"
    include "expressionBubblesSpritesheetIndex"


    include "ranchSpringMap"
    include "ranchSummerMap"
    include "ranchFallMap"
    include "ranchWinterMap"
    include "annsRoomMap"
    include "ranchBarnMap"
    include "ranchStoreMap"
    include "ranchHouseMap"
    include "emptyMap1"

    include "beachSpringMap"
    include "beachSummerMap"
    include "beachFallMap"
    include "beachWinterMap"

    include "raceTrackSpringMap"
    include "raceTrackSummerMap"
    include "raceTrackFallMap"
    include "raceTrackWinterMap"

    include "mountain1SpringMap"
    include "mountain1SummerMap"
    include "mountain1FallMap"
    include "mountain1WinterMap"
    include "mountain2SpringMap"
    include "mountain2SummerMap"
    include "mountain2FallMap"
    include "mountain2WinterMap"
    include "topOfMountain1SpringMap"
    include "topOfMountain1SummerMap"
    include "topOfMountain1FallMap"
    include "topOfMountain1WinterMap"
    include "moonMountainSpringMap"
    include "moonMountainSummerMap"
    include "moonMountainFallMap"
    include "moonMountainWinterMap"
    include "carpentersHutMap"
    include "dumplingHouseMap"

    include "pondSpringMap"
    include "pondSummerMap"
    include "pondFallMap"
    include "pondWinterMap"

    include "ellisRoomMap"
    include "bakeryMap"

    include "village1SpringMap"
    include "village1SummerMap"
    include "village1FallMap"
    include "village1WinterMap"
    include "village2SpringMap"
    include "village2SummerMap"
    include "village2FallMap"
    include "village2WinterMap"
    include "popurisRoomMap"
    include "flowerShopMap"
    include "churchMap"
    include "souvenirShopMap"

    include "squareSpringMap"
    include "squareSummerMap"
    include "squareFallMap"
    include "squareWinterMap"
    include "ricksShopMap"
    include "midwifesHouseMap"
    include "tavernMap"
    include "libraryMap"

    include "mariasRoomMap"
    include "mayorsHouseMap"

    include "potionShopBackroomMap"
    include "potionShopMap"
    include "emptyMap2"

    include "spriteCaveMap"
    include "caveMap"
    include "emptyMineMap"
    include "mineMap"

    include "karensRoomMap"
    include "vineyardSpringMap"
    include "vineyardSummerMap"
    include "vineyardFallMap"
    include "vineyardWinterMap"
    include "vineyardHouseMap"
    include "vineyardCellar1Map"
    include "vineyardCellar2Map"

    include "roadSpringMap"
    include "roadSummerMap"
    include "roadFallMap"
    include "roadWinterMap"

    include "farmSpringMap"
    include "farmSummerMap"
    include "farmFallMap"
    include "farmWinterMap"
    include "greenhouseMap"
    include "houseMap"
    include "barnMap"
    include "coopMap"
    include "kitchenMap"
    include "bathroomMap"

    include "wavesTexture"
    include "wavesAssetsIndex"
    include "wavesSpritesheetIndex"
    include "waterTilesTexture"
    include "waterTilesAssetsIndex"
    include "waterTilesSpritesheetIndex"

    include "boulderTexture"
    include "boulderAssetsIndex"
    include "boulderSpritesheetIndex"
    include "bridgeTexture"
    include "bridgeAssetsIndex"
    include "bridgeSpritesheetIndex"
    include "stonePillarTexture"
    include "stonePillarAssetsIndex"
    include "stonePillarSpritesheetIndex"
    include "emptyMountainSprite1Texture"
    include "emptyMountainSprite2Texture"
    include "mountainPathTilesTexture"
    include "mountainPathTilesAssetsIndex"
    include "mountainPathTilesSpritesheetIndex"
    include "steamTexture"
    include "steamAssetsIndex"
    include "steamSpritesheetIndex"

    include "pondWaterTexture"
    include "pondWaterAssetsIndex"
    include "pondWaterSpritesheetIndex"

    include "festivalFlowersTexture"
    include "festivalFlowersAssetsIndex"
    include "festivalFlowersSpritesheetIndex"
    include "squareFountainTexture"
    include "squareFountainAssetsIndex"
    include "squareFountainSpritesheetIndex"
    include "village2WaterTexture"
    include "village2WaterAssetsIndex"
    include "village2WaterSpritesheetIndex"

    include "emptyMapSprite1Texture"
    include "emptyMapSprite2Texture"
    include "emptyMapSprite3Texture"
    include "emptyMapSprite4Texture"
    include "emptyMapSprite5Texture"
    include "emptyMapSprite6Texture"
    include "stoneTexture"
    include "stoneAssetsIndex"
    include "stoneSpritesheetIndex"
    include "vineyardTreeTexture"
    include "vineyardTreeAssetsIndex"
    include "vineyardTreeSpritesheetIndex"
    include "emptyMap1Texture"
    include "emptyMap2Texture"
    include "farmPondTexture"
    include "farmPondAssetsIndex"
    include "farmPondSpritesheetIndex"

    include "funeralSpritesTexture"
    include "funeralSpritesIndex"
    include "moonMountainBackgroundTexture"
    include "moonMountainBackgroundAssetsIndex"
    include "horseRaceTexture"
    include "horseRaceAssetsIndex"
    include "emptyOverlayScreen1Texture"

    include "splashTexture"
    include "splashAssetsIndex"
    include "sparklersTexture"
    include "sparklersAssetsIndex"
    include "chimneySmokeTexture"
    include "chimneySmokeAssetsIndex"
    include "balloonsTexture"
    include "balloonsAssetsIndex"
    include "smallCloudTexture"
    include "smallCloudAssetsIndex"
    include "fairiesTexture"
    include "fairiesTextureAssetsIndex"
    include "firefliesTexture"
    include "firefliesAssetsIndex"

    include "bulletBlinkingTexture"
    include "bulletBlinkingAssetsIndex"
    include "bulletNumeralTexture"
    include "bulletNumeralAssetsIndex"
    include "checkerboardBackgroundTexture"
    include "checkerboardBackgroundAssetsIndex"
    include "emptyOverlayScreen2Texture"
    include "emptyOverlayScreen3Texture"
    include "namingScreenBackgroundTexture"
    include "namingScreenBackgroundAssetsIndex"
    include "bookTexture"
    include "bookAssetsIndex"
    include "photoSmallTexture"
    include "photoSmallAssetsIndex"
    include "snapshotLargeTexture"
    include "snapshotLargeAssetsIndex"
    include "namingScreen1Texture"
    include "namingScreen1AssetsIndex"
    include "calendarTexture"
    include "calendarAssetsIndex"
    include "calenderJapanTexture"
    include "calenderJapanAssetsIndex"
    include "bookScreenLabelsTexture"
    include "bookScreenLabelsAssetsIndex"
    include "japaneseCharacterSelectTexture"
    include "japaneseCharacterSelectAssetsIndex"
    include "overlayScreenNamesTexture"
    include "overlayScreenNamesAssetsIndex"
    include "moneyTexture"
    include "moneyAssetsIndex"
    include "powerNutTreeDrawingTexture"
    include "powerNutTreeDrawingAssetsIndex"
    include "inventoryScreenTexture"
    include "inventoryScreenAssetsIndex"
    include "prizeScreenTexture"
    include "prizeScreenAssetsIndex"
    include "loadGameScreenTexture"
    include "loadGameScreenAssetsIndex"
    include "messageBoxTexture"
    include "messageBoxAssetsIndex"
    include "namingScreen2Texture"
    include "namingScreen2AssetsIndex"
    include "estimateScreenTexture"
    include "estimateScreenAssetsIndex"
    include "raceBettingUiTexture"
    include "raceBettingUiAssetsIndex"
    include "emptyOverlayScreen4Texture"
    include "timeUiTexture"
    include "timeUiAssetsIndex"
    include "houseExtensionSelectionTexture"
    include "houseExtensionSelectionAssetsIndex"
    include "shopIconsTexture"
    include "shopIconsAssetsIndex"
    include "rankingsTexture"
    include "rankingsAssetsIndex"
    include "guidebookTexture"
    include "guidebookAssetsIndex"
    include "dialogueIconsTexture"
    include "dialogueIconsAssetsIndex"
    include "tvContentTexture"
    include "tvContentAssetsIndex"
    include "tvContentSpritesheetIndex"

    include "toolsTexture"
    include "toolsAssetsIndex"
    include "toolsSpritesheetIndex"
    include "holdableItemsTexture"
    include "holdableItemsAssetsIndex"
    include "holdableItemsSpritesheetIndex"
    include "extraFestivalTexture"
    include "extraFestivalAssetsIndex"
    include "extraFestivalSpritesheetIndex"
    include "homeItemsTexture"
    include "homeItemsAssetsIndex"
    include "homeItemsSpritesheetIndex"
    include "groundObjectsTexture"
    include "groundObjectsIndex"
    include "rainTexture"
    include "rainAssetsIndex"

    include "characterDialogueIconsTexture"
    include "characterDialogueIconsAssetsIndex"
    include "characterDialogueIconsSpritesheetIndex"
    include "titleSpritesTexture"
    include "titleSpritesAssetsIndex"
    include "controllerIconsTexture"
    include "controllerIconsAssetsIndex"
    include "logoTextures"
    include "logoAssetsIndex"
    include "creditsTexture"
    include "creditsAssetsIndex"
    include "albumPhotosTexture"
    include "albumPhotosAssetsIndex"
    include "albumPhotosSpritesheetIndex"
    include "villageMapScreenTexture"
    include "villageMapScreenAssetsIndex"

    include "fontTexture"
    include "fontPalette1"
    include "fontPalette2"
    include "fontPalette3"

    include "text1Text"
    include "text1TextIndex"
    include "libraryText"
    include "libraryTextIndex"
    include "diaryText"
    include "diaryTextIndex"
    include "text4Text"
    include "text4TextIndex"
    include "festivalOverlaySelectionsText"
    include "festivalOverlaySelectionsTextIndex"
    include "lettersText"
    include "lettersTextIndex"
    include "shopText"
    include "shopTextIndex"
    include "animalInteractionsText"
    include "animalInteractionsTextIndex"
    include "tvText"
    include "tvTextIndex"
    include "text10Text"
    include "text10TextIndex"
    include "namingScreenText"
    include "namingScreenTextIndex"
    include "elliText"
    include "elliTextIndex"
    include "kaiText"
    include "kaiTextIndex"
    include "karenText"
    include "karenTextIndex"
    include "gotzText"
    include "gotzTextIndex"
    include "sashaText"
    include "sashaTextIndex"
    include "cliffText"
    include "cliffTextIndex"
    include "jeffText"
    include "jeffTextIndex"
    include "kentText"
    include "kentTextIndex"
    include "harrisText"
    include "harrisTextIndex"
    include "popuriText"
    include "popuriTextIndex"
    include "mariaText"
    include "mariaTextIndex"
    include "mayText"
    include "mayTextIndex"
    include "annText"
    include "annTextIndex"
    include "dougText"
    include "dougTextIndex"
    include "grayText"
    include "grayTextIndex"
    include "basilText"
    include "basilTextIndex"
    include "liliaText"
    include "liliaTextIndex"
    include "dukeText"
    include "dukeTextIndex"
    include "shipperText"
    include "shipperTextIndex"
    include "harvestSpritesText"
    include "harvestSpritesTextIndex"
    include "assistantCarpentersText"
    include "assistantCarpentersTextIndex"
    include "masterCarpenterText"
    include "masterCarpenterTextIndex"
    include "mayorText"
    include "mayorTextIndex"
    include "gregText"
    include "gregTextIndex"
    include "rickText"
    include "rickTextIndex"
    include "barleyText"
    include "barleyTextIndex"
    include "sydneyText"
    include "sydneyTextIndex"
    include "potionShopDealerText"
    include "potionShopDealerTextIndex"
    include "mayorWifeText"
    include "mayorWifeTextIndex"
    include "ellenText"
    include "ellenTextIndex"
    include "stuText"
    include "stuTextIndex"
    include "midwifeText"
    include "midwifeTextIndex"
    include "pastorText"
    include "pastorTextIndex"
    include "saibaraText"
    include "saibaraTextIndex"
    include "cutscenes1Text"
    include "cutscenes1TextIndex"
    include "funeralIntroText"
    include "funeralIntroTextIndex"
    include "text48Text"
    include "text48TextIndex"
    include "text49Text"
    include "text49TextIndex"
    include "text50Text"
    include "text50TextIndex"
    include "text51Text"
    include "text51TextIndex"
    include "text52Text"
    include "text52TextIndex"
    include "dogRaceText"
    include "dogRaceTextIndex"
    include "text54Text"
    include "text54TextIndex"
    include "text55Text"
    include "text55TextIndex"
    include "text56Text"
    include "text56TextIndex"
    include "newYearFestivalText"
    include "newYearFestivalTextIndex"
    include "spiritFestivalText"
    include "spiritFestivalTextIndex"
    include "horseRaceText"
    include "horseRaceTextIndex"
    include "marriedDialoguesText"
    include "marriedDialoguesTextIndex"
    include "text61Text"
    include "text61TextIndex"
    include "karenCutscenes1Text"
    include "karenCutscenes1TextIndex"
    include "text63Text"
    include "text63TextIndex"
    include "text64Text"
    include "text64TextIndex"
    include "text65Text"
    include "text65TextIndex"
    include "eggFestivalText"
    include "eggFestivalTextIndex"
    include "karenCutscenes2Text"
    include "karenCutscenes2TextIndex"
    include "vegetableFestivalText"
    include "vegetableFestivalTextIndex"
    include "babyText"
    include "babyTextIndex"
    include "mrsManaAndJohnText"
    include "mrsManaAndJohnTextIndex"
    include "additionalNpcsText"
    include "additionalNpcsTextIndex"
    include "howToPlayText"
    include "howToPlayTextIndex"

    include "dialogueBytecodeSegment1"
    include "dialogueBytecodeSegment1Index"
    include "dialogueBytecodeSegment2"
    include "dialogueBytecodeSegment2Index"
    include "dialogueBytecodeSegment3"
    include "dialogueBytecodeSegment3Index"
    include "dialogueBytecodeSegment4"
    include "dialogueBytecodeSegment4Index"
    include "dialogueBytecodeSegment5"
    include "dialogueBytecodeSegment5Index"
    include "dialogueBytecodeSegment6"
    include "dialogueBytecodeSegment6Index"
    include "dialogueBytecodeSegment7"
    include "dialogueBytecodeSegment7Index"
    include "dialogueBytecodeSegment8"
    include "dialogueBytecodeSegment8Index"
    include "dialogueBytecodeSegment9"
    include "dialogueBytecodeSegment9Index"
    include "mariaDialogueBytecode"
    include "mariaDialogueBytecodeIndex"
    include "dialogueBytecodeSegment11"
    include "dialogueBytecodeSegment11Index"
    include "dialogueBytecodeSegment12"
    include "dialogueBytecodeSegment12Index"
    include "dialogueBytecodeSegment13"
    include "dialogueBytecodeSegment13Index"
    include "dialogueBytecodeSegment14"
    include "dialogueBytecodeSegment14Index"
    include "dialogueBytecodeSegment15"
    include "dialogueBytecodeSegment15Index"
    include "dialogueBytecodeSegment16"
    include "dialogueBytecodeSegment16Index"
    include "dialogueBytecodeSegment17"
    include "dialogueBytecodeSegment17Index"
    include "dialogueBytecodeSegment18"
    include "dialogueBytecodeSegment18Index"
    include "dialogueBytecodeSegment19"
    include "dialogueBytecodeSegment19Index"
    include "dialogueBytecodeSegment20"
    include "dialogueBytecodeSegment20Index"
    include "dialogueBytecodeSegment21"
    include "dialogueBytecodeSegment21Index"
    include "dialogueBytecodeSegment22"
    include "dialogueBytecodeSegment22Index"
    include "dialogueBytecodeSegment23"
    include "dialogueBytecodeSegment23Index"
    include "dialogueBytecodeSegment24"
    include "dialogueBytecodeSegment24Index"
    include "dialogueBytecodeSegment25"
    include "dialogueBytecodeSegment25Index"
    include "dialogueBytecodeSegment26"
    include "dialogueBytecodeSegment26Index"
    include "dialogueBytecodeSegment27"
    include "dialogueBytecodeSegment27Index"
    include "dialogueBytecodeSegment28"
    include "dialogueBytecodeSegment28Index"
    include "dialogueBytecodeSegment29"
    include "dialogueBytecodeSegment29Index"
    include "dialogueBytecodeSegment30"
    include "dialogueBytecodeSegment30Index"
    include "dialogueBytecodeSegment31"
    include "dialogueBytecodeSegment31Index"
    include "dialogueBytecodeSegment32"
    include "dialogueBytecodeSegment32Index"
    include "dialogueBytecodeSegment33"
    include "dialogueBytecodeSegment33Index"
    include "dialogueBytecodeSegment34"
    include "dialogueBytecodeSegment34Index"
    include "dialogueBytecodeSegment35"
    include "dialogueBytecodeSegment35Index"
    include "dialogueBytecodeSegment36"
    include "dialogueBytecodeSegment36Index"
    include "dialogueBytecodeSegment37"
    include "dialogueBytecodeSegment37Index"
    include "dialogueBytecodeSegment38"
    include "dialogueBytecodeSegment38Index"
    include "dialogueBytecodeSegment39"
    include "dialogueBytecodeSegment39Index"
    include "dialogueBytecodeSegment40"
    include "dialogueBytecodeSegment40Index"
    include "dialogueBytecodeSegment41"
    include "dialogueBytecodeSegment41Index"
    include "dialogueBytecodeSegment42"
    include "dialogueBytecodeSegment42Index"
    include "dialogueBytecodeSegment43"
    include "dialogueBytecodeSegment43Index"
    include "dialogueBytecodeSegment44"
    include "dialogueBytecodeSegment44Index"
    include "dialogueBytecodeSegment45"
    include "dialogueBytecodeSegment45Index"
    include "dialogueBytecodeSegment46"
    include "dialogueBytecodeSegment46Index"
    include "dialogueBytecodeSegment47"
    include "dialogueBytecodeSegment47Index"
    include "dialogueBytecodeSegment48"
    include "dialogueBytecodeSegment48Index"
    include "dialogueBytecodeSegment49"
    include "dialogueBytecodeSegment49Index"
    include "dialogueBytecodeSegment50"
    include "dialogueBytecodeSegment50Index"
    include "dialogueBytecodeSegment51"
    include "dialogueBytecodeSegment51Index"
    include "dialogueBytecodeSegment52"
    include "dialogueBytecodeSegment52Index"
    include "dialogueBytecodeSegment53"
    include "dialogueBytecodeSegment53Index"
    include "dialogueBytecodeSegment54"
    include "dialogueBytecodeSegment54Index"
    include "dialogueBytecodeSegment55"
    include "dialogueBytecodeSegment55Index"
    include "dialogueBytecodeSegment56"
    include "dialogueBytecodeSegment56Index"
    include "dialogueBytecodeSegment57"
    include "dialogueBytecodeSegment57Index"
    include "dialogueBytecodeSegment58"
    include "dialogueBytecodeSegment58Index"
    include "dialogueBytecodeSegment59"
    include "dialogueBytecodeSegment59Index"
    include "dialogueBytecodeSegment60"
    include "dialogueBytecodeSegment60Index"
    include "dialogueBytecodeSegment61"
    include "dialogueBytecodeSegment61Index"
    include "dialogueBytecodeSegment62"
    include "dialogueBytecodeSegment62Index"
    include "dialogueBytecodeSegment63"
    include "dialogueBytecodeSegment63Index"
    include "dialogueBytecodeSegment64"
    include "dialogueBytecodeSegment64Index"
    include "dialogueBytecodeSegment65"
    include "dialogueBytecodeSegment65Index"
    include "dialogueBytecodeSegment66"
    include "dialogueBytecodeSegment66Index"
    include "dialogueBytecodeSegment67"
    include "dialogueBytecodeSegment67Index"
    include "dialogueBytecodeSegment68"
    include "dialogueBytecodeSegment68Index"
    include "dialogueBytecodeSegment69"
    include "dialogueBytecodeSegment69Index"
    include "dialogueBytecodeSegment70"
    include "dialogueBytecodeSegment70Index"

    include "waveTablePointer"
    include "waveTableData"

    include "opening"
    include "title"
    include "sportsFestival1"
    include "goodbye"
    include "spring"
    include "summer"
    include "autumn"
    include "winter"
    include "namingScreen"
    include "festivalTheme"
    include "sportsFestival2"
    include "spiritFestival"
    include "dogRace"
    include "racingFestival"
    include "festivalDance"
    include "mountain"
    include "village"
    include "pond"
    include "church"
    include "tavern"
    include "wedding"
    include "newYearSunrise"
    include "credits"
    include "brokenMusicBox"
    include "musicBox"
    include "flutePerformance"
    include "organPerformance"
    include "ocarinaPerformance"
    include "sleighBells"
    include "badEnding"
    include "vocalPerformance"
    include "ensemblePerformance"
    include "drumPerformance"
    include "typhoonAmbience1"
    include "typhoonAmbience2"
    include "nightAmbienceSpring"
    include "nightAmbienceSummer"
    include "nightAmbienceAutumn"
    include "starryNightFestival"
    include "beachAmbience1"
    include "beachAmbience2"

    include "bird1"
    include "bird2"
    include "seq44"
    include "cicada"
    include "seq46"
    include "seq47"
    include "seq48"
    include "fireworksSfx"
    include "seq50"
    include "horseGallopFast"
    include "horseGallop1"
    include "horseGallop2"
    include "horseGallop3"
    include "water1"
    include "water2"
    include "hammer"
    include "seq58"
    include "seq59"
    include "seq60"

endwave
