.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

/* Handwritten function */
nonmatching __osExceptionPreamble, 0x10

glabel __osExceptionPreamble
    /* E1380 80105F80 3C1A8010 */  lui        $k0, %hi(__osException) /* handwritten instruction */
    /* E1384 80105F84 275A6054 */  addiu      $k0, $k0, %lo(__osException) /* handwritten instruction */
    /* E1388 80105F88 03400008 */  jr         $k0
    /* E138C 80105F8C 00000000 */   nop
endlabel __osExceptionPreamble
.size __osExceptionPreamble, . - __osExceptionPreamble

/* Handwritten function */
nonmatching __ptExceptionPreamble, 0x20

glabel __ptExceptionPreamble
    /* E1390 80105F90 AFBAFFF0 */  sw         $k0, -0x10($sp) /* handwritten instruction */
    /* E1394 80105F94 10000003 */  b          .L80105FA4
    /* E1398 80105F98 3C1A8010 */   lui       $k0, %hi(__ptException) /* handwritten instruction */
    /* E139C 80105F9C 00000000 */  nop
    /* E13A0 80105FA0 00000000 */  nop
  .L80105FA4:
    /* E13A4 80105FA4 275A5FB0 */  addiu      $k0, $k0, %lo(__ptException) /* handwritten instruction */
    /* E13A8 80105FA8 03400008 */  jr         $k0
    /* E13AC 80105FAC 00000000 */   nop
endlabel __ptExceptionPreamble
.size __ptExceptionPreamble, . - __ptExceptionPreamble

/* Handwritten function */
nonmatching __ptException, 0xA0

glabel __ptException
    /* E13B0 80105FB0 401A6800 */  mfc0       $k0, $13 /* handwritten instruction */
    /* E13B4 80105FB4 335A007C */  andi       $k0, $k0, 0x7C /* handwritten instruction */
    /* E13B8 80105FB8 17400008 */  bnez       $k0, .L80105FDC /* handwritten instruction */
    /* E13BC 80105FBC 001AD082 */   srl       $k0, $k0, 2
    /* E13C0 80105FC0 401A6800 */  mfc0       $k0, $13 /* handwritten instruction */
    /* E13C4 80105FC4 00000000 */  nop
    /* E13C8 80105FC8 335A4000 */  andi       $k0, $k0, 0x4000 /* handwritten instruction */
    /* E13CC 80105FCC 13400021 */  beqz       $k0, __osException /* handwritten instruction */
    /* E13D0 80105FD0 00000000 */   nop
    /* E13D4 80105FD4 080417FE */  j          .L80105FF8
    /* E13D8 80105FD8 00000000 */   nop
  .L80105FDC:
    /* E13DC 80105FDC AFBBFFF8 */  sw         $k1, -0x8($sp) /* handwritten instruction */
    /* E13E0 80105FE0 3C1B8012 */  lui        $k1, %hi(__osCauseTable_pt) /* handwritten instruction */
    /* E13E4 80105FE4 277B3ED4 */  addiu      $k1, $k1, %lo(__osCauseTable_pt) /* handwritten instruction */
    /* E13E8 80105FE8 037AD820 */  add        $k1, $k1, $k0 /* handwritten instruction */
    /* E13EC 80105FEC 937A0000 */  lbu        $k0, 0x0($k1) /* handwritten instruction */
    /* E13F0 80105FF0 13400018 */  beqz       $k0, __osException /* handwritten instruction */
    /* E13F4 80105FF4 00000000 */   nop
  .L80105FF8:
    /* E13F8 80105FF8 3C1AA460 */  lui        $k0, %hi(D_A4600010) /* handwritten instruction */
    /* E13FC 80105FFC 8F5A0010 */  lw         $k0, %lo(D_A4600010)($k0) /* handwritten instruction */
    /* E1400 80106000 00000000 */  nop
    /* E1404 80106004 335A0003 */  andi       $k0, $k0, 0x3 /* handwritten instruction */
    /* E1408 80106008 1740FFFB */  bnez       $k0, .L80105FF8 /* handwritten instruction */
    /* E140C 8010600C 00000000 */   nop
    /* E1410 80106010 3C1ABFF1 */  lui        $k0, %hi(D_BFF08004) /* handwritten instruction */
    /* E1414 80106014 8F5A8004 */  lw         $k0, %lo(D_BFF08004)($k0) /* handwritten instruction */
    /* E1418 80106018 00000000 */  nop
    /* E141C 8010601C 335A0008 */  andi       $k0, $k0, 0x8 /* handwritten instruction */
    /* E1420 80106020 17400005 */  bnez       $k0, .L80106038 /* handwritten instruction */
    /* E1424 80106024 3C1ABFF0 */   lui       $k0, (0xBFF00014 >> 16) /* handwritten instruction */
    /* E1428 80106028 375A0014 */  ori        $k0, $k0, (0xBFF00014 & 0xFFFF) /* handwritten instruction */
    /* E142C 8010602C 8FBBFFF8 */  lw         $k1, -0x8($sp) /* handwritten instruction */
    /* E1430 80106030 03400008 */  jr         $k0
    /* E1434 80106034 27BDFFA0 */   addiu     $sp, $sp, -0x60
  .L80106038:
    /* E1438 80106038 401A7000 */  mfc0       $k0, $14 /* handwritten instruction */
    /* E143C 8010603C 3C1BBFF1 */  lui        $k1, %hi(D_BFF08000) /* handwritten instruction */
    /* E1440 80106040 AF7A8000 */  sw         $k0, %lo(D_BFF08000)($k1) /* handwritten instruction */
    /* E1444 80106044 8FBBFFF8 */  lw         $k1, -0x8($sp) /* handwritten instruction */
    /* E1448 80106048 8FBAFFF0 */  lw         $k0, -0x10($sp) /* handwritten instruction */
    /* E144C 8010604C 42000018 */  eret /* handwritten instruction */
endlabel __ptException
.size __ptException, . - __ptException
    /* E1450 80106050 00000000 */  nop

/* Handwritten function */
nonmatching __osException, 0x940

glabel __osException
    /* E1454 80106054 3C1A8017 */  lui        $k0, %hi(__osThreadSave) /* handwritten instruction */
    /* E1458 80106058 275AF6E8 */  addiu      $k0, $k0, %lo(__osThreadSave) /* handwritten instruction */
    /* E145C 8010605C FF410020 */  sd         $at, 0x20($k0) /* handwritten instruction */
    /* E1460 80106060 401B6000 */  mfc0       $k1, $12 /* handwritten instruction */
    /* E1464 80106064 AF5B0118 */  sw         $k1, 0x118($k0) /* handwritten instruction */
    /* E1468 80106068 2401FFFC */  addiu      $at, $zero, -0x4
    /* E146C 8010606C 0361D824 */  and        $k1, $k1, $at
    /* E1470 80106070 409B6000 */  mtc0       $k1, $12 /* handwritten instruction */
    /* E1474 80106074 FF480058 */  sd         $t0, 0x58($k0) /* handwritten instruction */
    /* E1478 80106078 FF490060 */  sd         $t1, 0x60($k0) /* handwritten instruction */
    /* E147C 8010607C FF4A0068 */  sd         $t2, 0x68($k0) /* handwritten instruction */
    /* E1480 80106080 AF400018 */  sw         $zero, 0x18($k0) /* handwritten instruction */
    /* E1484 80106084 40086800 */  mfc0       $t0, $13 /* handwritten instruction */
    /* E1488 80106088 3C0A8017 */  lui        $t2, %hi(__kmc_pt_mode)
    /* E148C 8010608C 8D4AF6E4 */  lw         $t2, %lo(__kmc_pt_mode)($t2)
    /* E1490 80106090 154000DD */  bnez       $t2, .L80106408
    /* E1494 80106094 00000000 */   nop
    /* E1498 80106098 3109007C */  andi       $t1, $t0, 0x7C
    /* E149C 8010609C 240A0000 */  addiu      $t2, $zero, 0x0
    /* E14A0 801060A0 152A00D9 */  bne        $t1, $t2, .L80106408
    /* E14A4 801060A4 00000000 */   nop
    /* E14A8 801060A8 03684824 */  and        $t1, $k1, $t0
    /* E14AC 801060AC 312A4000 */  andi       $t2, $t1, 0x4000
    /* E14B0 801060B0 114000A3 */  beqz       $t2, .L80106340
    /* E14B4 801060B4 00000000 */   nop
    /* E14B8 801060B8 3C09C000 */  lui        $t1, (0xC0000008 >> 16)
    /* E14BC 801060BC 35290008 */  ori        $t1, $t1, (0xC0000008 & 0xFFFF)
    /* E14C0 801060C0 AD200000 */  sw         $zero, 0x0($t1)
  .L801060C4:
    /* E14C4 801060C4 40086800 */  mfc0       $t0, $13 /* handwritten instruction */
    /* E14C8 801060C8 31084000 */  andi       $t0, $t0, 0x4000
    /* E14CC 801060CC 1408FFFD */  bne        $zero, $t0, .L801060C4
    /* E14D0 801060D0 00000000 */   nop
    /* E14D4 801060D4 3C0AC000 */  lui        $t2, (0xC0000000 >> 16)
    /* E14D8 801060D8 8D480000 */  lw         $t0, (0xC0000000 & 0xFFFF)($t2)
    /* E14DC 801060DC 00084E82 */  srl        $t1, $t0, 26
    /* E14E0 801060E0 3129003F */  andi       $t1, $t1, 0x3F
    /* E14E4 801060E4 240A0010 */  addiu      $t2, $zero, 0x10
    /* E14E8 801060E8 112A0041 */  beq        $t1, $t2, .L801061F0
    /* E14EC 801060EC 00000000 */   nop
    /* E14F0 801060F0 240A000E */  addiu      $t2, $zero, 0xE
    /* E14F4 801060F4 112A0066 */  beq        $t1, $t2, .L80106290
    /* E14F8 801060F8 00000000 */   nop
    /* E14FC 801060FC 240A0014 */  addiu      $t2, $zero, 0x14
    /* E1500 80106100 112A0022 */  beq        $t1, $t2, .L8010618C
    /* E1504 80106104 00000000 */   nop
    /* E1508 80106108 240A000F */  addiu      $t2, $zero, 0xF
    /* E150C 8010610C 112A0022 */  beq        $t1, $t2, .L80106198
    /* E1510 80106110 00000000 */   nop
    /* E1514 80106114 240A0011 */  addiu      $t2, $zero, 0x11
    /* E1518 80106118 112A0025 */  beq        $t1, $t2, .L801061B0
    /* E151C 8010611C 00000000 */   nop
    /* E1520 80106120 240A000D */  addiu      $t2, $zero, 0xD
    /* E1524 80106124 112A0026 */  beq        $t1, $t2, .L801061C0
    /* E1528 80106128 00000000 */   nop
    /* E152C 8010612C 240A0012 */  addiu      $t2, $zero, 0x12
    /* E1530 80106130 112A0027 */  beq        $t1, $t2, .L801061D0
    /* E1534 80106134 00000000 */   nop
    /* E1538 80106138 240A0013 */  addiu      $t2, $zero, 0x13
    /* E153C 8010613C 112A0028 */  beq        $t1, $t2, .L801061E0
    /* E1540 80106140 00000000 */   nop
    /* E1544 80106144 240A0015 */  addiu      $t2, $zero, 0x15
    /* E1548 80106148 112A0003 */  beq        $t1, $t2, .L80106158
    /* E154C 8010614C 00000000 */   nop
    /* E1550 80106150 100000A2 */  b          .L801063DC
    /* E1554 80106154 00000000 */   nop
  .L80106158:
    /* E1558 80106158 240A0001 */  addiu      $t2, $zero, 0x1
    /* E155C 8010615C 00084C02 */  srl        $t1, $t0, 16
    /* E1560 80106160 312900FF */  andi       $t1, $t1, 0xFF
    /* E1564 80106164 112A0005 */  beq        $t1, $t2, .L8010617C
    /* E1568 80106168 00000000 */   nop
    /* E156C 8010616C 240A00A8 */  addiu      $t2, $zero, 0xA8
    /* E1570 80106170 3C018012 */  lui        $at, %hi(D_8011E204)
    /* E1574 80106174 100000A4 */  b          .L80106408
    /* E1578 80106178 AC2AE204 */   sw        $t2, %lo(D_8011E204)($at)
  .L8010617C:
    /* E157C 8010617C 240A00B0 */  addiu      $t2, $zero, 0xB0
    /* E1580 80106180 3C018012 */  lui        $at, %hi(D_8011E204)
    /* E1584 80106184 100000A0 */  b          .L80106408
    /* E1588 80106188 AC2AE204 */   sw        $t2, %lo(D_8011E204)($at)
  .L8010618C:
    /* E158C 8010618C 3C018012 */  lui        $at, %hi(D_8011E208)
    /* E1590 80106190 1000009D */  b          .L80106408
    /* E1594 80106194 AC28E208 */   sw        $t0, %lo(D_8011E208)($at)
  .L80106198:
    /* E1598 80106198 3C0A00FF */  lui        $t2, (0xFFFFFF >> 16)
    /* E159C 8010619C 354AFFFF */  ori        $t2, $t2, (0xFFFFFF & 0xFFFF)
    /* E15A0 801061A0 010A4824 */  and        $t1, $t0, $t2
    /* E15A4 801061A4 3C018012 */  lui        $at, %hi(D_8011E200)
    /* E15A8 801061A8 1000008C */  b          .L801063DC
    /* E15AC 801061AC AC29E200 */   sw        $t1, %lo(D_8011E200)($at)
  .L801061B0:
    /* E15B0 801061B0 240A0088 */  addiu      $t2, $zero, 0x88
    /* E15B4 801061B4 3C018012 */  lui        $at, %hi(D_8011E204)
    /* E15B8 801061B8 10000093 */  b          .L80106408
    /* E15BC 801061BC AC2AE204 */   sw        $t2, %lo(D_8011E204)($at)
  .L801061C0:
    /* E15C0 801061C0 240A0080 */  addiu      $t2, $zero, 0x80
    /* E15C4 801061C4 3C018012 */  lui        $at, %hi(D_8011E204)
    /* E15C8 801061C8 1000008F */  b          .L80106408
    /* E15CC 801061CC AC2AE204 */   sw        $t2, %lo(D_8011E204)($at)
  .L801061D0:
    /* E15D0 801061D0 240A0090 */  addiu      $t2, $zero, 0x90
    /* E15D4 801061D4 3C018012 */  lui        $at, %hi(D_8011E204)
    /* E15D8 801061D8 1000008B */  b          .L80106408
    /* E15DC 801061DC AC2AE204 */   sw        $t2, %lo(D_8011E204)($at)
  .L801061E0:
    /* E15E0 801061E0 240A0098 */  addiu      $t2, $zero, 0x98
    /* E15E4 801061E4 3C018012 */  lui        $at, %hi(D_8011E204)
    /* E15E8 801061E8 10000087 */  b          .L80106408
    /* E15EC 801061EC AC2AE204 */   sw        $t2, %lo(D_8011E204)($at)
  .L801061F0:
    /* E15F0 801061F0 00084E02 */  srl        $t1, $t0, 24
    /* E15F4 801061F4 31290003 */  andi       $t1, $t1, 0x3
    /* E15F8 801061F8 10090078 */  beq        $zero, $t1, .L801063DC
    /* E15FC 801061FC 00000000 */   nop
    /* E1600 80106200 3C0A8019 */  lui        $t2, %hi(__osRdb_Read_Data_Ct)
    /* E1604 80106204 8D4A8F64 */  lw         $t2, %lo(__osRdb_Read_Data_Ct)($t2)
    /* E1608 80106208 01495023 */  subu       $t2, $t2, $t1
    /* E160C 8010620C 3C018019 */  lui        $at, %hi(__osRdb_Read_Data_Ct)
    /* E1610 80106210 AC2A8F64 */  sw         $t2, %lo(__osRdb_Read_Data_Ct)($at)
    /* E1614 80106214 FF4B0070 */  sd         $t3, 0x70($k0) /* handwritten instruction */
    /* E1618 80106218 3C0B8020 */  lui        $t3, %hi(__osRdb_Read_Data_Buf)
    /* E161C 8010621C 8D6B5628 */  lw         $t3, %lo(__osRdb_Read_Data_Buf)($t3)
    /* E1620 80106220 00085402 */  srl        $t2, $t0, 16
    /* E1624 80106224 314A00FF */  andi       $t2, $t2, 0xFF
    /* E1628 80106228 A16A0000 */  sb         $t2, 0x0($t3)
    /* E162C 8010622C 216B0001 */  addi       $t3, $t3, 0x1 /* handwritten instruction */
    /* E1630 80106230 2129FFFF */  addi       $t1, $t1, -0x1 /* handwritten instruction */
    /* E1634 80106234 1009000B */  beq        $zero, $t1, .L80106264
    /* E1638 80106238 00000000 */   nop
    /* E163C 8010623C 00085202 */  srl        $t2, $t0, 8
    /* E1640 80106240 314A00FF */  andi       $t2, $t2, 0xFF
    /* E1644 80106244 A16A0000 */  sb         $t2, 0x0($t3)
    /* E1648 80106248 216B0001 */  addi       $t3, $t3, 0x1 /* handwritten instruction */
    /* E164C 8010624C 2129FFFF */  addi       $t1, $t1, -0x1 /* handwritten instruction */
    /* E1650 80106250 10090004 */  beq        $zero, $t1, .L80106264
    /* E1654 80106254 00000000 */   nop
    /* E1658 80106258 310800FF */  andi       $t0, $t0, 0xFF
    /* E165C 8010625C A1680000 */  sb         $t0, 0x0($t3)
    /* E1660 80106260 216B0001 */  addi       $t3, $t3, 0x1 /* handwritten instruction */
  .L80106264:
    /* E1664 80106264 3C018020 */  lui        $at, %hi(__osRdb_Read_Data_Buf)
    /* E1668 80106268 AC2B5628 */  sw         $t3, %lo(__osRdb_Read_Data_Buf)($at)
    /* E166C 8010626C DF4B0070 */  ld         $t3, 0x70($k0) /* handwritten instruction */
    /* E1670 80106270 3C0A8019 */  lui        $t2, %hi(__osRdb_Read_Data_Ct)
    /* E1674 80106274 8D4A8F64 */  lw         $t2, %lo(__osRdb_Read_Data_Ct)($t2)
    /* E1678 80106278 140A0058 */  bne        $zero, $t2, .L801063DC
    /* E167C 8010627C 00000000 */   nop
    /* E1680 80106280 240A0078 */  addiu      $t2, $zero, 0x78
    /* E1684 80106284 3C018012 */  lui        $at, %hi(D_8011E204)
    /* E1688 80106288 1000005F */  b          .L80106408
    /* E168C 8010628C AC2AE204 */   sw        $t2, %lo(D_8011E204)($at)
  .L80106290:
    /* E1690 80106290 00084E02 */  srl        $t1, $t0, 24
    /* E1694 80106294 31290003 */  andi       $t1, $t1, 0x3
    /* E1698 80106298 10090050 */  beq        $zero, $t1, .L801063DC
    /* E169C 8010629C 00000000 */   nop
    /* E16A0 801062A0 3C0A8012 */  lui        $t2, %hi(D_8011E200)
    /* E16A4 801062A4 8D4AE200 */  lw         $t2, %lo(D_8011E200)($t2)
    /* E16A8 801062A8 01495023 */  subu       $t2, $t2, $t1
    /* E16AC 801062AC 3C018012 */  lui        $at, %hi(D_8011E200)
    /* E16B0 801062B0 AC2AE200 */  sw         $t2, %lo(D_8011E200)($at)
    /* E16B4 801062B4 FF4B0070 */  sd         $t3, 0x70($k0) /* handwritten instruction */
    /* E16B8 801062B8 3C0B8014 */  lui        $t3, %hi(__osRdb_DbgRead_Buf)
    /* E16BC 801062BC 8D6BD5E8 */  lw         $t3, %lo(__osRdb_DbgRead_Buf)($t3)
    /* E16C0 801062C0 140B0003 */  bne        $zero, $t3, .L801062D0
    /* E16C4 801062C4 00000000 */   nop
    /* E16C8 801062C8 10000044 */  b          .L801063DC
    /* E16CC 801062CC DF4B0070 */   ld        $t3, 0x70($k0) /* handwritten instruction */
  .L801062D0:
    /* E16D0 801062D0 00085402 */  srl        $t2, $t0, 16
    /* E16D4 801062D4 314A00FF */  andi       $t2, $t2, 0xFF
    /* E16D8 801062D8 A16A0000 */  sb         $t2, 0x0($t3)
    /* E16DC 801062DC 216B0001 */  addi       $t3, $t3, 0x1 /* handwritten instruction */
    /* E16E0 801062E0 2129FFFF */  addi       $t1, $t1, -0x1 /* handwritten instruction */
    /* E16E4 801062E4 1009000B */  beq        $zero, $t1, .L80106314
    /* E16E8 801062E8 00000000 */   nop
    /* E16EC 801062EC 00085202 */  srl        $t2, $t0, 8
    /* E16F0 801062F0 314A00FF */  andi       $t2, $t2, 0xFF
    /* E16F4 801062F4 A16A0000 */  sb         $t2, 0x0($t3)
    /* E16F8 801062F8 216B0001 */  addi       $t3, $t3, 0x1 /* handwritten instruction */
    /* E16FC 801062FC 2129FFFF */  addi       $t1, $t1, -0x1 /* handwritten instruction */
    /* E1700 80106300 10090004 */  beq        $zero, $t1, .L80106314
    /* E1704 80106304 00000000 */   nop
    /* E1708 80106308 310800FF */  andi       $t0, $t0, 0xFF
    /* E170C 8010630C A1680000 */  sb         $t0, 0x0($t3)
    /* E1710 80106310 216B0001 */  addi       $t3, $t3, 0x1 /* handwritten instruction */
  .L80106314:
    /* E1714 80106314 3C018014 */  lui        $at, %hi(__osRdb_DbgRead_Buf)
    /* E1718 80106318 AC2BD5E8 */  sw         $t3, %lo(__osRdb_DbgRead_Buf)($at)
    /* E171C 8010631C DF4B0070 */  ld         $t3, 0x70($k0) /* handwritten instruction */
    /* E1720 80106320 3C0A8012 */  lui        $t2, %hi(D_8011E200)
    /* E1724 80106324 8D4AE200 */  lw         $t2, %lo(D_8011E200)($t2)
    /* E1728 80106328 140A002C */  bne        $zero, $t2, .L801063DC
    /* E172C 8010632C 00000000 */   nop
    /* E1730 80106330 240A00A0 */  addiu      $t2, $zero, 0xA0
    /* E1734 80106334 3C018012 */  lui        $at, %hi(D_8011E204)
    /* E1738 80106338 10000033 */  b          .L80106408
    /* E173C 8010633C AC2AE204 */   sw        $t2, %lo(D_8011E204)($at)
  .L80106340:
    /* E1740 80106340 312A2000 */  andi       $t2, $t1, 0x2000
    /* E1744 80106344 11400030 */  beqz       $t2, .L80106408
    /* E1748 80106348 00000000 */   nop
    /* E174C 8010634C 3C09C000 */  lui        $t1, (0xC000000C >> 16)
    /* E1750 80106350 3529000C */  ori        $t1, $t1, (0xC000000C & 0xFFFF)
    /* E1754 80106354 AD200000 */  sw         $zero, 0x0($t1)
    /* E1758 80106358 3C0A8023 */  lui        $t2, %hi(__osRdb_IP6_Ct)
    /* E175C 8010635C 8D4A73EC */  lw         $t2, %lo(__osRdb_IP6_Ct)($t2)
    /* E1760 80106360 15400005 */  bnez       $t2, .L80106378
    /* E1764 80106364 00000000 */   nop
    /* E1768 80106368 240A0001 */  addiu      $t2, $zero, 0x1
    /* E176C 8010636C 3C018012 */  lui        $at, %hi(__osRdb_IP6_Empty)
    /* E1770 80106370 1000001A */  b          .L801063DC
    /* E1774 80106374 AC2AE260 */   sw        $t2, %lo(__osRdb_IP6_Empty)($at)
  .L80106378:
    /* E1778 80106378 214AFFFF */  addi       $t2, $t2, -0x1 /* handwritten instruction */
    /* E177C 8010637C 3C018023 */  lui        $at, %hi(__osRdb_IP6_Ct)
    /* E1780 80106380 AC2A73EC */  sw         $t2, %lo(__osRdb_IP6_Ct)($at)
    /* E1784 80106384 3C088022 */  lui        $t0, %hi(__osRdb_IP6_Data)
    /* E1788 80106388 8D08E6D8 */  lw         $t0, %lo(__osRdb_IP6_Data)($t0)
    /* E178C 8010638C 3C098020 */  lui        $t1, %hi(__osRdb_IP6_CurSend)
    /* E1790 80106390 8D29B9C8 */  lw         $t1, %lo(__osRdb_IP6_CurSend)($t1)
    /* E1794 80106394 00095080 */  sll        $t2, $t1, 2
    /* E1798 80106398 01484020 */  add        $t0, $t2, $t0 /* handwritten instruction */
    /* E179C 8010639C 8D0A0000 */  lw         $t2, 0x0($t0)
    /* E17A0 801063A0 21290001 */  addi       $t1, $t1, 0x1 /* handwritten instruction */
    /* E17A4 801063A4 3C088019 */  lui        $t0, %hi(__osRdb_IP6_Size)
    /* E17A8 801063A8 8D089818 */  lw         $t0, %lo(__osRdb_IP6_Size)($t0)
    /* E17AC 801063AC 01094022 */  sub        $t0, $t0, $t1 /* handwritten instruction */
    /* E17B0 801063B0 1D000002 */  bgtz       $t0, .L801063BC
    /* E17B4 801063B4 00000000 */   nop
    /* E17B8 801063B8 24090000 */  addiu      $t1, $zero, 0x0
  .L801063BC:
    /* E17BC 801063BC 3C018020 */  lui        $at, %hi(__osRdb_IP6_CurSend)
    /* E17C0 801063C0 AC29B9C8 */  sw         $t1, %lo(__osRdb_IP6_CurSend)($at)
  .L801063C4:
    /* E17C4 801063C4 40086800 */  mfc0       $t0, $13 /* handwritten instruction */
    /* E17C8 801063C8 31082000 */  andi       $t0, $t0, 0x2000
    /* E17CC 801063CC 1408FFFD */  bne        $zero, $t0, .L801063C4
    /* E17D0 801063D0 00000000 */   nop
    /* E17D4 801063D4 3C08C000 */  lui        $t0, (0xC0000000 >> 16)
    /* E17D8 801063D8 AD0A0000 */  sw         $t2, (0xC0000000 & 0xFFFF)($t0)
  .L801063DC:
    /* E17DC 801063DC DF480058 */  ld         $t0, 0x58($k0) /* handwritten instruction */
    /* E17E0 801063E0 DF490060 */  ld         $t1, 0x60($k0) /* handwritten instruction */
    /* E17E4 801063E4 DF4A0068 */  ld         $t2, 0x68($k0) /* handwritten instruction */
    /* E17E8 801063E8 DF410020 */  ld         $at, 0x20($k0) /* handwritten instruction */
    /* E17EC 801063EC 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* E17F0 801063F0 409B6000 */  mtc0       $k1, $12 /* handwritten instruction */
    /* E17F4 801063F4 00000000 */  nop
    /* E17F8 801063F8 00000000 */  nop
    /* E17FC 801063FC 00000000 */  nop
    /* E1800 80106400 00000000 */  nop
    /* E1804 80106404 42000018 */  eret /* handwritten instruction */
  .L80106408:
    /* E1808 80106408 03404021 */  addu       $t0, $k0, $zero
    /* E180C 8010640C 3C1A8012 */  lui        $k0, %hi(__osRunningThread) /* handwritten instruction */
    /* E1810 80106410 8F5ACCF0 */  lw         $k0, %lo(__osRunningThread)($k0) /* handwritten instruction */
    /* E1814 80106414 DD090020 */  ld         $t1, 0x20($t0)
    /* E1818 80106418 FF490020 */  sd         $t1, 0x20($k0) /* handwritten instruction */
    /* E181C 8010641C DD090118 */  ld         $t1, 0x118($t0)
    /* E1820 80106420 FF490118 */  sd         $t1, 0x118($k0) /* handwritten instruction */
    /* E1824 80106424 DD090058 */  ld         $t1, 0x58($t0)
    /* E1828 80106428 FF490058 */  sd         $t1, 0x58($k0) /* handwritten instruction */
    /* E182C 8010642C DD090060 */  ld         $t1, 0x60($t0)
    /* E1830 80106430 FF490060 */  sd         $t1, 0x60($k0) /* handwritten instruction */
    /* E1834 80106434 DD090068 */  ld         $t1, 0x68($t0)
    /* E1838 80106438 FF490068 */  sd         $t1, 0x68($k0) /* handwritten instruction */
    /* E183C 8010643C FF420028 */  sd         $v0, 0x28($k0) /* handwritten instruction */
    /* E1840 80106440 FF430030 */  sd         $v1, 0x30($k0) /* handwritten instruction */
    /* E1844 80106444 FF440038 */  sd         $a0, 0x38($k0) /* handwritten instruction */
    /* E1848 80106448 FF450040 */  sd         $a1, 0x40($k0) /* handwritten instruction */
    /* E184C 8010644C FF460048 */  sd         $a2, 0x48($k0) /* handwritten instruction */
    /* E1850 80106450 FF470050 */  sd         $a3, 0x50($k0) /* handwritten instruction */
    /* E1854 80106454 FF4B0070 */  sd         $t3, 0x70($k0) /* handwritten instruction */
    /* E1858 80106458 FF4C0078 */  sd         $t4, 0x78($k0) /* handwritten instruction */
    /* E185C 8010645C FF4D0080 */  sd         $t5, 0x80($k0) /* handwritten instruction */
    /* E1860 80106460 FF4E0088 */  sd         $t6, 0x88($k0) /* handwritten instruction */
    /* E1864 80106464 FF4F0090 */  sd         $t7, 0x90($k0) /* handwritten instruction */
    /* E1868 80106468 FF500098 */  sd         $s0, 0x98($k0) /* handwritten instruction */
    /* E186C 8010646C FF5100A0 */  sd         $s1, 0xA0($k0) /* handwritten instruction */
    /* E1870 80106470 FF5200A8 */  sd         $s2, 0xA8($k0) /* handwritten instruction */
    /* E1874 80106474 FF5300B0 */  sd         $s3, 0xB0($k0) /* handwritten instruction */
    /* E1878 80106478 FF5400B8 */  sd         $s4, 0xB8($k0) /* handwritten instruction */
    /* E187C 8010647C FF5500C0 */  sd         $s5, 0xC0($k0) /* handwritten instruction */
    /* E1880 80106480 FF5600C8 */  sd         $s6, 0xC8($k0) /* handwritten instruction */
    /* E1884 80106484 FF5700D0 */  sd         $s7, 0xD0($k0) /* handwritten instruction */
    /* E1888 80106488 FF5800D8 */  sd         $t8, 0xD8($k0) /* handwritten instruction */
    /* E188C 8010648C FF5900E0 */  sd         $t9, 0xE0($k0) /* handwritten instruction */
    /* E1890 80106490 FF5C00E8 */  sd         $gp, 0xE8($k0) /* handwritten instruction */
    /* E1894 80106494 FF5D00F0 */  sd         $sp, 0xF0($k0) /* handwritten instruction */
    /* E1898 80106498 FF5E00F8 */  sd         $fp, 0xF8($k0) /* handwritten instruction */
    /* E189C 8010649C FF5F0100 */  sd         $ra, 0x100($k0) /* handwritten instruction */
    /* E18A0 801064A0 00004012 */  mflo       $t0
    /* E18A4 801064A4 FF480108 */  sd         $t0, 0x108($k0) /* handwritten instruction */
    /* E18A8 801064A8 00004010 */  mfhi       $t0
    /* E18AC 801064AC FF480110 */  sd         $t0, 0x110($k0) /* handwritten instruction */
    /* E18B0 801064B0 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* E18B4 801064B4 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
    /* E18B8 801064B8 11200013 */  beqz       $t1, .L80106508
    /* E18BC 801064BC 00000000 */   nop
    /* E18C0 801064C0 3C088012 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* E18C4 801064C4 2508E220 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* E18C8 801064C8 8D080000 */  lw         $t0, 0x0($t0)
    /* E18CC 801064CC 2401FFFF */  addiu      $at, $zero, -0x1
    /* E18D0 801064D0 01015026 */  xor        $t2, $t0, $at
    /* E18D4 801064D4 314AFF00 */  andi       $t2, $t2, 0xFF00
    /* E18D8 801064D8 012A6025 */  or         $t4, $t1, $t2
    /* E18DC 801064DC 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* E18E0 801064E0 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* E18E4 801064E4 03615824 */  and        $t3, $k1, $at
    /* E18E8 801064E8 016C5825 */  or         $t3, $t3, $t4
    /* E18EC 801064EC AF4B0118 */  sw         $t3, 0x118($k0) /* handwritten instruction */
    /* E18F0 801064F0 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* E18F4 801064F4 01284824 */  and        $t1, $t1, $t0
    /* E18F8 801064F8 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* E18FC 801064FC 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* E1900 80106500 0361D824 */  and        $k1, $k1, $at
    /* E1904 80106504 0369D825 */  or         $k1, $k1, $t1
  .L80106508:
    /* E1908 80106508 3C09A430 */  lui        $t1, %hi(D_A430000C)
    /* E190C 8010650C 8D29000C */  lw         $t1, %lo(D_A430000C)($t1)
    /* E1910 80106510 1120000B */  beqz       $t1, .L80106540
    /* E1914 80106514 00000000 */   nop
    /* E1918 80106518 3C088012 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* E191C 8010651C 2508E220 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* E1920 80106520 8D080000 */  lw         $t0, 0x0($t0)
    /* E1924 80106524 00084402 */  srl        $t0, $t0, 16
    /* E1928 80106528 2401FFFF */  addiu      $at, $zero, -0x1
    /* E192C 8010652C 01014026 */  xor        $t0, $t0, $at
    /* E1930 80106530 3108003F */  andi       $t0, $t0, 0x3F
    /* E1934 80106534 8F4C0128 */  lw         $t4, 0x128($k0) /* handwritten instruction */
    /* E1938 80106538 010C4024 */  and        $t0, $t0, $t4
    /* E193C 8010653C 01284825 */  or         $t1, $t1, $t0
  .L80106540:
    /* E1940 80106540 AF490128 */  sw         $t1, 0x128($k0) /* handwritten instruction */
    /* E1944 80106544 40087000 */  mfc0       $t0, $14 /* handwritten instruction */
    /* E1948 80106548 AF48011C */  sw         $t0, 0x11C($k0) /* handwritten instruction */
    /* E194C 8010654C 8F480018 */  lw         $t0, 0x18($k0) /* handwritten instruction */
    /* E1950 80106550 11000014 */  beqz       $t0, .L801065A4
    /* E1954 80106554 00000000 */   nop
    /* E1958 80106558 4448F800 */  cfc1       $t0, $31
    /* E195C 8010655C 00000000 */  nop
    /* E1960 80106560 AF48012C */  sw         $t0, 0x12C($k0) /* handwritten instruction */
    /* E1964 80106564 F7400130 */  sdc1       $f0, 0x130($k0)
    /* E1968 80106568 F7420138 */  sdc1       $f2, 0x138($k0)
    /* E196C 8010656C F7440140 */  sdc1       $f4, 0x140($k0)
    /* E1970 80106570 F7460148 */  sdc1       $f6, 0x148($k0)
    /* E1974 80106574 F7480150 */  sdc1       $f8, 0x150($k0)
    /* E1978 80106578 F74A0158 */  sdc1       $f10, 0x158($k0)
    /* E197C 8010657C F74C0160 */  sdc1       $f12, 0x160($k0)
    /* E1980 80106580 F74E0168 */  sdc1       $f14, 0x168($k0)
    /* E1984 80106584 F7500170 */  sdc1       $f16, 0x170($k0)
    /* E1988 80106588 F7520178 */  sdc1       $f18, 0x178($k0)
    /* E198C 8010658C F7540180 */  sdc1       $f20, 0x180($k0)
    /* E1990 80106590 F7560188 */  sdc1       $f22, 0x188($k0)
    /* E1994 80106594 F7580190 */  sdc1       $f24, 0x190($k0)
    /* E1998 80106598 F75A0198 */  sdc1       $f26, 0x198($k0)
    /* E199C 8010659C F75C01A0 */  sdc1       $f28, 0x1A0($k0)
    /* E19A0 801065A0 F75E01A8 */  sdc1       $f30, 0x1A8($k0)
  .L801065A4:
    /* E19A4 801065A4 40086800 */  mfc0       $t0, $13 /* handwritten instruction */
    /* E19A8 801065A8 AF480120 */  sw         $t0, 0x120($k0) /* handwritten instruction */
    /* E19AC 801065AC 24090002 */  addiu      $t1, $zero, 0x2
    /* E19B0 801065B0 A7490010 */  sh         $t1, 0x10($k0) /* handwritten instruction */
    /* E19B4 801065B4 3C048012 */  lui        $a0, %hi(D_8011E208)
    /* E19B8 801065B8 8C84E208 */  lw         $a0, %lo(D_8011E208)($a0)
    /* E19BC 801065BC 10800006 */  beqz       $a0, .L801065D8
    /* E19C0 801065C0 00000000 */   nop
    /* E19C4 801065C4 3C018012 */  lui        $at, %hi(D_8011E208)
    /* E19C8 801065C8 0C041E56 */  jal        kdebugserver
    /* E19CC 801065CC AC20E208 */   sw        $zero, %lo(D_8011E208)($at)
    /* E19D0 801065D0 1000018C */  b          .L80106C04
    /* E19D4 801065D4 00000000 */   nop
  .L801065D8:
    /* E19D8 801065D8 3C048012 */  lui        $a0, %hi(D_8011E204)
    /* E19DC 801065DC 8C84E204 */  lw         $a0, %lo(D_8011E204)($a0)
    /* E19E0 801065E0 10800005 */  beqz       $a0, .L801065F8
    /* E19E4 801065E4 00000000 */   nop
    /* E19E8 801065E8 3C018012 */  lui        $at, %hi(D_8011E204)
    /* E19EC 801065EC 0C041A65 */  jal        send_mesg
    /* E19F0 801065F0 AC20E204 */   sw        $zero, %lo(D_8011E204)($at)
    /* E19F4 801065F4 8F480120 */  lw         $t0, 0x120($k0) /* handwritten instruction */
  .L801065F8:
    /* E19F8 801065F8 3109007C */  andi       $t1, $t0, 0x7C
    /* E19FC 801065FC 240A0024 */  addiu      $t2, $zero, 0x24
    /* E1A00 80106600 112A00BF */  beq        $t1, $t2, .L80106900
    /* E1A04 80106604 00000000 */   nop
    /* E1A08 80106608 240A002C */  addiu      $t2, $zero, 0x2C
    /* E1A0C 8010660C 112A0110 */  beq        $t1, $t2, handle_CpU
    /* E1A10 80106610 00000000 */   nop
    /* E1A14 80106614 240A0000 */  addiu      $t2, $zero, 0x0
    /* E1A18 80106618 152A00D2 */  bne        $t1, $t2, .L80106964
    /* E1A1C 8010661C 00000000 */   nop
    /* E1A20 80106620 03688024 */  and        $s0, $k1, $t0
  .L80106624:
    /* E1A24 80106624 3209FF00 */  andi       $t1, $s0, 0xFF00
    /* E1A28 80106628 00095302 */  srl        $t2, $t1, 12
    /* E1A2C 8010662C 15400003 */  bnez       $t2, .L8010663C
    /* E1A30 80106630 00000000 */   nop
    /* E1A34 80106634 00095202 */  srl        $t2, $t1, 8
    /* E1A38 80106638 214A0010 */  addi       $t2, $t2, 0x10 /* handwritten instruction */
  .L8010663C:
    /* E1A3C 8010663C 3C018012 */  lui        $at, %hi(D_80123E90)
    /* E1A40 80106640 002A0821 */  addu       $at, $at, $t2
    /* E1A44 80106644 902A3E90 */  lbu        $t2, %lo(D_80123E90)($at)
    /* E1A48 80106648 3C018012 */  lui        $at, %hi(jtbl_80123EB0)
    /* E1A4C 8010664C 002A0821 */  addu       $at, $at, $t2
    /* E1A50 80106650 8C2A3EB0 */  lw         $t2, %lo(jtbl_80123EB0)($at)
    /* E1A54 80106654 01400008 */  jr         $t2
    /* E1A58 80106658 00000000 */   nop
  jlabel .L8010665C
    /* E1A5C 8010665C 2401DFFF */  addiu      $at, $zero, -0x2001
    /* E1A60 80106660 1000FFF0 */  b          .L80106624
    /* E1A64 80106664 02018024 */   and       $s0, $s0, $at
  jlabel .L80106668
    /* E1A68 80106668 2401BFFF */  addiu      $at, $zero, -0x4001
    /* E1A6C 8010666C 1000FFED */  b          .L80106624
    /* E1A70 80106670 02018024 */   and       $s0, $s0, $at
  jlabel .L80106674
    /* E1A74 80106674 40095800 */  mfc0       $t1, $11 /* handwritten instruction */
    /* E1A78 80106678 40895800 */  mtc0       $t1, $11 /* handwritten instruction */
    /* E1A7C 8010667C 24040018 */  addiu      $a0, $zero, 0x18
    /* E1A80 80106680 0C041A65 */  jal        send_mesg
    /* E1A84 80106684 00000000 */   nop
    /* E1A88 80106688 3C01FFFF */  lui        $at, (0xFFFF7FFF >> 16)
    /* E1A8C 8010668C 34217FFF */  ori        $at, $at, (0xFFFF7FFF & 0xFFFF)
    /* E1A90 80106690 1000FFE4 */  b          .L80106624
    /* E1A94 80106694 02018024 */   and       $s0, $s0, $at
  jlabel .L80106698
    /* E1A98 80106698 2401F7FF */  addiu      $at, $zero, -0x801
    /* E1A9C 8010669C 02018024 */  and        $s0, $s0, $at
    /* E1AA0 801066A0 3C098012 */  lui        $t1, %hi(D_8011E1D0)
    /* E1AA4 801066A4 2529E1D0 */  addiu      $t1, $t1, %lo(D_8011E1D0)
    /* E1AA8 801066A8 21290008 */  addi       $t1, $t1, 0x8 /* handwritten instruction */
    /* E1AAC 801066AC 8D2A0000 */  lw         $t2, 0x0($t1)
    /* E1AB0 801066B0 11400007 */  beqz       $t2, .L801066D0
    /* E1AB4 801066B4 00000000 */   nop
    /* E1AB8 801066B8 0140F809 */  jalr       $t2
    /* E1ABC 801066BC 8D3D0004 */   lw        $sp, 0x4($t1)
    /* E1AC0 801066C0 10400003 */  beqz       $v0, .L801066D0
    /* E1AC4 801066C4 00000000 */   nop
    /* E1AC8 801066C8 10000093 */  b          .L80106918
    /* E1ACC 801066CC 00000000 */   nop
  .L801066D0:
    /* E1AD0 801066D0 0C041A65 */  jal        send_mesg
    /* E1AD4 801066D4 24040010 */   addiu     $a0, $zero, 0x10
    /* E1AD8 801066D8 1000FFD2 */  b          .L80106624
    /* E1ADC 801066DC 00000000 */   nop
  jlabel .L801066E0
    /* E1AE0 801066E0 3C11A430 */  lui        $s1, %hi(D_A4300008)
    /* E1AE4 801066E4 8E310008 */  lw         $s1, %lo(D_A4300008)($s1)
    /* E1AE8 801066E8 3C088012 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* E1AEC 801066EC 2508E220 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* E1AF0 801066F0 8D080000 */  lw         $t0, 0x0($t0)
    /* E1AF4 801066F4 00084402 */  srl        $t0, $t0, 16
    /* E1AF8 801066F8 02288824 */  and        $s1, $s1, $t0
    /* E1AFC 801066FC 32290001 */  andi       $t1, $s1, 0x1
    /* E1B00 80106700 11200014 */  beqz       $t1, .L80106754
    /* E1B04 80106704 00000000 */   nop
    /* E1B08 80106708 3231003E */  andi       $s1, $s1, 0x3E
    /* E1B0C 8010670C 3C0CA404 */  lui        $t4, %hi(D_A4040010)
    /* E1B10 80106710 8D8C0010 */  lw         $t4, %lo(D_A4040010)($t4)
    /* E1B14 80106714 34098008 */  ori        $t1, $zero, 0x8008
    /* E1B18 80106718 3C01A404 */  lui        $at, %hi(D_A4040010)
    /* E1B1C 8010671C AC290010 */  sw         $t1, %lo(D_A4040010)($at)
    /* E1B20 80106720 318C0300 */  andi       $t4, $t4, 0x300
    /* E1B24 80106724 11800007 */  beqz       $t4, .L80106744
    /* E1B28 80106728 00000000 */   nop
    /* E1B2C 8010672C 0C041A65 */  jal        send_mesg
    /* E1B30 80106730 24040020 */   addiu     $a0, $zero, 0x20
    /* E1B34 80106734 12200044 */  beqz       $s1, .L80106848
    /* E1B38 80106738 00000000 */   nop
    /* E1B3C 8010673C 10000005 */  b          .L80106754
    /* E1B40 80106740 00000000 */   nop
  .L80106744:
    /* E1B44 80106744 0C041A65 */  jal        send_mesg
    /* E1B48 80106748 24040058 */   addiu     $a0, $zero, 0x58
    /* E1B4C 8010674C 1220003E */  beqz       $s1, .L80106848
    /* E1B50 80106750 00000000 */   nop
  .L80106754:
    /* E1B54 80106754 32290008 */  andi       $t1, $s1, 0x8
    /* E1B58 80106758 11200008 */  beqz       $t1, .L8010677C
    /* E1B5C 8010675C 00000000 */   nop
    /* E1B60 80106760 32310037 */  andi       $s1, $s1, 0x37
    /* E1B64 80106764 3C01A440 */  lui        $at, %hi(D_A4400010)
    /* E1B68 80106768 AC200010 */  sw         $zero, %lo(D_A4400010)($at)
    /* E1B6C 8010676C 0C041A65 */  jal        send_mesg
    /* E1B70 80106770 24040038 */   addiu     $a0, $zero, 0x38
    /* E1B74 80106774 12200034 */  beqz       $s1, .L80106848
    /* E1B78 80106778 00000000 */   nop
  .L8010677C:
    /* E1B7C 8010677C 32290004 */  andi       $t1, $s1, 0x4
    /* E1B80 80106780 11200009 */  beqz       $t1, .L801067A8
    /* E1B84 80106784 00000000 */   nop
    /* E1B88 80106788 3231003B */  andi       $s1, $s1, 0x3B
    /* E1B8C 8010678C 24090001 */  addiu      $t1, $zero, 0x1
    /* E1B90 80106790 3C01A450 */  lui        $at, %hi(D_A450000C)
    /* E1B94 80106794 AC29000C */  sw         $t1, %lo(D_A450000C)($at)
    /* E1B98 80106798 0C041A65 */  jal        send_mesg
    /* E1B9C 8010679C 24040030 */   addiu     $a0, $zero, 0x30
    /* E1BA0 801067A0 12200029 */  beqz       $s1, .L80106848
    /* E1BA4 801067A4 00000000 */   nop
  .L801067A8:
    /* E1BA8 801067A8 32290002 */  andi       $t1, $s1, 0x2
    /* E1BAC 801067AC 11200008 */  beqz       $t1, .L801067D0
    /* E1BB0 801067B0 00000000 */   nop
    /* E1BB4 801067B4 3231003D */  andi       $s1, $s1, 0x3D
    /* E1BB8 801067B8 3C01A480 */  lui        $at, %hi(D_A4800018)
    /* E1BBC 801067BC AC200018 */  sw         $zero, %lo(D_A4800018)($at)
    /* E1BC0 801067C0 0C041A65 */  jal        send_mesg
    /* E1BC4 801067C4 24040028 */   addiu     $a0, $zero, 0x28
    /* E1BC8 801067C8 1220001F */  beqz       $s1, .L80106848
    /* E1BCC 801067CC 00000000 */   nop
  .L801067D0:
    /* E1BD0 801067D0 32290010 */  andi       $t1, $s1, 0x10
    /* E1BD4 801067D4 11200013 */  beqz       $t1, .L80106824
    /* E1BD8 801067D8 00000000 */   nop
    /* E1BDC 801067DC 3231002F */  andi       $s1, $s1, 0x2F
    /* E1BE0 801067E0 24090002 */  addiu      $t1, $zero, 0x2
    /* E1BE4 801067E4 3C01A460 */  lui        $at, %hi(D_A4600010)
    /* E1BE8 801067E8 AC290010 */  sw         $t1, %lo(D_A4600010)($at)
    /* E1BEC 801067EC 3C098012 */  lui        $t1, %hi(D_8011E1F8)
    /* E1BF0 801067F0 2529E1F8 */  addiu      $t1, $t1, %lo(D_8011E1F8)
    /* E1BF4 801067F4 8D2A0000 */  lw         $t2, 0x0($t1)
    /* E1BF8 801067F8 11400006 */  beqz       $t2, .L80106814
    /* E1BFC 801067FC 00000000 */   nop
    /* E1C00 80106800 8D3D0004 */  lw         $sp, 0x4($t1)
    /* E1C04 80106804 0140F809 */  jalr       $t2
    /* E1C08 80106808 00402021 */   addu      $a0, $v0, $zero
    /* E1C0C 8010680C 14400003 */  bnez       $v0, .L8010681C
    /* E1C10 80106810 00000000 */   nop
  .L80106814:
    /* E1C14 80106814 0C041A65 */  jal        send_mesg
    /* E1C18 80106818 24040040 */   addiu     $a0, $zero, 0x40
  .L8010681C:
    /* E1C1C 8010681C 1220000A */  beqz       $s1, .L80106848
    /* E1C20 80106820 00000000 */   nop
  .L80106824:
    /* E1C24 80106824 32290020 */  andi       $t1, $s1, 0x20
    /* E1C28 80106828 11200007 */  beqz       $t1, .L80106848
    /* E1C2C 8010682C 00000000 */   nop
    /* E1C30 80106830 3231001F */  andi       $s1, $s1, 0x1F
    /* E1C34 80106834 24090800 */  addiu      $t1, $zero, 0x800
    /* E1C38 80106838 3C01A430 */  lui        $at, %hi(D_A4300000)
    /* E1C3C 8010683C AC290000 */  sw         $t1, %lo(D_A4300000)($at)
    /* E1C40 80106840 0C041A65 */  jal        send_mesg
    /* E1C44 80106844 24040048 */   addiu     $a0, $zero, 0x48
  .L80106848:
    /* E1C48 80106848 2401FBFF */  addiu      $at, $zero, -0x401
    /* E1C4C 8010684C 1000FF75 */  b          .L80106624
    /* E1C50 80106850 02018024 */   and       $s0, $s0, $at
  jlabel .L80106854
    /* E1C54 80106854 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* E1C58 80106858 2401EFFF */  addiu      $at, $zero, -0x1001
    /* E1C5C 8010685C 0361D824 */  and        $k1, $k1, $at
    /* E1C60 80106860 AF5B0118 */  sw         $k1, 0x118($k0) /* handwritten instruction */
    /* E1C64 80106864 3C098012 */  lui        $t1, %hi(__osShutdown)
    /* E1C68 80106868 2529E21C */  addiu      $t1, $t1, %lo(__osShutdown)
    /* E1C6C 8010686C 8D2A0000 */  lw         $t2, 0x0($t1)
    /* E1C70 80106870 11400004 */  beqz       $t2, .L80106884
    /* E1C74 80106874 00000000 */   nop
    /* E1C78 80106878 2401EFFF */  addiu      $at, $zero, -0x1001
    /* E1C7C 8010687C 10000026 */  b          .L80106918
    /* E1C80 80106880 02018024 */   and       $s0, $s0, $at
  .L80106884:
    /* E1C84 80106884 240A0001 */  addiu      $t2, $zero, 0x1
    /* E1C88 80106888 AD2A0000 */  sw         $t2, 0x0($t1)
    /* E1C8C 8010688C 0C041A65 */  jal        send_mesg
    /* E1C90 80106890 24040070 */   addiu     $a0, $zero, 0x70
    /* E1C94 80106894 2401EFFF */  addiu      $at, $zero, -0x1001
    /* E1C98 80106898 02018024 */  and        $s0, $s0, $at
    /* E1C9C 8010689C 3C0A8012 */  lui        $t2, %hi(__osRunQueue)
    /* E1CA0 801068A0 8D4ACCE8 */  lw         $t2, %lo(__osRunQueue)($t2)
    /* E1CA4 801068A4 8D5B0118 */  lw         $k1, 0x118($t2) /* handwritten instruction */
    /* E1CA8 801068A8 2401EFFF */  addiu      $at, $zero, -0x1001
    /* E1CAC 801068AC 0361D824 */  and        $k1, $k1, $at
    /* E1CB0 801068B0 10000019 */  b          .L80106918
    /* E1CB4 801068B4 AD5B0118 */   sw        $k1, 0x118($t2) /* handwritten instruction */
  jlabel .L801068B8
    /* E1CB8 801068B8 2401FDFF */  addiu      $at, $zero, -0x201
    /* E1CBC 801068BC 01014024 */  and        $t0, $t0, $at
    /* E1CC0 801068C0 40886800 */  mtc0       $t0, $13 /* handwritten instruction */
    /* E1CC4 801068C4 24040008 */  addiu      $a0, $zero, 0x8
    /* E1CC8 801068C8 0C041A65 */  jal        send_mesg
    /* E1CCC 801068CC 00000000 */   nop
    /* E1CD0 801068D0 2401FDFF */  addiu      $at, $zero, -0x201
    /* E1CD4 801068D4 1000FF53 */  b          .L80106624
    /* E1CD8 801068D8 02018024 */   and       $s0, $s0, $at
  jlabel .L801068DC
    /* E1CDC 801068DC 2401FEFF */  addiu      $at, $zero, -0x101
    /* E1CE0 801068E0 01014024 */  and        $t0, $t0, $at
    /* E1CE4 801068E4 40886800 */  mtc0       $t0, $13 /* handwritten instruction */
    /* E1CE8 801068E8 24040000 */  addiu      $a0, $zero, 0x0
    /* E1CEC 801068EC 0C041A65 */  jal        send_mesg
    /* E1CF0 801068F0 00000000 */   nop
    /* E1CF4 801068F4 2401FEFF */  addiu      $at, $zero, -0x101
    /* E1CF8 801068F8 1000FF4A */  b          .L80106624
    /* E1CFC 801068FC 02018024 */   and       $s0, $s0, $at
  .L80106900:
    /* E1D00 80106900 24090001 */  addiu      $t1, $zero, 0x1
    /* E1D04 80106904 A7490012 */  sh         $t1, 0x12($k0) /* handwritten instruction */
    /* E1D08 80106908 0C041A65 */  jal        send_mesg
    /* E1D0C 8010690C 24040050 */   addiu     $a0, $zero, 0x50
    /* E1D10 80106910 10000001 */  b          .L80106918
    /* E1D14 80106914 00000000 */   nop
  jlabel .L80106918
    /* E1D18 80106918 8F490004 */  lw         $t1, 0x4($k0) /* handwritten instruction */
    /* E1D1C 8010691C 3C0A8012 */  lui        $t2, %hi(__osRunQueue)
    /* E1D20 80106920 8D4ACCE8 */  lw         $t2, %lo(__osRunQueue)($t2)
    /* E1D24 80106924 8D4B0004 */  lw         $t3, 0x4($t2)
    /* E1D28 80106928 012B082A */  slt        $at, $t1, $t3
    /* E1D2C 8010692C 10200007 */  beqz       $at, .L8010694C
    /* E1D30 80106930 00000000 */   nop
    /* E1D34 80106934 03402821 */  addu       $a1, $k0, $zero
    /* E1D38 80106938 3C048012 */  lui        $a0, %hi(__osRunQueue)
    /* E1D3C 8010693C 0C041AE3 */  jal        __osEnqueueThread
    /* E1D40 80106940 2484CCE8 */   addiu     $a0, $a0, %lo(__osRunQueue)
    /* E1D44 80106944 08041AF9 */  j          __osDispatchThread
    /* E1D48 80106948 00000000 */   nop
  .L8010694C:
    /* E1D4C 8010694C 3C098012 */  lui        $t1, %hi(__osRunQueue)
    /* E1D50 80106950 2529CCE8 */  addiu      $t1, $t1, %lo(__osRunQueue)
    /* E1D54 80106954 8D2A0000 */  lw         $t2, 0x0($t1)
    /* E1D58 80106958 AF4A0000 */  sw         $t2, 0x0($k0) /* handwritten instruction */
    /* E1D5C 8010695C 08041AF9 */  j          __osDispatchThread
    /* E1D60 80106960 AD3A0000 */   sw        $k0, 0x0($t1) /* handwritten instruction */
  .L80106964:
    /* E1D64 80106964 3C018012 */  lui        $at, %hi(__osFaultedThread)
    /* E1D68 80106968 AC3ACCF4 */  sw         $k0, %lo(__osFaultedThread)($at) /* handwritten instruction */
    /* E1D6C 8010696C 24090001 */  addiu      $t1, $zero, 0x1
    /* E1D70 80106970 A7490010 */  sh         $t1, 0x10($k0) /* handwritten instruction */
    /* E1D74 80106974 24090002 */  addiu      $t1, $zero, 0x2
    /* E1D78 80106978 A7490012 */  sh         $t1, 0x12($k0) /* handwritten instruction */
    /* E1D7C 8010697C 400A4000 */  mfc0       $t2, $8 /* handwritten instruction */
    /* E1D80 80106980 AF4A0124 */  sw         $t2, 0x124($k0) /* handwritten instruction */
    /* E1D84 80106984 0C041A65 */  jal        send_mesg
    /* E1D88 80106988 24040060 */   addiu     $a0, $zero, 0x60
    /* E1D8C 8010698C 08041AF9 */  j          __osDispatchThread
    /* E1D90 80106990 00000000 */   nop
endlabel __osException
.size __osException, . - __osException

nonmatching send_mesg, 0xBC

glabel send_mesg
    /* E1D94 80106994 03E09021 */  addu       $s2, $ra, $zero
    /* E1D98 80106998 3C0A8021 */  lui        $t2, %hi(__osEventStateTab)
    /* E1D9C 8010699C 254A5E00 */  addiu      $t2, $t2, %lo(__osEventStateTab)
    /* E1DA0 801069A0 01445021 */  addu       $t2, $t2, $a0
    /* E1DA4 801069A4 8D490000 */  lw         $t1, 0x0($t2)
    /* E1DA8 801069A8 11200027 */  beqz       $t1, .L80106A48
    /* E1DAC 801069AC 00000000 */   nop
    /* E1DB0 801069B0 8D2B0008 */  lw         $t3, 0x8($t1)
    /* E1DB4 801069B4 8D2C0010 */  lw         $t4, 0x10($t1)
    /* E1DB8 801069B8 016C082A */  slt        $at, $t3, $t4
    /* E1DBC 801069BC 10200022 */  beqz       $at, .L80106A48
    /* E1DC0 801069C0 00000000 */   nop
    /* E1DC4 801069C4 8D2D000C */  lw         $t5, 0xC($t1)
    /* E1DC8 801069C8 01AB6821 */  addu       $t5, $t5, $t3
    /* E1DCC 801069CC 01AC001A */  div        $zero, $t5, $t4
    /* E1DD0 801069D0 15800002 */  bnez       $t4, .L801069DC
    /* E1DD4 801069D4 00000000 */   nop
    /* E1DD8 801069D8 0007000D */  break      7
  .L801069DC:
    /* E1DDC 801069DC 2401FFFF */  addiu      $at, $zero, -0x1
    /* E1DE0 801069E0 15810004 */  bne        $t4, $at, .L801069F4
    /* E1DE4 801069E4 3C018000 */   lui       $at, (0x80000000 >> 16)
    /* E1DE8 801069E8 15A10002 */  bne        $t5, $at, .L801069F4
    /* E1DEC 801069EC 00000000 */   nop
    /* E1DF0 801069F0 0006000D */  break      6
  .L801069F4:
    /* E1DF4 801069F4 00006810 */  mfhi       $t5
    /* E1DF8 801069F8 8D2C0014 */  lw         $t4, 0x14($t1)
    /* E1DFC 801069FC 24010004 */  addiu      $at, $zero, 0x4
    /* E1E00 80106A00 01A10018 */  mult       $t5, $at
    /* E1E04 80106A04 00006812 */  mflo       $t5
    /* E1E08 80106A08 018D6021 */  addu       $t4, $t4, $t5
    /* E1E0C 80106A0C 8D4D0004 */  lw         $t5, 0x4($t2)
    /* E1E10 80106A10 AD8D0000 */  sw         $t5, 0x0($t4)
    /* E1E14 80106A14 256A0001 */  addiu      $t2, $t3, 0x1
    /* E1E18 80106A18 AD2A0008 */  sw         $t2, 0x8($t1)
    /* E1E1C 80106A1C 8D2A0000 */  lw         $t2, 0x0($t1)
    /* E1E20 80106A20 8D4B0000 */  lw         $t3, 0x0($t2)
    /* E1E24 80106A24 11600008 */  beqz       $t3, .L80106A48
    /* E1E28 80106A28 00000000 */   nop
    /* E1E2C 80106A2C 0C041AF5 */  jal        __osPopThread
    /* E1E30 80106A30 01202021 */   addu      $a0, $t1, $zero
    /* E1E34 80106A34 00405021 */  addu       $t2, $v0, $zero
    /* E1E38 80106A38 01402821 */  addu       $a1, $t2, $zero
    /* E1E3C 80106A3C 3C048012 */  lui        $a0, %hi(__osRunQueue)
    /* E1E40 80106A40 0C041AE3 */  jal        __osEnqueueThread
    /* E1E44 80106A44 2484CCE8 */   addiu     $a0, $a0, %lo(__osRunQueue)
  .L80106A48:
    /* E1E48 80106A48 02400008 */  jr         $s2
    /* E1E4C 80106A4C 00000000 */   nop
endlabel send_mesg
.size send_mesg, . - send_mesg

/* Handwritten function */
nonmatching handle_CpU, 0x34

glabel handle_CpU
    /* E1E50 80106A50 3C013000 */  lui        $at, (0x30000000 >> 16)
    /* E1E54 80106A54 01014824 */  and        $t1, $t0, $at
    /* E1E58 80106A58 00094F02 */  srl        $t1, $t1, 28
    /* E1E5C 80106A5C 240A0001 */  addiu      $t2, $zero, 0x1
    /* E1E60 80106A60 152AFFC0 */  bne        $t1, $t2, .L80106964
    /* E1E64 80106A64 00000000 */   nop
    /* E1E68 80106A68 24090001 */  addiu      $t1, $zero, 0x1
    /* E1E6C 80106A6C AF490018 */  sw         $t1, 0x18($k0) /* handwritten instruction */
    /* E1E70 80106A70 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* E1E74 80106A74 3C012000 */  lui        $at, (0x20000000 >> 16)
    /* E1E78 80106A78 0361D825 */  or         $k1, $k1, $at
    /* E1E7C 80106A7C 1000FFB3 */  b          .L8010694C
    /* E1E80 80106A80 AF5B0118 */   sw        $k1, 0x118($k0) /* handwritten instruction */
endlabel handle_CpU
.size handle_CpU, . - handle_CpU

/* Handwritten function */
nonmatching __osEnqueueAndYield, 0x108

glabel __osEnqueueAndYield
    /* E1E84 80106A84 3C058012 */  lui        $a1, %hi(__osRunningThread)
    /* E1E88 80106A88 8CA5CCF0 */  lw         $a1, %lo(__osRunningThread)($a1)
    /* E1E8C 80106A8C 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
    /* E1E90 80106A90 35080002 */  ori        $t0, $t0, 0x2
    /* E1E94 80106A94 ACA80118 */  sw         $t0, 0x118($a1)
    /* E1E98 80106A98 FCB00098 */  sd         $s0, 0x98($a1)
    /* E1E9C 80106A9C FCB100A0 */  sd         $s1, 0xA0($a1)
    /* E1EA0 80106AA0 FCB200A8 */  sd         $s2, 0xA8($a1)
    /* E1EA4 80106AA4 FCB300B0 */  sd         $s3, 0xB0($a1)
    /* E1EA8 80106AA8 FCB400B8 */  sd         $s4, 0xB8($a1)
    /* E1EAC 80106AAC FCB500C0 */  sd         $s5, 0xC0($a1)
    /* E1EB0 80106AB0 FCB600C8 */  sd         $s6, 0xC8($a1)
    /* E1EB4 80106AB4 FCB700D0 */  sd         $s7, 0xD0($a1)
    /* E1EB8 80106AB8 FCBC00E8 */  sd         $gp, 0xE8($a1)
    /* E1EBC 80106ABC FCBD00F0 */  sd         $sp, 0xF0($a1)
    /* E1EC0 80106AC0 FCBE00F8 */  sd         $fp, 0xF8($a1)
    /* E1EC4 80106AC4 FCBF0100 */  sd         $ra, 0x100($a1)
    /* E1EC8 80106AC8 ACBF011C */  sw         $ra, 0x11C($a1)
    /* E1ECC 80106ACC 8CBB0018 */  lw         $k1, 0x18($a1) /* handwritten instruction */
    /* E1ED0 80106AD0 1360000A */  beqz       $k1, .L80106AFC /* handwritten instruction */
    /* E1ED4 80106AD4 00000000 */   nop
    /* E1ED8 80106AD8 445BF800 */  cfc1       $k1, $31
    /* E1EDC 80106ADC 00000000 */  nop
    /* E1EE0 80106AE0 ACBB012C */  sw         $k1, 0x12C($a1) /* handwritten instruction */
    /* E1EE4 80106AE4 F4B40180 */  sdc1       $f20, 0x180($a1)
    /* E1EE8 80106AE8 F4B60188 */  sdc1       $f22, 0x188($a1)
    /* E1EEC 80106AEC F4B80190 */  sdc1       $f24, 0x190($a1)
    /* E1EF0 80106AF0 F4BA0198 */  sdc1       $f26, 0x198($a1)
    /* E1EF4 80106AF4 F4BC01A0 */  sdc1       $f28, 0x1A0($a1)
    /* E1EF8 80106AF8 F4BE01A8 */  sdc1       $f30, 0x1A8($a1)
  .L80106AFC:
    /* E1EFC 80106AFC 8CBB0118 */  lw         $k1, 0x118($a1) /* handwritten instruction */
    /* E1F00 80106B00 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
    /* E1F04 80106B04 1120000D */  beqz       $t1, .L80106B3C
    /* E1F08 80106B08 00000000 */   nop
    /* E1F0C 80106B0C 3C088012 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* E1F10 80106B10 2508E220 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* E1F14 80106B14 8D080000 */  lw         $t0, 0x0($t0)
    /* E1F18 80106B18 2401FFFF */  addiu      $at, $zero, -0x1
    /* E1F1C 80106B1C 01014026 */  xor        $t0, $t0, $at
    /* E1F20 80106B20 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* E1F24 80106B24 01284825 */  or         $t1, $t1, $t0
    /* E1F28 80106B28 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* E1F2C 80106B2C 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* E1F30 80106B30 0361D824 */  and        $k1, $k1, $at
    /* E1F34 80106B34 0369D825 */  or         $k1, $k1, $t1
    /* E1F38 80106B38 ACBB0118 */  sw         $k1, 0x118($a1) /* handwritten instruction */
  .L80106B3C:
    /* E1F3C 80106B3C 3C1BA430 */  lui        $k1, %hi(D_A430000C) /* handwritten instruction */
    /* E1F40 80106B40 8F7B000C */  lw         $k1, %lo(D_A430000C)($k1) /* handwritten instruction */
    /* E1F44 80106B44 1360000B */  beqz       $k1, .L80106B74 /* handwritten instruction */
    /* E1F48 80106B48 00000000 */   nop
    /* E1F4C 80106B4C 3C1A8012 */  lui        $k0, %hi(__OSGlobalIntMask) /* handwritten instruction */
    /* E1F50 80106B50 275AE220 */  addiu      $k0, $k0, %lo(__OSGlobalIntMask) /* handwritten instruction */
    /* E1F54 80106B54 8F5A0000 */  lw         $k0, 0x0($k0) /* handwritten instruction */
    /* E1F58 80106B58 001AD402 */  srl        $k0, $k0, 16
    /* E1F5C 80106B5C 2401FFFF */  addiu      $at, $zero, -0x1
    /* E1F60 80106B60 0341D026 */  xor        $k0, $k0, $at
    /* E1F64 80106B64 335A003F */  andi       $k0, $k0, 0x3F /* handwritten instruction */
    /* E1F68 80106B68 8CA80128 */  lw         $t0, 0x128($a1)
    /* E1F6C 80106B6C 0348D024 */  and        $k0, $k0, $t0
    /* E1F70 80106B70 037AD825 */  or         $k1, $k1, $k0
  .L80106B74:
    /* E1F74 80106B74 10800003 */  beqz       $a0, .L80106B84
    /* E1F78 80106B78 ACBB0128 */   sw        $k1, 0x128($a1) /* handwritten instruction */
    /* E1F7C 80106B7C 0C041AE3 */  jal        __osEnqueueThread
    /* E1F80 80106B80 00000000 */   nop
  .L80106B84:
    /* E1F84 80106B84 08041AF9 */  j          __osDispatchThread
    /* E1F88 80106B88 00000000 */   nop
endlabel __osEnqueueAndYield
.size __osEnqueueAndYield, . - __osEnqueueAndYield

nonmatching __osEnqueueThread, 0x48

glabel __osEnqueueThread
    /* E1F8C 80106B8C 0080C821 */  addu       $t9, $a0, $zero
    /* E1F90 80106B90 8C980000 */  lw         $t8, 0x0($a0)
    /* E1F94 80106B94 8CAF0004 */  lw         $t7, 0x4($a1)
    /* E1F98 80106B98 8F0E0004 */  lw         $t6, 0x4($t8)
    /* E1F9C 80106B9C 01CF082A */  slt        $at, $t6, $t7
    /* E1FA0 80106BA0 14200007 */  bnez       $at, .L80106BC0
    /* E1FA4 80106BA4 00000000 */   nop
  .L80106BA8:
    /* E1FA8 80106BA8 0300C821 */  addu       $t9, $t8, $zero
    /* E1FAC 80106BAC 8F180000 */  lw         $t8, 0x0($t8)
    /* E1FB0 80106BB0 8F0E0004 */  lw         $t6, 0x4($t8)
    /* E1FB4 80106BB4 01CF082A */  slt        $at, $t6, $t7
    /* E1FB8 80106BB8 1020FFFB */  beqz       $at, .L80106BA8
    /* E1FBC 80106BBC 00000000 */   nop
  .L80106BC0:
    /* E1FC0 80106BC0 8F380000 */  lw         $t8, 0x0($t9)
    /* E1FC4 80106BC4 ACB80000 */  sw         $t8, 0x0($a1)
    /* E1FC8 80106BC8 AF250000 */  sw         $a1, 0x0($t9)
    /* E1FCC 80106BCC 03E00008 */  jr         $ra
    /* E1FD0 80106BD0 ACA40008 */   sw        $a0, 0x8($a1)
endlabel __osEnqueueThread
.size __osEnqueueThread, . - __osEnqueueThread

nonmatching __osPopThread, 0x10

glabel __osPopThread
    /* E1FD4 80106BD4 8C820000 */  lw         $v0, 0x0($a0)
    /* E1FD8 80106BD8 8C590000 */  lw         $t9, 0x0($v0)
    /* E1FDC 80106BDC 03E00008 */  jr         $ra
    /* E1FE0 80106BE0 AC990000 */   sw        $t9, 0x0($a0)
endlabel __osPopThread
.size __osPopThread, . - __osPopThread

/* Handwritten function */
nonmatching __osDispatchThread, 0x17C

glabel __osDispatchThread
    /* E1FE4 80106BE4 3C048012 */  lui        $a0, %hi(__osRunQueue)
    /* E1FE8 80106BE8 0C041AF5 */  jal        __osPopThread
    /* E1FEC 80106BEC 2484CCE8 */   addiu     $a0, $a0, %lo(__osRunQueue)
    /* E1FF0 80106BF0 3C018012 */  lui        $at, %hi(__osRunningThread)
    /* E1FF4 80106BF4 AC22CCF0 */  sw         $v0, %lo(__osRunningThread)($at)
    /* E1FF8 80106BF8 24080004 */  addiu      $t0, $zero, 0x4
    /* E1FFC 80106BFC A4480010 */  sh         $t0, 0x10($v0)
    /* E2000 80106C00 0040D021 */  addu       $k0, $v0, $zero
  .L80106C04:
    /* E2004 80106C04 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* E2008 80106C08 3C088012 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* E200C 80106C0C 2508E220 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* E2010 80106C10 8D080000 */  lw         $t0, 0x0($t0)
    /* E2014 80106C14 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* E2018 80106C18 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
    /* E201C 80106C1C 01284824 */  and        $t1, $t1, $t0
    /* E2020 80106C20 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* E2024 80106C24 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* E2028 80106C28 0361D824 */  and        $k1, $k1, $at
    /* E202C 80106C2C 0369D825 */  or         $k1, $k1, $t1
    /* E2030 80106C30 409B6000 */  mtc0       $k1, $12 /* handwritten instruction */
    /* E2034 80106C34 DF410020 */  ld         $at, 0x20($k0) /* handwritten instruction */
    /* E2038 80106C38 DF420028 */  ld         $v0, 0x28($k0) /* handwritten instruction */
    /* E203C 80106C3C DF430030 */  ld         $v1, 0x30($k0) /* handwritten instruction */
    /* E2040 80106C40 DF440038 */  ld         $a0, 0x38($k0) /* handwritten instruction */
    /* E2044 80106C44 DF450040 */  ld         $a1, 0x40($k0) /* handwritten instruction */
    /* E2048 80106C48 DF460048 */  ld         $a2, 0x48($k0) /* handwritten instruction */
    /* E204C 80106C4C DF470050 */  ld         $a3, 0x50($k0) /* handwritten instruction */
    /* E2050 80106C50 DF480058 */  ld         $t0, 0x58($k0) /* handwritten instruction */
    /* E2054 80106C54 DF490060 */  ld         $t1, 0x60($k0) /* handwritten instruction */
    /* E2058 80106C58 DF4A0068 */  ld         $t2, 0x68($k0) /* handwritten instruction */
    /* E205C 80106C5C DF4B0070 */  ld         $t3, 0x70($k0) /* handwritten instruction */
    /* E2060 80106C60 DF4C0078 */  ld         $t4, 0x78($k0) /* handwritten instruction */
    /* E2064 80106C64 DF4D0080 */  ld         $t5, 0x80($k0) /* handwritten instruction */
    /* E2068 80106C68 DF4E0088 */  ld         $t6, 0x88($k0) /* handwritten instruction */
    /* E206C 80106C6C DF4F0090 */  ld         $t7, 0x90($k0) /* handwritten instruction */
    /* E2070 80106C70 DF500098 */  ld         $s0, 0x98($k0) /* handwritten instruction */
    /* E2074 80106C74 DF5100A0 */  ld         $s1, 0xA0($k0) /* handwritten instruction */
    /* E2078 80106C78 DF5200A8 */  ld         $s2, 0xA8($k0) /* handwritten instruction */
    /* E207C 80106C7C DF5300B0 */  ld         $s3, 0xB0($k0) /* handwritten instruction */
    /* E2080 80106C80 DF5400B8 */  ld         $s4, 0xB8($k0) /* handwritten instruction */
    /* E2084 80106C84 DF5500C0 */  ld         $s5, 0xC0($k0) /* handwritten instruction */
    /* E2088 80106C88 DF5600C8 */  ld         $s6, 0xC8($k0) /* handwritten instruction */
    /* E208C 80106C8C DF5700D0 */  ld         $s7, 0xD0($k0) /* handwritten instruction */
    /* E2090 80106C90 DF5800D8 */  ld         $t8, 0xD8($k0) /* handwritten instruction */
    /* E2094 80106C94 DF5900E0 */  ld         $t9, 0xE0($k0) /* handwritten instruction */
    /* E2098 80106C98 DF5C00E8 */  ld         $gp, 0xE8($k0) /* handwritten instruction */
    /* E209C 80106C9C DF5D00F0 */  ld         $sp, 0xF0($k0) /* handwritten instruction */
    /* E20A0 80106CA0 DF5E00F8 */  ld         $fp, 0xF8($k0) /* handwritten instruction */
    /* E20A4 80106CA4 DF5F0100 */  ld         $ra, 0x100($k0) /* handwritten instruction */
    /* E20A8 80106CA8 DF5B0108 */  ld         $k1, 0x108($k0) /* handwritten instruction */
    /* E20AC 80106CAC 03600013 */  mtlo       $k1
    /* E20B0 80106CB0 DF5B0110 */  ld         $k1, 0x110($k0) /* handwritten instruction */
    /* E20B4 80106CB4 03600011 */  mthi       $k1
    /* E20B8 80106CB8 8F5B011C */  lw         $k1, 0x11C($k0) /* handwritten instruction */
    /* E20BC 80106CBC 409B7000 */  mtc0       $k1, $14 /* handwritten instruction */
    /* E20C0 80106CC0 8F5B0018 */  lw         $k1, 0x18($k0) /* handwritten instruction */
    /* E20C4 80106CC4 13600013 */  beqz       $k1, .L80106D14 /* handwritten instruction */
    /* E20C8 80106CC8 00000000 */   nop
    /* E20CC 80106CCC 8F5B012C */  lw         $k1, 0x12C($k0) /* handwritten instruction */
    /* E20D0 80106CD0 44DBF800 */  ctc1       $k1, $31
    /* E20D4 80106CD4 D7400130 */  ldc1       $f0, 0x130($k0)
    /* E20D8 80106CD8 D7420138 */  ldc1       $f2, 0x138($k0)
    /* E20DC 80106CDC D7440140 */  ldc1       $f4, 0x140($k0)
    /* E20E0 80106CE0 D7460148 */  ldc1       $f6, 0x148($k0)
    /* E20E4 80106CE4 D7480150 */  ldc1       $f8, 0x150($k0)
    /* E20E8 80106CE8 D74A0158 */  ldc1       $f10, 0x158($k0)
    /* E20EC 80106CEC D74C0160 */  ldc1       $f12, 0x160($k0)
    /* E20F0 80106CF0 D74E0168 */  ldc1       $f14, 0x168($k0)
    /* E20F4 80106CF4 D7500170 */  ldc1       $f16, 0x170($k0)
    /* E20F8 80106CF8 D7520178 */  ldc1       $f18, 0x178($k0)
    /* E20FC 80106CFC D7540180 */  ldc1       $f20, 0x180($k0)
    /* E2100 80106D00 D7560188 */  ldc1       $f22, 0x188($k0)
    /* E2104 80106D04 D7580190 */  ldc1       $f24, 0x190($k0)
    /* E2108 80106D08 D75A0198 */  ldc1       $f26, 0x198($k0)
    /* E210C 80106D0C D75C01A0 */  ldc1       $f28, 0x1A0($k0)
    /* E2110 80106D10 D75E01A8 */  ldc1       $f30, 0x1A8($k0)
  .L80106D14:
    /* E2114 80106D14 8F5B0128 */  lw         $k1, 0x128($k0) /* handwritten instruction */
    /* E2118 80106D18 3C1A8012 */  lui        $k0, %hi(__OSGlobalIntMask) /* handwritten instruction */
    /* E211C 80106D1C 275AE220 */  addiu      $k0, $k0, %lo(__OSGlobalIntMask) /* handwritten instruction */
    /* E2120 80106D20 8F5A0000 */  lw         $k0, 0x0($k0) /* handwritten instruction */
    /* E2124 80106D24 001AD402 */  srl        $k0, $k0, 16
    /* E2128 80106D28 037AD824 */  and        $k1, $k1, $k0
    /* E212C 80106D2C 001BD840 */  sll        $k1, $k1, 1
    /* E2130 80106D30 3C1A8012 */  lui        $k0, %hi(__osRcpImTable) /* handwritten instruction */
    /* E2134 80106D34 275A3C30 */  addiu      $k0, $k0, %lo(__osRcpImTable) /* handwritten instruction */
    /* E2138 80106D38 037AD821 */  addu       $k1, $k1, $k0
    /* E213C 80106D3C 977B0000 */  lhu        $k1, 0x0($k1) /* handwritten instruction */
    /* E2140 80106D40 3C1AA430 */  lui        $k0, (0xA430000C >> 16) /* handwritten instruction */
    /* E2144 80106D44 375A000C */  ori        $k0, $k0, (0xA430000C & 0xFFFF) /* handwritten instruction */
    /* E2148 80106D48 AF5B0000 */  sw         $k1, 0x0($k0) /* handwritten instruction */
    /* E214C 80106D4C 00000000 */  nop
    /* E2150 80106D50 00000000 */  nop
    /* E2154 80106D54 00000000 */  nop
    /* E2158 80106D58 00000000 */  nop
    /* E215C 80106D5C 42000018 */  eret /* handwritten instruction */
endlabel __osDispatchThread
.size __osDispatchThread, . - __osDispatchThread

nonmatching __osCleanupThread, 0xC

glabel __osCleanupThread
    /* E2160 80106D60 00002021 */  addu       $a0, $zero, $zero
    /* E2164 80106D64 0C041D3C */  jal        osDestroyThread
    /* E2168 80106D68 00000000 */   nop
endlabel __osCleanupThread
.size __osCleanupThread, . - __osCleanupThread
    /* E216C 80106D6C 00000000 */  nop
