.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.0 */

/* Handwritten function */
nonmatching osSetIntMask, 0xA0

glabel osSetIntMask
    /* DA8B0 800FF4B0 400C6000 */  mfc0       $t4, $12 /* handwritten instruction */
    /* DA8B4 800FF4B4 3182FF01 */  andi       $v0, $t4, 0xFF01
    /* DA8B8 800FF4B8 3C088012 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* DA8BC 800FF4BC 2508E220 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* DA8C0 800FF4C0 8D0B0000 */  lw         $t3, 0x0($t0)
    /* DA8C4 800FF4C4 2401FFFF */  addiu      $at, $zero, -0x1
    /* DA8C8 800FF4C8 01614026 */  xor        $t0, $t3, $at
    /* DA8CC 800FF4CC 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* DA8D0 800FF4D0 00481025 */  or         $v0, $v0, $t0
    /* DA8D4 800FF4D4 3C0AA430 */  lui        $t2, %hi(D_A430000C)
    /* DA8D8 800FF4D8 8D4A000C */  lw         $t2, %lo(D_A430000C)($t2)
    /* DA8DC 800FF4DC 11400005 */  beqz       $t2, .L800FF4F4
    /* DA8E0 800FF4E0 000B4C02 */   srl       $t1, $t3, 16
    /* DA8E4 800FF4E4 2401FFFF */  addiu      $at, $zero, -0x1
    /* DA8E8 800FF4E8 01214826 */  xor        $t1, $t1, $at
    /* DA8EC 800FF4EC 3129003F */  andi       $t1, $t1, 0x3F
    /* DA8F0 800FF4F0 01495025 */  or         $t2, $t2, $t1
  .L800FF4F4:
    /* DA8F4 800FF4F4 000A5400 */  sll        $t2, $t2, 16
    /* DA8F8 800FF4F8 004A1025 */  or         $v0, $v0, $t2
    /* DA8FC 800FF4FC 3C01003F */  lui        $at, (0x3F0000 >> 16)
    /* DA900 800FF500 00814024 */  and        $t0, $a0, $at
    /* DA904 800FF504 010B4024 */  and        $t0, $t0, $t3
    /* DA908 800FF508 000843C2 */  srl        $t0, $t0, 15
    /* DA90C 800FF50C 3C0A8012 */  lui        $t2, %hi(__osRcpImTable)
    /* DA910 800FF510 01485021 */  addu       $t2, $t2, $t0
    /* DA914 800FF514 954A3C30 */  lhu        $t2, %lo(__osRcpImTable)($t2)
    /* DA918 800FF518 3C01A430 */  lui        $at, %hi(D_A430000C)
    /* DA91C 800FF51C AC2A000C */  sw         $t2, %lo(D_A430000C)($at)
    /* DA920 800FF520 3088FF01 */  andi       $t0, $a0, 0xFF01
    /* DA924 800FF524 3169FF00 */  andi       $t1, $t3, 0xFF00
    /* DA928 800FF528 01094024 */  and        $t0, $t0, $t1
    /* DA92C 800FF52C 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* DA930 800FF530 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* DA934 800FF534 01816024 */  and        $t4, $t4, $at
    /* DA938 800FF538 01886025 */  or         $t4, $t4, $t0
    /* DA93C 800FF53C 408C6000 */  mtc0       $t4, $12 /* handwritten instruction */
    /* DA940 800FF540 00000000 */  nop
    /* DA944 800FF544 00000000 */  nop
    /* DA948 800FF548 03E00008 */  jr         $ra
    /* DA94C 800FF54C 00000000 */   nop
endlabel osSetIntMask
.size osSetIntMask, . - osSetIntMask
