.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.37.0 */

nonmatching func_800FF450, 0x4

glabel func_800FF450
    /* DA850 800FF450 00000000 */  nop
endlabel func_800FF450
.size func_800FF450, . - func_800FF450
    /* DA854 800FF454 00000000 */  nop
    /* DA858 800FF458 00000000 */  nop
    /* DA85C 800FF45C 00000000 */  nop
    /* DA860 800FF460 00000000 */  nop
    /* DA864 800FF464 00000000 */  nop
    /* DA868 800FF468 00000000 */  nop
    /* DA86C 800FF46C 00000000 */  nop
    /* DA870 800FF470 00000000 */  nop
    /* DA874 800FF474 00000000 */  nop
    /* DA878 800FF478 00000000 */  nop
    /* DA87C 800FF47C 00000000 */  nop
    /* DA880 800FF480 00000000 */  nop
    /* DA884 800FF484 00000000 */  nop
    /* DA888 800FF488 00000000 */  nop
    /* DA88C 800FF48C 00000000 */  nop
    /* DA890 800FF490 00000000 */  nop
    /* DA894 800FF494 00000000 */  nop
    /* DA898 800FF498 00000000 */  nop
    /* DA89C 800FF49C 00000000 */  nop
    /* DA8A0 800FF4A0 00000000 */  nop
    /* DA8A4 800FF4A4 00000000 */  nop
    /* DA8A8 800FF4A8 00000000 */  nop
    /* DA8AC 800FF4AC 00000000 */  nop
