"""Bank object -> .inst text (N64 SDK soundbank description format).

The .inst format is hierarchical: envelope -> sound -> instrument -> bank.
HM64 doesn't store per-instrument envelopes, so we emit a single shared
default envelope.

HM64-specific metadata (bank name, sample rate) is emitted as `# [hm64] ...`
comment headers so the .inst remains a valid SDK file while still
round-tripping via inst_reader.
"""
from libhm64.audio.wavetable.container import Bank


# Default envelope used by every instrument since HM64 doesn't store per-instrument values.
_DEFAULT_ENVELOPE = """envelope env_default {
    attackTime    = 5000;
    attackVolume  = 127;
    decayTime     = 364920;
    decayVolume   = 127;
    releaseTime   = 5000;
    releaseVolume = 0;
}
"""


def emit_inst_text(bank: Bank, sounds_subdir: str = "sounds") -> str:
    """Render a Bank object as .inst text (round-trippable via inst_reader)."""
    out: list[str] = []
    out.append(f"# Bank: {bank.name}")
    out.append(f"# Auto-generated by tools/libhm64/audio/wavetable/inst_writer.py.")
    out.append(f"# [hm64] sample_rate = {bank.sample_rate}")
    out.append("")
    out.append(_DEFAULT_ENVELOPE)

    # Per-sound and per-instrument blocks. basenote/detune live on the
    # instrument block (they're the libmus per-instrument arrays — basenote[i]
    # and detune[i] in player.c).
    for idx, inst in enumerate(bank.instruments):
        if not inst.sound.adpcm_bytes:
            out.append(f"# instrument {idx}: empty slot (no sound data)")
            out.append("")
            continue
        sound_name = f"sound_{idx:03d}"
        inst_name = f"inst_{idx:03d}"
        aifc_path = f"{sounds_subdir}/{idx:03d}.aifc"
        out.append(f'sound {sound_name} {{')
        out.append(f'    use ("{aifc_path}");')
        out.append(f'    envelope = env_default;')
        out.append(f'}}')
        out.append("")
        out.append(f'instrument {inst_name} {{')
        out.append(f'    basenote = {inst.basenote};')
        out.append(f'    detune   = {inst.detune};')
        out.append(f'    sound    = {sound_name};')
        out.append(f'}}')
        out.append("")

    # Bank block referencing instruments by index.
    bank_id = bank.name.split(".")[0]   # "BOKUJO01.WBK" -> "BOKUJO01"
    out.append(f"bank {bank_id} {{")
    for idx, inst in enumerate(bank.instruments):
        if not inst.sound.adpcm_bytes:
            continue
        out.append(f"    instrument [{idx}] = inst_{idx:03d};")
    out.append("}")
    out.append("")
    return "\n".join(out)
