#ifndef _DIALOGUE_MENU_INDICES_H_
#define _DIALOGUE_MENU_INDICES_H_

/* dialogueMenuIndex values used by showDialogueTextBox() and
 * dialogueMenuCallback() in src/game/game.c. */

#define DIALOGUE_MENU_DIARY_ROOT                 0
#define DIALOGUE_MENU_DIARY_SAVE_PROMPT          1
#define DIALOGUE_MENU_BAKERY_FOOD                2
#define DIALOGUE_MENU_BAKERY_DRINK_MENU          3
#define DIALOGUE_MENU_TAVERN_MENU                4
#define DIALOGUE_MENU_RANCH_STORE_ANIMALS_ROOT          5
#define DIALOGUE_MENU_RANCH_STORE_ANIMAL_BUY            6
#define DIALOGUE_MENU_RANCH_STORE_ANIMAL_SELL_CONFIRM   7
#define DIALOGUE_MENU_COW_FESTIVAL_ENTRY_CONFIRM 8
#define DIALOGUE_MENU_FLOWER_FESTIVAL_VOTE       9
#define DIALOGUE_MENU_SQUARE_STALL              10
#define DIALOGUE_MENU_HORSE_RACE_STALL          11
#define DIALOGUE_MENU_DOG_RACE_STALL            12
#define DIALOGUE_MENU_LIBRARY_BOOKSHELF_1       13
#define DIALOGUE_MENU_LIBRARY_BOOKSHELF_2       14
#define DIALOGUE_MENU_LIBRARY_BOOKSHELF_3       15
#define DIALOGUE_MENU_LIBRARY_BOOKSHELF_4       16
#define DIALOGUE_MENU_LIBRARY_BOOKSHELF_5       17
#define DIALOGUE_MENU_LIBRARY_BOOKSHELF_6       18
#define DIALOGUE_MENU_LIBRARY_BOOKSHELF_7       19
#define DIALOGUE_MENU_LIBRARY_BOOKSHELF_8       20
#define DIALOGUE_MENU_LIBRARY_BOOKSHELF_9       21
#define DIALOGUE_MENU_LIBRARY_BOOKSHELF_10      22
#define DIALOGUE_MENU_EVALUATION_CONTINUE_PROMPT 23

/* Segment indices within dialogue banks, used as he 3rd
 * argument of showMessageBox(). These mirror the .define aliases in the
 * corresponding src/bytecode/dialogues/*.dialogue files. */

/* shopDialogue.dialogue */
#define DIALOGUE_SHOP_BAKERY_FOOD_MENU    11
#define DIALOGUE_SHOP_BAKERY_DRINK_MENU          12
#define DIALOGUE_SHOP_RANCH_STORE_MAIN_MENU            13
#define DIALOGUE_SHOP_RANCH_STORE_BUY_MENU             14
#define DIALOGUE_SHOP_RANCH_STORE_SELL_CONFIRM         15
#define DIALOGUE_SHOP_TAVERN_MENU           18
#define DIALOGUE_SHOP_POPURIS_NOTEBOOK 40
#define DIALOGUE_SHOP_ANIMAL_NOTEBOOK 41

/* festivalOverlaySelectionsDialogue.dialogue */
#define DIALOGUE_FESTIVAL_OVERLAY_HORSE_RACE_STALL  0
#define DIALOGUE_FESTIVAL_OVERLAY_DOG_RACE_STALL    1
#define DIALOGUE_FESTIVAL_OVERLAY_SQUARE_STALL      2
#define DIALOGUE_FESTIVAL_OVERLAY_FLOWER_VOTE       6
#define DIALOGUE_FESTIVAL_OVERLAY_COW_ENTRY         7

/* libraryDialogue.dialogue: each bookshelf has two variants that
 * cover all four seasons in pairs. SPRING_WINTER is shown in spring
 * and winter; SUMMER_AUTUMN is shown in summer and autumn.
 * Matches .spring_winter_N / .summer_autumn_N aliases in the .dialogue. */
#define DIALOGUE_LIBRARY_BOOKSHELF_1_SPRING_WINTER   0
#define DIALOGUE_LIBRARY_BOOKSHELF_2_SPRING_WINTER   1
#define DIALOGUE_LIBRARY_BOOKSHELF_3_SPRING_WINTER   2
#define DIALOGUE_LIBRARY_BOOKSHELF_4_SPRING_WINTER   3
#define DIALOGUE_LIBRARY_BOOKSHELF_5_SPRING_WINTER   4
#define DIALOGUE_LIBRARY_BOOKSHELF_6_SPRING_WINTER   5
#define DIALOGUE_LIBRARY_BOOKSHELF_7_SPRING_WINTER   6
#define DIALOGUE_LIBRARY_BOOKSHELF_8_SPRING_WINTER   7
#define DIALOGUE_LIBRARY_BOOKSHELF_9_SPRING_WINTER   8
#define DIALOGUE_LIBRARY_BOOKSHELF_10_SPRING_WINTER  9
#define DIALOGUE_LIBRARY_BOOKSHELF_1_SUMMER_AUTUMN  10
#define DIALOGUE_LIBRARY_BOOKSHELF_2_SUMMER_AUTUMN  11
#define DIALOGUE_LIBRARY_BOOKSHELF_3_SUMMER_AUTUMN  12
#define DIALOGUE_LIBRARY_BOOKSHELF_4_SUMMER_AUTUMN  13
#define DIALOGUE_LIBRARY_BOOKSHELF_5_SUMMER_AUTUMN  14
#define DIALOGUE_LIBRARY_BOOKSHELF_6_SUMMER_AUTUMN  15
#define DIALOGUE_LIBRARY_BOOKSHELF_7_SUMMER_AUTUMN  16
#define DIALOGUE_LIBRARY_BOOKSHELF_8_SUMMER_AUTUMN  17
#define DIALOGUE_LIBRARY_BOOKSHELF_9_SUMMER_AUTUMN  18
#define DIALOGUE_LIBRARY_BOOKSHELF_10_SUMMER_AUTUMN 19

#endif
