#ifndef _SEQUENCE_INDICES_H_
#define _SEQUENCE_INDICES_H_

// currently defined in audio.h; might make more sense to auto-generate when building
// #define TOTAL_SEQUENCES 64

#define OPENING 0
#define TITLE_THEME 1
#define SPORTS_FESTIVAL 2
#define GOODBYE 3
#define SPRING_THEME 4
#define SUMMER_THEME 5
#define AUTUMN_THEME 6
#define WINTER_THEME 7
#define NAMING_SCREEN_THEME 8
#define FESTIVAL_THEME 9
#define SPORTS_FESTIVAL_THEME_2 10
#define SPIRIT_FESTIVAL_THEME 11
#define DOG_RACE_THEME 12
#define RACING_FESTIVAL_THEME 13
#define FESTIVAL_DANCE_THEME 14
#define MOUNTAIN_THEME 15
#define VILLAGE_THEME 16
#define POND_THEME 17
#define CHURCH_THEME 18 
#define TAVERN_THEME 19
#define WEDDING_THEME 20
#define NEW_YEAR_SUNRISE_THEME 21
#define CREDITS_THEME 22
#define BROKEN_MUSIC_BOX_THEME 23
#define MUSIC_BOX_THEME 24
#define FLUTE_PERFORMANCE 25
#define ORGAN_PERFORMANCE 26
#define OCARINA_PERFORMANCE 27
#define SLEIGH_BELLS 28
#define BAD_ENDING_THEME 29
#define VOCAL_PERFORMANCE 30
#define ENSEMBLE_PERFORMANCE 31
#define DRUM_PERFORMANCE 32
#define TYPHOON_AMBIENCE_1 33
#define TYPHOON_AMBIENCE_2 34
#define NIGHT_AMBIENCE_SPRING 35
#define NIGHT_AMBIENCE_SUMMER 36
#define NIGHT_AMBIENCE_AUTUMN 37
#define STARRY_NIGHT_FESTIVAL_THEME 38
#define BEACH_AMBIENCE_1 39
#define BEACH_AMBIENCE_2 40

#endif