"""Byte-identity round-trip test for the wavetable pipeline.

Pipeline: original .bin
  -> container.parse                  (Bank dataclass)
  -> inst_writer + aifc.write_aifc    (.inst + .aifc files)
  -> inst_reader + aifc_reader        (Bank reconstructed from files)
  -> container.pack                   (regenerated .bin)

Asserts the regenerated bytes match the original. Skipped if the source
binaries are not present (i.e. on a fresh checkout before splat extraction
or before the bootstrap commit).
"""
import tempfile
import unittest
from pathlib import Path

from libhm64.audio.wavetable import (
    aifc, aifc_reader, container, inst_reader, inst_writer,
)


REPO_ROOT = Path(__file__).resolve().parents[5]
POINTER_BIN = REPO_ROOT / "bin" / "audio" / "waveTablePointer.bin"
DATA_BIN = REPO_ROOT / "bin" / "audio" / "waveTableData.bin"


@unittest.skipUnless(POINTER_BIN.exists() and DATA_BIN.exists(),
                     "wavetable binaries not present")
class RoundTripTest(unittest.TestCase):
    def test_byte_identical_round_trip(self):
        orig_p = POINTER_BIN.read_bytes()
        orig_d = DATA_BIN.read_bytes()

        bank = container.parse(orig_p, orig_d)
        self.assertEqual(bank.name, "BOKUJO01.WBK")
        self.assertEqual(len(bank.instruments), 147)

        with tempfile.TemporaryDirectory() as td:
            out_dir = Path(td)
            sounds_dir = out_dir / "sounds"
            sounds_dir.mkdir()
            for idx, inst in enumerate(bank.instruments):
                if not inst.sound.adpcm_bytes:
                    continue
                aifc.write_aifc(sounds_dir / f"{idx:03d}.aifc",
                                inst.sound, bank.sample_rate)
            inst_path = out_dir / "BOKUJO01.inst"
            inst_path.write_text(inst_writer.emit_inst_text(bank))

            re_bank = inst_reader.parse(inst_path.read_text())
            for inst in re_bank.instruments:
                if hasattr(inst.sound, "aifc_path"):
                    inst.sound = aifc_reader.read_file(out_dir / inst.sound.aifc_path)

            new_p, new_d = container.pack(re_bank)

        self.assertEqual(len(new_p), len(orig_p),
                         f"pointer_bin length: new={len(new_p)} orig={len(orig_p)}")
        self.assertEqual(len(new_d), len(orig_d),
                         f"data_bin length: new={len(new_d)} orig={len(orig_d)}")
        self.assertEqual(new_p, orig_p, "waveTablePointer.bin not byte-identical")
        self.assertEqual(new_d, orig_d, "waveTableData.bin not byte-identical")


class ContainerOnlyRoundTripTest(unittest.TestCase):
    """Pack/parse round-trip with synthetic data (no .bin file dependency)."""

    def test_synthetic_bank_round_trip(self):
        cb = container.Codebook(order=2, npredictors=1, predictors=[0] * 16)
        sound = container.Sound(adpcm_bytes=b"\x00" * 9, codebook=cb)
        inst = container.Instrument(basenote=60, detune=41, sound=sound)
        bank = container.Bank(name="TEST.WBK", instruments=[inst])
        p, d = container.pack(bank)
        re_bank = container.parse(p, d)
        self.assertEqual(re_bank.name, "TEST.WBK")
        self.assertEqual(len(re_bank.instruments), 1)
        self.assertEqual(re_bank.instruments[0].basenote, 60)
        self.assertEqual(re_bank.instruments[0].detune, 41)
        self.assertEqual(re_bank.instruments[0].sound.adpcm_bytes, b"\x00" * 9)


if __name__ == "__main__":
    unittest.main()
