.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.26.0 */

glabel __divdi3
/* EBA50 80110650 3C088000 */  lui        $t0, (0x80000000 >> 16)
/* EBA54 80110654 00801821 */  addu       $v1, $a0, $zero
/* EBA58 80110658 00661826 */  xor        $v1, $v1, $a2
/* EBA5C 8011065C 0104C824 */  and        $t9, $t0, $a0
/* EBA60 80110660 13200007 */  beqz       $t9, .L80110680
/* EBA64 80110664 00000000 */   nop
/* EBA68 80110668 2409FFFF */  addiu      $t1, $zero, -0x1
/* EBA6C 8011066C 00A92826 */  xor        $a1, $a1, $t1
/* EBA70 80110670 00892026 */  xor        $a0, $a0, $t1
/* EBA74 80110674 24A50001 */  addiu      $a1, $a1, 0x1
/* EBA78 80110678 2CB90001 */  sltiu      $t9, $a1, 0x1
/* EBA7C 8011067C 00992021 */  addu       $a0, $a0, $t9
.L80110680:
/* EBA80 80110680 0106C824 */  and        $t9, $t0, $a2
/* EBA84 80110684 13200007 */  beqz       $t9, .L801106A4
/* EBA88 80110688 00000000 */   nop
/* EBA8C 8011068C 2409FFFF */  addiu      $t1, $zero, -0x1
/* EBA90 80110690 00E93826 */  xor        $a3, $a3, $t1
/* EBA94 80110694 00C93026 */  xor        $a2, $a2, $t1
/* EBA98 80110698 24E70001 */  addiu      $a3, $a3, 0x1
/* EBA9C 8011069C 2CF90001 */  sltiu      $t9, $a3, 0x1
/* EBAA0 801106A0 00D93021 */  addu       $a2, $a2, $t9
.L801106A4:
/* EBAA4 801106A4 00681824 */  and        $v1, $v1, $t0
/* EBAA8 801106A8 10600045 */  beqz       $v1, __udivdi3
/* EBAAC 801106AC 00000000 */   nop
/* EBAB0 801106B0 14C00006 */  bnez       $a2, .L801106CC
/* EBAB4 801106B4 00000000 */   nop
/* EBAB8 801106B8 03E06821 */  addu       $t5, $ra, $zero
/* EBABC 801106BC 0C044161 */  jal        func_80110584
/* EBAC0 801106C0 00000000 */   nop
/* EBAC4 801106C4 080441B7 */  j          .L801106DC
/* EBAC8 801106C8 01A0F821 */   addu      $ra, $t5, $zero
.L801106CC:
/* EBACC 801106CC 03E06821 */  addu       $t5, $ra, $zero
/* EBAD0 801106D0 0C044122 */  jal        func_80110488
/* EBAD4 801106D4 00000000 */   nop
/* EBAD8 801106D8 01A0F821 */  addu       $ra, $t5, $zero
.L801106DC:
/* EBADC 801106DC 2407FFFF */  addiu      $a3, $zero, -0x1
/* EBAE0 801106E0 00671826 */  xor        $v1, $v1, $a3
/* EBAE4 801106E4 00471026 */  xor        $v0, $v0, $a3
/* EBAE8 801106E8 24630001 */  addiu      $v1, $v1, 0x1
/* EBAEC 801106EC 2C790001 */  sltiu      $t9, $v1, 0x1
/* EBAF0 801106F0 03E00008 */  jr         $ra
/* EBAF4 801106F4 00591021 */   addu      $v0, $v0, $t9
/* EBAF8 801106F8 00000000 */  nop
/* EBAFC 801106FC 00000000 */  nop
/* EBB00 80110700 3C088000 */  lui        $t0, (0x80000000 >> 16)
/* EBB04 80110704 00801821 */  addu       $v1, $a0, $zero
/* EBB08 80110708 0104C824 */  and        $t9, $t0, $a0
/* EBB0C 8011070C 13200007 */  beqz       $t9, .L8011072C
/* EBB10 80110710 00000000 */   nop
/* EBB14 80110714 2409FFFF */  addiu      $t1, $zero, -0x1
/* EBB18 80110718 00A92826 */  xor        $a1, $a1, $t1
/* EBB1C 8011071C 00892026 */  xor        $a0, $a0, $t1
/* EBB20 80110720 24A50001 */  addiu      $a1, $a1, 0x1
/* EBB24 80110724 2CB90001 */  sltiu      $t9, $a1, 0x1
/* EBB28 80110728 00992021 */  addu       $a0, $a0, $t9
.L8011072C:
/* EBB2C 8011072C 0106C824 */  and        $t9, $t0, $a2
/* EBB30 80110730 13200007 */  beqz       $t9, .L80110750
/* EBB34 80110734 00000000 */   nop
/* EBB38 80110738 2409FFFF */  addiu      $t1, $zero, -0x1
/* EBB3C 8011073C 00E93826 */  xor        $a3, $a3, $t1
/* EBB40 80110740 00C93026 */  xor        $a2, $a2, $t1
/* EBB44 80110744 24E70001 */  addiu      $a3, $a3, 0x1
/* EBB48 80110748 2CF90001 */  sltiu      $t9, $a3, 0x1
/* EBB4C 8011074C 00D93021 */  addu       $a2, $a2, $t9
.L80110750:
/* EBB50 80110750 00681824 */  and        $v1, $v1, $t0
/* EBB54 80110754 10600022 */  beqz       $v1, __umoddi3
/* EBB58 80110758 00000000 */   nop
/* EBB5C 8011075C 14C00008 */  bnez       $a2, .L80110780
/* EBB60 80110760 00000000 */   nop
/* EBB64 80110764 03E06821 */  addu       $t5, $ra, $zero
/* EBB68 80110768 0C044161 */  jal        func_80110584
/* EBB6C 8011076C 00000000 */   nop
/* EBB70 80110770 01A0F821 */  addu       $ra, $t5, $zero
/* EBB74 80110774 01201821 */  addu       $v1, $t1, $zero
/* EBB78 80110778 080441E6 */  j          .L80110798
/* EBB7C 8011077C 00421026 */   xor       $v0, $v0, $v0
.L80110780:
/* EBB80 80110780 03E06821 */  addu       $t5, $ra, $zero
/* EBB84 80110784 0C044122 */  jal        func_80110488
/* EBB88 80110788 00000000 */   nop
/* EBB8C 8011078C 01A0F821 */  addu       $ra, $t5, $zero
/* EBB90 80110790 00A01821 */  addu       $v1, $a1, $zero
/* EBB94 80110794 00801021 */  addu       $v0, $a0, $zero
.L80110798:
/* EBB98 80110798 2407FFFF */  addiu      $a3, $zero, -0x1
/* EBB9C 8011079C 00671826 */  xor        $v1, $v1, $a3
/* EBBA0 801107A0 00471026 */  xor        $v0, $v0, $a3
/* EBBA4 801107A4 24630001 */  addiu      $v1, $v1, 0x1
/* EBBA8 801107A8 2C790001 */  sltiu      $t9, $v1, 0x1
/* EBBAC 801107AC 03E00008 */  jr         $ra
/* EBBB0 801107B0 00591021 */   addu      $v0, $v0, $t9
/* EBBB4 801107B4 00000000 */  nop
/* EBBB8 801107B8 00000000 */  nop
/* EBBBC 801107BC 00000000 */  nop
.size __divdi3, . - __divdi3
