.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.26.0 */

glabel __udivdi3
/* EBBC0 801107C0 14C00003 */  bnez       $a2, .L801107D0
/* EBBC4 801107C4 00000000 */   nop
/* EBBC8 801107C8 08044161 */  j          func_80110584
/* EBBCC 801107CC 00000000 */   nop
.L801107D0:
/* EBBD0 801107D0 08044122 */  j          func_80110488
/* EBBD4 801107D4 00000000 */   nop
/* EBBD8 801107D8 00000000 */  nop
/* EBBDC 801107DC 00000000 */  nop
.size __udivdi3, . - __udivdi3
