.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.26.0 */

glabel __umoddi3
/* EBBE0 801107E0 14C00008 */  bnez       $a2, .L80110804
/* EBBE4 801107E4 00000000 */   nop
/* EBBE8 801107E8 03E06821 */  addu       $t5, $ra, $zero
/* EBBEC 801107EC 0C044161 */  jal        func_80110584
/* EBBF0 801107F0 00000000 */   nop
/* EBBF4 801107F4 01A0F821 */  addu       $ra, $t5, $zero
/* EBBF8 801107F8 01201821 */  addu       $v1, $t1, $zero
/* EBBFC 801107FC 03E00008 */  jr         $ra
/* EBC00 80110800 00421026 */   xor       $v0, $v0, $v0
.L80110804:
/* EBC04 80110804 03E06821 */  addu       $t5, $ra, $zero
/* EBC08 80110808 0C044122 */  jal        func_80110488
/* EBC0C 8011080C 00000000 */   nop
/* EBC10 80110810 01A0F821 */  addu       $ra, $t5, $zero
/* EBC14 80110814 00A01821 */  addu       $v1, $a1, $zero
/* EBC18 80110818 03E00008 */  jr         $ra
/* EBC1C 8011081C 00801021 */   addu      $v0, $a0, $zero
.size __umoddi3, . - __umoddi3
