#ifndef _FARM_RANKINGs_SPRITE_BUFFER_H_
#define _FARM_RANKINGs_SPRITE_BUFFER_H_

#define FARM_RANKINGS_TEXTURE_BUFFER                   0x8026F000
#define FARM_RANKINGS_PALETTE_BUFFER                   0x8027E200
#define FARM_RANKINGS_ANIMATION_FRAME_METADATA_BUFFER  0x8027E700
#define FARM_RANKINGS_TEXTURE_TO_PALETTE_LOOKUP_BUFFER 0x8027EB00

#endif

