#ifndef _OVERLAY_SCREEN_BUFFER_H_
#define _OVERLAY_SCREEN_BUFFER_H_

#define OVERLAY_SCREEN_TEXTURE_BUFFER 0x8026F000
#define OVERLAY_SCREEN_PALETTE_BUFFER 0x8027E200
#define OVERLAY_SCREEN_ANIMATION_FRAME_METADATA_BUFFER 0x8027E700
#define OVERLAY_SCREEN_TEXTURE_TO_PALETTE_LOOKUP_BUFFER 0x8027EB00

#define OVERLAY_SCREEN_PAUSE_SCREEN_MAP_TEXTURE_BUFFER 0x8026F000
#define OVERLAY_SCREEN_PAUSE_SCREEN_MAP_PALETTE_BUFFER 0x80282000
#define OVERLAY_SCREEN_PAUSE_SCREEN_MAP_ANIMATION_FRAME_METADATA_BUFFER 0x80282300
#define OVERLAY_SCREEN_PAUSE_SCREEN_MAP_TEXTURE_TO_PALETTE_LOOKUP_BUFFER 0x80282400

#define OVERLAY_SCREEN_CLOCK_TEXTURE_BUFFER 0x8027EC00
#define OVERLAY_SCREEN_CLOCK_PALETTE_BUFFER 0x80281E00
#define OVERLAY_SCREEN_CLOCK_ANIMATION_FRAME_METADATA_BUFFER 0x80282200
#define OVERLAY_SCREEN_CLOCK_TEXTURE_TO_PALETTE_LOOKUP_BUFFER 0x80282400

#define OVERLAY_SCREEN_RECIPE_LABELS_TEXTURE_BUFFER 0x8027EC00
#define OVERLAY_SCREEN_RECIPE_LABELS_PALETTE_BUFFER 0x80289400
#define OVERLAY_SCREEN_RECIPE_LABELS_ANIMATION_FRAME_METADATA_BUFFER 0x80289500
#define OVERLAY_SCREEN_RECIPE_LABELS_TEXTURE_TO_PALETTE_LOOKUP_BUFFER 0x80289800

#define OVERLAY_SCREEN_HOLDABLE_ITEMS_TEXTURE_1_BASE               0x80293000
#define OVERLAY_SCREEN_HOLDABLE_ITEMS_TEXTURE_2_BASE               0x80293300
#define OVERLAY_SCREEN_HOLDABLE_ITEMS_TEXTURE_SIZE                 0x300

#define OVERLAY_SCREEN_KEY_ITEMS_TEXTURE_1_BASE                    0x80296600
#define OVERLAY_SCREEN_KEY_ITEMS_TEXTURE_2_BASE                    0x80296900
#define OVERLAY_SCREEN_KEY_ITEMS_TEXTURE_SIZE                      0x300

// Shared metadata for holdable items and key items
#define OVERLAY_SCREEN_ITEMS_GRID_PALETTE                          0x8029F600
#define OVERLAY_SCREEN_ITEMS_GRID_ANIM_METADATA                    0x802A1E00
#define OVERLAY_SCREEN_ITEMS_GRID_SPRITESHEET_INDEX                0x802A5300
#define OVERLAY_SCREEN_ITEMS_GRID_TEXTURE_TO_PALETTE_LOOKUP                   0x802A5500

#define OVERLAY_SCREEN_SNAPSHOT_TEXTURE_BUFFER                     0x80289900
#define OVERLAY_SCREEN_SNAPSHOT_PALETTE                            0x8028EF00
#define OVERLAY_SCREEN_SNAPSHOT_ANIM_METADATA                      0x8028F000
#define OVERLAY_SCREEN_SNAPSHOT_SPRITESHEET_INDEX                  0x8028F100

#define OVERLAY_SCREEN_TOOL_SPRITES_TEXTURE_1_BASE                 0x8028FA00
#define OVERLAY_SCREEN_TOOL_SPRITES_TEXTURE_2_BASE                 0x8028FD00
#define OVERLAY_SCREEN_TOOL_SPRITES_TEXTURE_SIZE                   0x300

// Shared metadata for tool sprites
#define OVERLAY_SCREEN_TOOL_SPRITES_PALETTE                        0x80299600
#define OVERLAY_SCREEN_TOOL_SPRITES_ANIM_METADATA                  0x8029BE00
#define OVERLAY_SCREEN_TOOL_SPRITES_SPRITESHEET_INDEX              0x8029EE00
#define OVERLAY_SCREEN_TOOL_SPRITES_TEXTURE_TO_PALETTE_LOOKUP                 0x8029F000

// ============================================================================
// Album Photos (4 photo slots)
// ============================================================================
#define OVERLAY_SCREEN_ALBUM_PHOTO_SLOT_1_TEXTURE_1                0x8028FA00
#define OVERLAY_SCREEN_ALBUM_PHOTO_SLOT_1_TEXTURE_2                0x80292A00
#define OVERLAY_SCREEN_ALBUM_PHOTO_SLOT_2_TEXTURE_1                0x80295A00
#define OVERLAY_SCREEN_ALBUM_PHOTO_SLOT_2_TEXTURE_2                0x80298A00
#define OVERLAY_SCREEN_ALBUM_PHOTO_SLOT_3_TEXTURE_1                0x8029BA00
#define OVERLAY_SCREEN_ALBUM_PHOTO_SLOT_3_TEXTURE_2                0x8029EA00
#define OVERLAY_SCREEN_ALBUM_PHOTO_SLOT_4_TEXTURE_1                0x802A1A00
#define OVERLAY_SCREEN_ALBUM_PHOTO_SLOT_4_TEXTURE_2                0x802A4A00

// Shared metadata for album photos
#define OVERLAY_SCREEN_ALBUM_PHOTOS_PALETTE                        0x802A7A00
#define OVERLAY_SCREEN_ALBUM_PHOTOS_ANIM_METADATA                  0x802AA200
#define OVERLAY_SCREEN_ALBUM_PHOTOS_SPRITESHEET_INDEX              0x802AA600
#define OVERLAY_SCREEN_ALBUM_PHOTOS_TEXTURE_TO_PALETTE_LOOKUP                 0x802AA800

#define OVERLAY_SCREEN_ESIMATE_SCREEN_NUMBERS_TEXTURE_BUFFER 0x8028F200
#define OVERLAY_SCREEN_ESIMATE_SCREEN_NUMBERS_PALETTE_BUFFER 0x8028F880
#define OVERLAY_SCREEN_ESIMATE_SCREEN_NUMBERS_ANIMATION_FRAME_METADATA_BUFFER 0x8028F900
#define OVERLAY_SCREEN_ESIMATE_SCREEN_NUMBERS_TEXTURE_TO_PALETTE_LOOKUP_BUFFER 0x8028F9C0

#define OVERLAY_SCREEN_BACKGROUND_TEXTURE_BUFFER 0x802DE5C0
#define OVERLAY_SCREEN_BACKGROUND_PALETTE_BUFFER 0x802E0BC0
#define OVERLAY_SCREEN_BACKGROUND_ANIMATION_FRAME_METADATA_BUFFER 0x802E0CC0
#define OVERLAY_SCREEN_BACKGROUND_TEXTURE_TO_PALETTE_LOOKUP_BUFFER 0x802E0DC0

#endif