#ifndef _SHOP_ITEMS_BUFFER_H_
#define _SHOP_ITEMS_BUFFER_H_

#define SHOP_DISPLAY_SIZE_TEX           0x208
#define SHOP_DISPLAY_OFFSET_TEX2        (SHOP_DISPLAY_SIZE_TEX)
#define SHOP_DISPLAY_SLOT_SIZE          0x410

#define SHOP_DISPLAY_REGION_1_BASE      0x8028D530  // Slots 1-2
#define SHOP_DISPLAY_REGION_2_BASE      0x802A3E50  // Slots 3-9

#define SHOP_DISPLAY_TEX1(base, n)      (u8*)((base) + SHOP_DISPLAY_SLOT_SIZE * (n))
#define SHOP_DISPLAY_TEX2(base, n)      (u8*)((base) + SHOP_DISPLAY_SLOT_SIZE * (n) + SHOP_DISPLAY_OFFSET_TEX2)

#define SHOP_ICONS_TEXTURE_BUFFER 0x802E0EC0
#define SHOP_ICONS_PALETTE_BUFFER 0x802E27C0
#define SHOP_ICONS_ANIMATION_FRAME_METADATA_BUFFER 0x802E28C0 
#define SHOP_ICONS_TEXTURE_TO_PALETTE_LOOKUP_BUFFER 0x802E2BC0

#endif