"""Scan spec files for segments whose include path ends in `.yay0.o`
and emit a C header declaring the runtime compressed-range table.

Invoked from the Makefile:
    python3 -m libhm64.yay0.generate_ranges <out.h> <spec1> [<spec2> ...]

The generated header declares:
    extern u8 _<name>SegmentRomStart[];     for each compressed segment
    static const CompressedRange sCompressedRanges[] = { ... };

and is included from lib/yay0/yay0.c.
"""

import re
import sys
from pathlib import Path


_NAME_RE = re.compile(r'name\s+"([^"]+)"')
_INC_RE = re.compile(r'include\s+"([^"]+)"')


def find_compressed_segments(spec_paths):
    names = []
    for sp in spec_paths:
        text = Path(sp).read_text()
        current = None
        in_seg = False
        for raw in text.splitlines():
            line = raw.strip()
            if line.startswith("//") or line.startswith("#"):
                continue
            if line == "beginseg" or line.startswith("beginseg"):
                in_seg = True
                current = None
                continue
            if line.startswith("endseg"):
                in_seg = False
                current = None
                continue
            if not in_seg:
                continue
            m = _NAME_RE.search(line)
            if m:
                current = m.group(1)
                continue
            m = _INC_RE.search(line)
            if m and m.group(1).endswith(".yay0.o") and current:
                names.append(current)
    # de-dup while preserving first occurrence
    seen = set()
    ordered = []
    for n in names:
        if n in seen:
            continue
        seen.add(n)
        ordered.append(n)
    return ordered


def emit(out_path, names):
    lines = [
        "// Auto-generated by tools/libhm64/yay0/generate_ranges.py — do not edit.",
        "// Regenerated whenever a .spec file changes.",
        "",
    ]
    for n in names:
        lines.append(f"extern u8 _{n}SegmentRomStart[];")
    lines.append("")
    lines.append("static const CompressedRange sCompressedRanges[] = {")
    for n in names:
        lines.append(f"    {{ (u32)_{n}SegmentRomStart }},")
    if not names:
        # C89 doesn't allow empty arrays; emit a dummy sentinel that's never matched.
        lines.append("    { 0 },")
    lines.append("};")
    lines.append("")
    Path(out_path).write_text("\n".join(lines))


def main(argv):
    if len(argv) < 3:
        print("usage: generate_ranges.py <out.h> <spec> [<spec> ...]", file=sys.stderr)
        return 1
    out_path = argv[1]
    spec_paths = argv[2:]
    names = find_compressed_segments(spec_paths)
    emit(out_path, names)
    print(f"yay0 ranges: {len(names)} segments → {out_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
